# Appendix C1. VSRI: Sensitivity of LSTM Results to Random Initialization

In [ ]:
# --- ENV FIRST ---
import os
os.environ["TF_DETERMINISTIC_OPS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["TF_NUM_INTRAOP_THREADS"] = "1"
os.environ["TF_NUM_INTEROP_THREADS"] = "1"
# --- IMPORTS ---
import random
import numpy as np
import tensorflow as tf
# --- TF CONFIG ---
tf.config.threading.set_inter_op_parallelism_threads(1)
tf.config.threading.set_intra_op_parallelism_threads(1)
tf.config.set_visible_devices([], 'GPU')
# --- RESET ---
tf.keras.backend.clear_session()

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import recall_score, f1_score, roc_auc_score, confusion_matrix, accuracy_score, roc_curve, precision_score
import itertools
from sklearn.utils.class_weight import compute_class_weight
from tensorflow import keras
from tensorflow.keras import layers
try:
  import keras_tuner as kt
except:
  !pip install keras-tuner
  import keras_tuner as kt
from google.colab import files
from google.colab import drive
import pandas as pd
import io
import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.1)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.80.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.4.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 1.2 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [ ]:
def import_data(file_path):
  try:
    drive.mount('/content/drive', force_remount=True)
    # Check if file exists
    if os.path.exists(file_path):
      df = pd.read_parquet(file_path)
      print(f"Loaded dataframe from Drive ({file_path})")
    else:
      raise FileNotFoundError(f"File not found at {file_path}")

  except Exception as e:
    print(f"Drive not available or file missing: {e}")
    print("Please upload dataframe manually.")
    uploaded = files.upload()

    # Automatically read the uploaded file
    file_name = list(uploaded.keys())[0]  # pick the first uploaded file
    try:
      df = pd.read_parquet(io.BytesIO(uploaded[file_name]))
    except:
      print("Wrong file extension. Parquet file required.")
    print(f"Loaded {file_name} from manual upload.")
    return df

In [ ]:
def train_classifier(model, X_train, y_train, X_test, y_test, X_val=False, y_val=False, threshold=0.5, early_stopping=False):
  is_keras = hasattr(model, "fit") and hasattr(model, "predict") and not hasattr(model, "predict_proba")
  if is_keras:
    if early_stopping:
      model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, class_weight=class_weight, validation_data=(X_val, y_val), shuffle=False, callbacks=[combined_metric, es])
    else:
      model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, class_weight=class_weight, validation_data=(X_val, y_val), shuffle=False)
    y_score = model.predict(X_test).ravel()
    y_pred = (y_score >= threshold).astype(int)
  else:
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_score = model.predict_proba(X_test)[:, 1]

  # Output Following Metrics:
  recall = recall_score(y_test, y_pred)
  f1 = f1_score(y_test, y_pred)
  roc_auc = roc_auc_score(y_test, y_score)
  cm = confusion_matrix(y_test, y_pred)

  return recall, f1, roc_auc, cm, y_score, y_pred

In [ ]:
file_path = "..."
df_sse = import_data(file_path)

Drive not available or file missing: Error: credential propagation was unsuccessful
Please upload dataframe manually.

Saving df_sse.parquet to df_sse.parquet
Loaded df_sse.parquet from manual upload.

In [ ]:
vsri_lstm = import_data(file_path)

Drive not available or file missing: Error: credential propagation was unsuccessful
Please upload dataframe manually.

Saving vsri_lstm.parquet to vsri_lstm.parquet
Loaded vsri_lstm.parquet from manual upload.

In [ ]:
# build a dataframe with the VSRI_LSTM and the Systemic Stress Events variable (target)
df_model_lstm = pd.concat([vsri_lstm, df_sse['systemic_stress_event']], axis=1, join='inner').dropna()
# split data in training and test set and apply purging
split_date = "2024-03-31"
purge = 20
train = df_model_lstm.loc[:split_date].iloc[:-purge]
test = df_model_lstm[df_model_lstm.index > split_date]
X_train = train[["VSRI_LSTM"]]
y_train = train["systemic_stress_event"]
X_test  = test[["VSRI_LSTM"]]
y_test  = test["systemic_stress_event"]

In [ ]:
timesteps = 60
split_idx = pd.Timestamp("2023-03-01")
X_train_lstm = X_train[X_train.index < split_idx].iloc[:-purge]
y_train_lstm = y_train[y_train.index < split_idx].iloc[:-purge]
X_val_lstm = X_train.loc[split_idx:]
y_val_lstm = y_train.loc[split_idx:]

X_train_values = X_train_lstm.values
y_train_values = y_train_lstm.values
X_test_values = X_test.values
y_test_values = y_test.values
X_val_values = X_val_lstm.values
y_val_values = y_val_lstm.values
X_train_seq = []
y_train_seq = []
X_test_seq = []
y_test_seq = []
X_val_seq = []
y_val_seq = []

for i in range(timesteps, len(X_train_values)):
  X_train_seq.append(X_train_values[i - timesteps:i])
  y_train_seq.append(y_train_values[i])
for i in range(timesteps, len(X_test_values)):
  X_test_seq.append(X_test_values[i - timesteps:i])
  y_test_seq.append(y_test_values[i])
for i in range(timesteps, len(X_val_values)):
  X_val_seq.append(X_val_values[i - timesteps:i])
  y_val_seq.append(y_val_values[i])

X_train_seq = np.array(X_train_seq)
y_train_seq = np.array(y_train_seq)
X_test_seq = np.array(X_test_seq)
y_test_seq = np.array(y_test_seq)
X_val_seq = np.array(X_val_seq)
y_val_seq = np.array(y_val_seq)

In [ ]:
print(X_train_seq.shape,
      y_train_seq.shape,
      X_val_seq.shape,
      y_val_seq.shape,
      X_test_seq.shape,
      y_test_seq.shape)

(1457, 60, 1) (1457,) (192, 60, 1) (192,) (416, 60, 1) (416,)

In [ ]:
class CombinedMetric(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs=None):
    logs = logs or {}
    recall = logs.get("val_recall", 0)
    pr_auc = logs.get("val_pr_auc", 0)
    logs["val_combined"] = 0.3 * recall + 0.7 * pr_auc

In [ ]:
classes = np.unique(y_train_seq)
weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train_seq)
class_weight = dict(zip(classes, weights))
epochs=200
batch_size=32

In [ ]:
seeds = [38, 60, 96, 146, 162]
robustness_results = []
input_shape = X_train_seq.shape[1:]

In [ ]:
for seed in seeds:
  print(f"\nRunning seed {seed}")
  tf.keras.backend.clear_session()
  random.seed(seed)
  np.random.seed(seed)
  tf.keras.utils.set_random_seed(seed)

  # LSTM MODEL
  lstm_model = keras.Sequential()
  lstm_model.add(layers.LSTM(128, return_sequences=True, input_shape=input_shape))
  lstm_model.add(layers.Dropout(0.5))
  lstm_model.add(layers.LSTM(128, return_sequences=True))
  lstm_model.add(layers.LSTM(16, return_sequences=True))
  lstm_model.add(layers.LSTM(8, return_sequences=True))
  lstm_model.add(layers.Dropout(0.3))
  lstm_model.add(layers.LSTM(8, return_sequences=False))
  lstm_model.add(layers.Dropout(0.3))
  # Dense layers
  lstm_model.add(layers.Dense(16, activation="relu"))
  lstm_model.add(layers.Dense(1, activation="sigmoid"))
  # Compile
  lstm_model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.0001),
                     loss="binary_crossentropy",
                     metrics=[keras.metrics.AUC(name="pr_auc", curve="PR"),
                              keras.metrics.AUC(name="roc_auc", curve="ROC"),
                              tf.keras.metrics.Recall(name="recall"),
                              tf.keras.metrics.Precision(name="precision")])

  combined_metric = CombinedMetric()
  es = tf.keras.callbacks.EarlyStopping(monitor="val_combined",
                                        mode="max",
                                        patience=50,
                                        restore_best_weights=True,
                                        verbose=1)

  # TRAIN
  lstm_results = train_classifier(lstm_model, X_train_seq, y_train_seq, X_test_seq, y_test_seq, X_val=X_val_seq, y_val=y_val_seq, early_stopping=True)
  (lstm_recall, lstm_f1, lstm_roc_auc, lstm_cm, lstm_probs, lstm_preds) = lstm_results
  # Store results
  robustness_results.append({"seed": seed,
                             "recall": lstm_recall,
                             "f1": lstm_f1,
                             "roc_auc": lstm_roc_auc,
                             "tn": lstm_cm[0,0],
                             "fp": lstm_cm[0,1],
                             "fn": lstm_cm[1,0],
                             "tp": lstm_cm[1,1]})

Running seed 38

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 23s 253ms/step - loss: 0.6935 - pr_auc: 0.0731 - precision: 0.0556 - recall: 0.4483 - roc_auc: 0.4836 - val_loss: 0.6930 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 2/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 245ms/step - loss: 0.6934 - pr_auc: 0.0782 - precision: 0.0742 - recall: 0.6983 - roc_auc: 0.4976 - val_loss: 0.6940 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 3/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 247ms/step - loss: 0.6934 - pr_auc: 0.0785 - precision: 0.0729 - recall: 0.7759 - roc_auc: 0.4985 - val_loss: 0.6935 - val_pr_auc: 0.0521 - val_precision: 0.0524 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 4/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 244ms/step - loss: 0.6932 - pr_auc: 0.0796 - precision: 0.0648 - recall: 0.5603 - roc_auc: 0.5000 - val_loss: 0.6941 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 5/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 239ms/step - loss: 0.6933 - pr_auc: 0.0793 - precision: 0.0777 - recall: 0.8793 - roc_auc: 0.4996 - val_loss: 0.6944 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 6/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 216ms/step - loss: 0.6933 - pr_auc: 0.0790 - precision: 0.0723 - recall: 0.7241 - roc_auc: 0.4993 - val_loss: 0.6945 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 7/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 246ms/step - loss: 0.6932 - pr_auc: 0.0796 - precision: 0.0734 - recall: 0.7414 - roc_auc: 0.5000 - val_loss: 0.6943 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 8/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6932 - pr_auc: 0.0796 - precision: 0.0702 - recall: 0.7241 - roc_auc: 0.5000 - val_loss: 0.6946 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 9/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6932 - pr_auc: 0.0796 - precision: 0.0753 - recall: 0.6983 - roc_auc: 0.5000 - val_loss: 0.6942 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 10/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 231ms/step - loss: 0.6933 - pr_auc: 0.0790 - precision: 0.0701 - recall: 0.6897 - roc_auc: 0.4993 - val_loss: 0.6943 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 11/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6932 - pr_auc: 0.0796 - precision: 0.0772 - recall: 0.7069 - roc_auc: 0.5000 - val_loss: 0.6944 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 12/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6933 - pr_auc: 0.0790 - precision: 0.0706 - recall: 0.6552 - roc_auc: 0.4993 - val_loss: 0.6945 - val_pr_auc: 0.0521 - val_precision: 0.0524 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 13/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 228ms/step - loss: 0.6933 - pr_auc: 0.0796 - precision: 0.0629 - recall: 0.3707 - roc_auc: 0.5000 - val_loss: 0.6949 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 14/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 227ms/step - loss: 0.6932 - pr_auc: 0.0796 - precision: 0.0753 - recall: 0.7586 - roc_auc: 0.5000 - val_loss: 0.6949 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 15/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6932 - pr_auc: 0.0788 - precision: 0.0796 - recall: 0.8707 - roc_auc: 0.4989 - val_loss: 0.6948 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 16/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6932 - pr_auc: 0.0790 - precision: 0.0718 - recall: 0.7500 - roc_auc: 0.4993 - val_loss: 0.6952 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 17/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 228ms/step - loss: 0.6932 - pr_auc: 0.0788 - precision: 0.0754 - recall: 0.7414 - roc_auc: 0.4989 - val_loss: 0.6953 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 18/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 228ms/step - loss: 0.6932 - pr_auc: 0.0776 - precision: 0.0768 - recall: 0.7414 - roc_auc: 0.4966 - val_loss: 0.6953 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 19/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6931 - pr_auc: 0.0804 - precision: 0.0766 - recall: 0.7328 - roc_auc: 0.5010 - val_loss: 0.6955 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 20/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.6932 - pr_auc: 0.0768 - precision: 0.0781 - recall: 0.8017 - roc_auc: 0.4946 - val_loss: 0.6958 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 21/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6933 - pr_auc: 0.0854 - precision: 0.0769 - recall: 0.8276 - roc_auc: 0.5122 - val_loss: 0.6960 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 22/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 228ms/step - loss: 0.6931 - pr_auc: 0.0736 - precision: 0.0736 - recall: 0.7845 - roc_auc: 0.4842 - val_loss: 0.6956 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 23/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 229ms/step - loss: 0.6932 - pr_auc: 0.0740 - precision: 0.0813 - recall: 0.8621 - roc_auc: 0.4852 - val_loss: 0.6956 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 24/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 210ms/step - loss: 0.6932 - pr_auc: 0.0729 - precision: 0.0830 - recall: 0.7931 - roc_auc: 0.4821 - val_loss: 0.6955 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 25/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 238ms/step - loss: 0.6931 - pr_auc: 0.0781 - precision: 0.0824 - recall: 0.7759 - roc_auc: 0.4964 - val_loss: 0.6955 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 26/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 13s 276ms/step - loss: 0.6932 - pr_auc: 0.0784 - precision: 0.0796 - recall: 0.7586 - roc_auc: 0.4970 - val_loss: 0.6955 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 27/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 231ms/step - loss: 0.6932 - pr_auc: 0.0789 - precision: 0.0814 - recall: 0.7672 - roc_auc: 0.4983 - val_loss: 0.6954 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 28/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 229ms/step - loss: 0.6930 - pr_auc: 0.0821 - precision: 0.0837 - recall: 0.6983 - roc_auc: 0.5062 - val_loss: 0.6961 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 29/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 213ms/step - loss: 0.6930 - pr_auc: 0.0901 - precision: 0.0791 - recall: 0.7845 - roc_auc: 0.5295 - val_loss: 0.6967 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 30/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6931 - pr_auc: 0.0823 - precision: 0.0818 - recall: 0.8190 - roc_auc: 0.5099 - val_loss: 0.6973 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 31/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 229ms/step - loss: 0.6931 - pr_auc: 0.0829 - precision: 0.0847 - recall: 0.8190 - roc_auc: 0.5120 - val_loss: 0.6976 - val_pr_auc: 0.0334 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.2775 - val_combined: 0.3233
Epoch 32/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 227ms/step - loss: 0.6927 - pr_auc: 0.0915 - precision: 0.0882 - recall: 0.8793 - roc_auc: 0.5449 - val_loss: 0.6989 - val_pr_auc: 0.0529 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5082 - val_combined: 0.3370
Epoch 33/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 214ms/step - loss: 0.6933 - pr_auc: 0.0746 - precision: 0.0812 - recall: 0.7931 - roc_auc: 0.4826 - val_loss: 0.6987 - val_pr_auc: 0.0535 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5137 - val_combined: 0.3374
Epoch 34/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 216ms/step - loss: 0.6929 - pr_auc: 0.0850 - precision: 0.0824 - recall: 0.8017 - roc_auc: 0.5250 - val_loss: 0.6992 - val_pr_auc: 0.0526 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5055 - val_combined: 0.3368
Epoch 35/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6929 - pr_auc: 0.0821 - precision: 0.0788 - recall: 0.7328 - roc_auc: 0.5198 - val_loss: 0.6997 - val_pr_auc: 0.0526 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5055 - val_combined: 0.3368
Epoch 36/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 224ms/step - loss: 0.6930 - pr_auc: 0.0887 - precision: 0.0793 - recall: 0.8793 - roc_auc: 0.5261 - val_loss: 0.7001 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 37/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 221ms/step - loss: 0.6931 - pr_auc: 0.0752 - precision: 0.0835 - recall: 0.9052 - roc_auc: 0.4895 - val_loss: 0.7003 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 38/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6930 - pr_auc: 0.0765 - precision: 0.0842 - recall: 0.8362 - roc_auc: 0.4892 - val_loss: 0.7000 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 39/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 227ms/step - loss: 0.6927 - pr_auc: 0.0804 - precision: 0.0877 - recall: 0.7586 - roc_auc: 0.5219 - val_loss: 0.7004 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 40/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 227ms/step - loss: 0.6930 - pr_auc: 0.0810 - precision: 0.0734 - recall: 0.6466 - roc_auc: 0.5225 - val_loss: 0.7006 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 41/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6930 - pr_auc: 0.0772 - precision: 0.0851 - recall: 0.8448 - roc_auc: 0.5091 - val_loss: 0.7008 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 42/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 21s 224ms/step - loss: 0.6927 - pr_auc: 0.0862 - precision: 0.0776 - recall: 0.6810 - roc_auc: 0.5539 - val_loss: 0.7010 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 43/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6928 - pr_auc: 0.0855 - precision: 0.0861 - recall: 0.8707 - roc_auc: 0.5256 - val_loss: 0.7018 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 44/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6926 - pr_auc: 0.0883 - precision: 0.0873 - recall: 0.8879 - roc_auc: 0.5277 - val_loss: 0.7029 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 45/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.6925 - pr_auc: 0.0883 - precision: 0.0823 - recall: 0.7672 - roc_auc: 0.5411 - val_loss: 0.7041 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 46/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 223ms/step - loss: 0.6933 - pr_auc: 0.0800 - precision: 0.0771 - recall: 0.7414 - roc_auc: 0.5146 - val_loss: 0.7037 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 47/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6924 - pr_auc: 0.0859 - precision: 0.0837 - recall: 0.7328 - roc_auc: 0.5590 - val_loss: 0.7040 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 48/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 224ms/step - loss: 0.6927 - pr_auc: 0.0865 - precision: 0.0830 - recall: 0.7672 - roc_auc: 0.5346 - val_loss: 0.7046 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 49/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6922 - pr_auc: 0.0954 - precision: 0.0814 - recall: 0.7500 - roc_auc: 0.5575 - val_loss: 0.7060 - val_pr_auc: 0.0352 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.3242 - val_combined: 0.3246
Epoch 50/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 222ms/step - loss: 0.6935 - pr_auc: 0.0768 - precision: 0.0771 - recall: 0.7241 - roc_auc: 0.4962 - val_loss: 0.7058 - val_pr_auc: 0.0478 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.4835 - val_combined: 0.3334
Epoch 51/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 227ms/step - loss: 0.6919 - pr_auc: 0.0957 - precision: 0.0880 - recall: 0.8017 - roc_auc: 0.5688 - val_loss: 0.7066 - val_pr_auc: 0.0332 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.2720 - val_combined: 0.3232
Epoch 52/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 224ms/step - loss: 0.6927 - pr_auc: 0.0794 - precision: 0.0818 - recall: 0.7155 - roc_auc: 0.5166 - val_loss: 0.7069 - val_pr_auc: 0.0329 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.2637 - val_combined: 0.3230
Epoch 53/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 205ms/step - loss: 0.6927 - pr_auc: 0.0810 - precision: 0.0808 - recall: 0.7241 - roc_auc: 0.5214 - val_loss: 0.7075 - val_pr_auc: 0.0293 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.1401 - val_combined: 0.3205
Epoch 54/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6916 - pr_auc: 0.0926 - precision: 0.0872 - recall: 0.7931 - roc_auc: 0.5599 - val_loss: 0.7093 - val_pr_auc: 0.0538 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5165 - val_combined: 0.3376
Epoch 55/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6924 - pr_auc: 0.0858 - precision: 0.0802 - recall: 0.7414 - roc_auc: 0.5407 - val_loss: 0.7106 - val_pr_auc: 0.0526 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5055 - val_combined: 0.3368
Epoch 56/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6922 - pr_auc: 0.0818 - precision: 0.0878 - recall: 0.8103 - roc_auc: 0.5397 - val_loss: 0.7108 - val_pr_auc: 0.0529 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5082 - val_combined: 0.3370
Epoch 57/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6931 - pr_auc: 0.0779 - precision: 0.0796 - recall: 0.6983 - roc_auc: 0.4944 - val_loss: 0.7100 - val_pr_auc: 0.0532 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5110 - val_combined: 0.3372
Epoch 58/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6929 - pr_auc: 0.0779 - precision: 0.0762 - recall: 0.6810 - roc_auc: 0.5128 - val_loss: 0.7092 - val_pr_auc: 0.0535 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5137 - val_combined: 0.3374
Epoch 59/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 224ms/step - loss: 0.6923 - pr_auc: 0.0858 - precision: 0.0822 - recall: 0.7500 - roc_auc: 0.5348 - val_loss: 0.7100 - val_pr_auc: 0.0529 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5082 - val_combined: 0.3370
Epoch 60/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6929 - pr_auc: 0.0794 - precision: 0.0804 - recall: 0.7414 - roc_auc: 0.5169 - val_loss: 0.7100 - val_pr_auc: 0.0529 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5082 - val_combined: 0.3370
Epoch 61/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 214ms/step - loss: 0.6920 - pr_auc: 0.0835 - precision: 0.0825 - recall: 0.7241 - roc_auc: 0.5363 - val_loss: 0.7106 - val_pr_auc: 0.0526 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5055 - val_combined: 0.3368
Epoch 62/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 214ms/step - loss: 0.6925 - pr_auc: 0.0821 - precision: 0.0823 - recall: 0.7500 - roc_auc: 0.5239 - val_loss: 0.7111 - val_pr_auc: 0.0524 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5027 - val_combined: 0.3366
Epoch 63/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6926 - pr_auc: 0.0798 - precision: 0.0825 - recall: 0.7414 - roc_auc: 0.5097 - val_loss: 0.7111 - val_pr_auc: 0.0524 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5027 - val_combined: 0.3366
Epoch 64/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 231ms/step - loss: 0.6921 - pr_auc: 0.0823 - precision: 0.0803 - recall: 0.7241 - roc_auc: 0.5280 - val_loss: 0.7119 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 65/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6916 - pr_auc: 0.1095 - precision: 0.0807 - recall: 0.7155 - roc_auc: 0.5596 - val_loss: 0.7134 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 66/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6921 - pr_auc: 0.0822 - precision: 0.0877 - recall: 0.7931 - roc_auc: 0.5347 - val_loss: 0.7139 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 67/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6915 - pr_auc: 0.0932 - precision: 0.0800 - recall: 0.7414 - roc_auc: 0.5456 - val_loss: 0.7151 - val_pr_auc: 0.0349 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.3159 - val_combined: 0.3244
Epoch 68/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 228ms/step - loss: 0.6918 - pr_auc: 0.0847 - precision: 0.0802 - recall: 0.7241 - roc_auc: 0.5328 - val_loss: 0.7161 - val_pr_auc: 0.0330 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.2665 - val_combined: 0.3231
Epoch 69/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 221ms/step - loss: 0.6931 - pr_auc: 0.0770 - precision: 0.0804 - recall: 0.7328 - roc_auc: 0.5000 - val_loss: 0.7160 - val_pr_auc: 0.0330 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.2665 - val_combined: 0.3231
Epoch 70/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.6918 - pr_auc: 0.0834 - precision: 0.0838 - recall: 0.8017 - roc_auc: 0.5353 - val_loss: 0.7161 - val_pr_auc: 0.0329 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.2637 - val_combined: 0.3230
Epoch 71/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6911 - pr_auc: 0.0863 - precision: 0.0827 - recall: 0.7672 - roc_auc: 0.5518 - val_loss: 0.7174 - val_pr_auc: 0.0289 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.1209 - val_combined: 0.3202
Epoch 72/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 224ms/step - loss: 0.6926 - pr_auc: 0.0765 - precision: 0.0801 - recall: 0.7328 - roc_auc: 0.5064 - val_loss: 0.7176 - val_pr_auc: 0.0281 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.0852 - val_combined: 0.3197
Epoch 73/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 20s 207ms/step - loss: 0.6913 - pr_auc: 0.0912 - precision: 0.0818 - recall: 0.7500 - roc_auc: 0.5481 - val_loss: 0.7179 - val_pr_auc: 0.0295 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.1742 - val_combined: 0.3207
Epoch 74/200

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 22s 245ms/step - loss: 0.6937 - pr_auc: 0.0687 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4349 - val_loss: 0.6899 - val_pr_auc: 0.0532 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5110 - val_combined: 0.0372
Epoch 2/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.6930 - pr_auc: 0.0772 - precision: 0.0323 - recall: 0.0086 - roc_auc: 0.4946 - val_loss: 0.6901 - val_pr_auc: 0.0541 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5192 - val_combined: 0.0378
Epoch 3/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.6932 - pr_auc: 0.0810 - precision: 0.0690 - recall: 0.0345 - roc_auc: 0.5037 - val_loss: 0.6903 - val_pr_auc: 0.0538 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5165 - val_combined: 0.0376
Epoch 4/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6932 - pr_auc: 0.0795 - precision: 0.0980 - recall: 0.0431 - roc_auc: 0.4980 - val_loss: 0.6905 - val_pr_auc: 0.0538 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5165 - val_combined: 0.0376
Epoch 5/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6927 - pr_auc: 0.0840 - precision: 0.0182 - recall: 0.0086 - roc_auc: 0.5311 - val_loss: 0.6901 - val_pr_auc: 0.0559 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5357 - val_combined: 0.0391
Epoch 6/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 189ms/step - loss: 0.6937 - pr_auc: 0.0790 - precision: 0.0351 - recall: 0.0172 - roc_auc: 0.4879 - val_loss: 0.6911 - val_pr_auc: 0.0541 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5192 - val_combined: 0.0378
Epoch 7/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6924 - pr_auc: 0.0808 - precision: 0.0769 - recall: 0.0517 - roc_auc: 0.5175 - val_loss: 0.6909 - val_pr_auc: 0.0546 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5247 - val_combined: 0.0383
Epoch 8/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 213ms/step - loss: 0.6929 - pr_auc: 0.0813 - precision: 0.0455 - recall: 0.0172 - roc_auc: 0.5116 - val_loss: 0.6909 - val_pr_auc: 0.0556 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5330 - val_combined: 0.0389
Epoch 9/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.6926 - pr_auc: 0.0905 - precision: 0.0652 - recall: 0.0259 - roc_auc: 0.5449 - val_loss: 0.6911 - val_pr_auc: 0.0552 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5302 - val_combined: 0.0387
Epoch 10/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 196ms/step - loss: 0.6923 - pr_auc: 0.1021 - precision: 0.0625 - recall: 0.0259 - roc_auc: 0.5479 - val_loss: 0.6907 - val_pr_auc: 0.0571 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5467 - val_combined: 0.0400
Epoch 11/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6907 - pr_auc: 0.0887 - precision: 0.0484 - recall: 0.0259 - roc_auc: 0.5555 - val_loss: 0.6890 - val_pr_auc: 0.0313 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2060 - val_combined: 0.0219
Epoch 12/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 214ms/step - loss: 0.6936 - pr_auc: 0.0838 - precision: 0.1034 - recall: 0.0776 - roc_auc: 0.5209 - val_loss: 0.6895 - val_pr_auc: 0.0303 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.1731 - val_combined: 0.0212
Epoch 13/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 194ms/step - loss: 0.6927 - pr_auc: 0.0925 - precision: 0.0482 - recall: 0.0345 - roc_auc: 0.5474 - val_loss: 0.6901 - val_pr_auc: 0.0372 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3412 - val_combined: 0.0260
Epoch 14/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.6925 - pr_auc: 0.0928 - precision: 0.0980 - recall: 0.0431 - roc_auc: 0.5479 - val_loss: 0.6902 - val_pr_auc: 0.0368 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3346 - val_combined: 0.0257
Epoch 15/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6934 - pr_auc: 0.0877 - precision: 0.0377 - recall: 0.0172 - roc_auc: 0.5271 - val_loss: 0.6905 - val_pr_auc: 0.0357 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3154 - val_combined: 0.0250
Epoch 16/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6922 - pr_auc: 0.0890 - precision: 0.0571 - recall: 0.0345 - roc_auc: 0.5417 - val_loss: 0.6899 - val_pr_auc: 0.0349 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3091 - val_combined: 0.0244
Epoch 17/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 189ms/step - loss: 0.6920 - pr_auc: 0.0920 - precision: 0.0244 - recall: 0.0086 - roc_auc: 0.5529 - val_loss: 0.6892 - val_pr_auc: 0.0313 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.1978 - val_combined: 0.0219
Epoch 18/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 214ms/step - loss: 0.6933 - pr_auc: 0.0863 - precision: 0.1183 - recall: 0.0948 - roc_auc: 0.5231 - val_loss: 0.6899 - val_pr_auc: 0.0381 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3588 - val_combined: 0.0267
Epoch 19/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 222ms/step - loss: 0.6929 - pr_auc: 0.0854 - precision: 0.1087 - recall: 0.1293 - roc_auc: 0.5232 - val_loss: 0.6906 - val_pr_auc: 0.0375 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3478 - val_combined: 0.0262
Epoch 20/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 213ms/step - loss: 0.6928 - pr_auc: 0.0893 - precision: 0.1161 - recall: 0.1552 - roc_auc: 0.5360 - val_loss: 0.6914 - val_pr_auc: 0.0413 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3890 - val_combined: 0.0289
Epoch 21/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 197ms/step - loss: 0.6928 - pr_auc: 0.0863 - precision: 0.0505 - recall: 0.1207 - roc_auc: 0.5276 - val_loss: 0.6916 - val_pr_auc: 0.0568 - val_precision: 0.0339 - val_recall: 0.2000 - val_roc_auc: 0.5440 - val_combined: 0.0998
Epoch 22/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 216ms/step - loss: 0.6921 - pr_auc: 0.0914 - precision: 0.0565 - recall: 0.1207 - roc_auc: 0.5466 - val_loss: 0.6912 - val_pr_auc: 0.0575 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5495 - val_combined: 0.0402
Epoch 23/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 214ms/step - loss: 0.6916 - pr_auc: 0.0939 - precision: 0.0779 - recall: 0.1552 - roc_auc: 0.5586 - val_loss: 0.6909 - val_pr_auc: 0.0575 - val_precision: 0.0714 - val_recall: 0.4000 - val_roc_auc: 0.5495 - val_combined: 0.1602
Epoch 24/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 195ms/step - loss: 0.6930 - pr_auc: 0.0926 - precision: 0.0989 - recall: 0.1552 - roc_auc: 0.5417 - val_loss: 0.6901 - val_pr_auc: 0.0432 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.4165 - val_combined: 0.0303
Epoch 25/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6924 - pr_auc: 0.0899 - precision: 0.0676 - recall: 0.1293 - roc_auc: 0.5405 - val_loss: 0.6900 - val_pr_auc: 0.0400 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3805 - val_combined: 0.0280
Epoch 26/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6913 - pr_auc: 0.0913 - precision: 0.0881 - recall: 0.1983 - roc_auc: 0.5417 - val_loss: 0.6901 - val_pr_auc: 0.0595 - val_precision: 0.0851 - val_recall: 0.4000 - val_roc_auc: 0.5659 - val_combined: 0.1617
Epoch 27/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6916 - pr_auc: 0.0951 - precision: 0.1125 - recall: 0.2328 - roc_auc: 0.5562 - val_loss: 0.6886 - val_pr_auc: 0.0449 - val_precision: 0.1081 - val_recall: 0.4000 - val_roc_auc: 0.4401 - val_combined: 0.1514
Epoch 28/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 191ms/step - loss: 0.6908 - pr_auc: 0.0953 - precision: 0.1243 - recall: 0.1983 - roc_auc: 0.5640 - val_loss: 0.6877 - val_pr_auc: 0.0394 - val_precision: 0.0526 - val_recall: 0.3000 - val_roc_auc: 0.3824 - val_combined: 0.1176
Epoch 29/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6923 - pr_auc: 0.1051 - precision: 0.1174 - recall: 0.2328 - roc_auc: 0.5614 - val_loss: 0.6877 - val_pr_auc: 0.0613 - val_precision: 0.0741 - val_recall: 0.2000 - val_roc_auc: 0.5797 - val_combined: 0.1029
Epoch 30/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 214ms/step - loss: 0.6886 - pr_auc: 0.0991 - precision: 0.1029 - recall: 0.1552 - roc_auc: 0.5907 - val_loss: 0.6863 - val_pr_auc: 0.0471 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.4670 - val_combined: 0.0330
Epoch 31/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 213ms/step - loss: 0.6898 - pr_auc: 0.0978 - precision: 0.1278 - recall: 0.2931 - roc_auc: 0.5722 - val_loss: 0.6879 - val_pr_auc: 0.0613 - val_precision: 0.0513 - val_recall: 0.4000 - val_roc_auc: 0.5797 - val_combined: 0.1629
Epoch 32/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 18s 397ms/step - loss: 0.6883 - pr_auc: 0.1085 - precision: 0.1272 - recall: 0.2500 - roc_auc: 0.6007 - val_loss: 0.6858 - val_pr_auc: 0.0621 - val_precision: 0.0930 - val_recall: 0.4000 - val_roc_auc: 0.5852 - val_combined: 0.1635
Epoch 33/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 15s 330ms/step - loss: 0.6903 - pr_auc: 0.1019 - precision: 0.1157 - recall: 0.2155 - roc_auc: 0.5861 - val_loss: 0.6821 - val_pr_auc: 0.0424 - val_precision: 0.0625 - val_recall: 0.3000 - val_roc_auc: 0.4247 - val_combined: 0.1197
Epoch 34/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6930 - pr_auc: 0.0949 - precision: 0.1156 - recall: 0.2241 - roc_auc: 0.5481 - val_loss: 0.6846 - val_pr_auc: 0.0847 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7033 - val_combined: 0.0593
Epoch 35/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.6923 - pr_auc: 0.0893 - precision: 0.1044 - recall: 0.2241 - roc_auc: 0.5486 - val_loss: 0.6833 - val_pr_auc: 0.0427 - val_precision: 0.0635 - val_recall: 0.4000 - val_roc_auc: 0.4319 - val_combined: 0.1499
Epoch 36/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6903 - pr_auc: 0.0990 - precision: 0.1444 - recall: 0.3534 - roc_auc: 0.5656 - val_loss: 0.6843 - val_pr_auc: 0.0613 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5797 - val_combined: 0.0429
Epoch 37/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6877 - pr_auc: 0.0960 - precision: 0.1124 - recall: 0.2414 - roc_auc: 0.5869 - val_loss: 0.6825 - val_pr_auc: 0.0506 - val_precision: 0.0606 - val_recall: 0.4000 - val_roc_auc: 0.5077 - val_combined: 0.1554
Epoch 38/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6921 - pr_auc: 0.1070 - precision: 0.1166 - recall: 0.3276 - roc_auc: 0.5614 - val_loss: 0.6839 - val_pr_auc: 0.0621 - val_precision: 0.1304 - val_recall: 0.6000 - val_roc_auc: 0.5852 - val_combined: 0.2235
Epoch 39/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 192ms/step - loss: 0.6905 - pr_auc: 0.0971 - precision: 0.0997 - recall: 0.2586 - roc_auc: 0.5612 - val_loss: 0.6835 - val_pr_auc: 0.0847 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7033 - val_combined: 0.0593
Epoch 40/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6895 - pr_auc: 0.0986 - precision: 0.1039 - recall: 0.2500 - roc_auc: 0.5770 - val_loss: 0.6841 - val_pr_auc: 0.0621 - val_precision: 0.1205 - val_recall: 1.0000 - val_roc_auc: 0.5852 - val_combined: 0.3435
Epoch 41/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 224ms/step - loss: 0.6908 - pr_auc: 0.0938 - precision: 0.1317 - recall: 0.3793 - roc_auc: 0.5616 - val_loss: 0.6839 - val_pr_auc: 0.0645 - val_precision: 0.1091 - val_recall: 0.6000 - val_roc_auc: 0.6016 - val_combined: 0.2252
Epoch 42/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6872 - pr_auc: 0.0959 - precision: 0.1152 - recall: 0.3276 - roc_auc: 0.5863 - val_loss: 0.6831 - val_pr_auc: 0.0820 - val_precision: 0.1333 - val_recall: 0.6000 - val_roc_auc: 0.7005 - val_combined: 0.2374
Epoch 43/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 191ms/step - loss: 0.6896 - pr_auc: 0.0988 - precision: 0.1178 - recall: 0.3362 - roc_auc: 0.5765 - val_loss: 0.6818 - val_pr_auc: 0.0445 - val_precision: 0.0482 - val_recall: 0.4000 - val_roc_auc: 0.4665 - val_combined: 0.1511
Epoch 44/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 216ms/step - loss: 0.6874 - pr_auc: 0.0965 - precision: 0.1000 - recall: 0.3448 - roc_auc: 0.5806 - val_loss: 0.6822 - val_pr_auc: 0.0584 - val_precision: 0.1190 - val_recall: 1.0000 - val_roc_auc: 0.5714 - val_combined: 0.3409
Epoch 45/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 216ms/step - loss: 0.6877 - pr_auc: 0.0947 - precision: 0.1176 - recall: 0.3793 - roc_auc: 0.5787 - val_loss: 0.6828 - val_pr_auc: 0.0739 - val_precision: 0.0448 - val_recall: 0.6000 - val_roc_auc: 0.5992 - val_combined: 0.2317
Epoch 46/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.6892 - pr_auc: 0.0973 - precision: 0.0956 - recall: 0.3707 - roc_auc: 0.5659 - val_loss: 0.6844 - val_pr_auc: 0.0490 - val_precision: 0.0909 - val_recall: 1.0000 - val_roc_auc: 0.5192 - val_combined: 0.3343
Epoch 47/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 196ms/step - loss: 0.6884 - pr_auc: 0.0949 - precision: 0.1155 - recall: 0.4310 - roc_auc: 0.5710 - val_loss: 0.6871 - val_pr_auc: 0.1042 - val_precision: 0.0610 - val_recall: 1.0000 - val_roc_auc: 0.7637 - val_combined: 0.3729
Epoch 48/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6873 - pr_auc: 0.0988 - precision: 0.1183 - recall: 0.4914 - roc_auc: 0.5842 - val_loss: 0.6864 - val_pr_auc: 0.0800 - val_precision: 0.0617 - val_recall: 1.0000 - val_roc_auc: 0.6841 - val_combined: 0.3560
Epoch 49/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 235ms/step - loss: 0.6861 - pr_auc: 0.1006 - precision: 0.1066 - recall: 0.4569 - roc_auc: 0.5891 - val_loss: 0.6873 - val_pr_auc: 0.0962 - val_precision: 0.0602 - val_recall: 1.0000 - val_roc_auc: 0.7418 - val_combined: 0.3673
Epoch 50/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 204ms/step - loss: 0.6869 - pr_auc: 0.1059 - precision: 0.1045 - recall: 0.4397 - roc_auc: 0.5899 - val_loss: 0.6889 - val_pr_auc: 0.0654 - val_precision: 0.0599 - val_recall: 1.0000 - val_roc_auc: 0.6071 - val_combined: 0.3458
Epoch 51/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6871 - pr_auc: 0.0927 - precision: 0.1107 - recall: 0.5086 - roc_auc: 0.5754 - val_loss: 0.6886 - val_pr_auc: 0.0617 - val_precision: 0.0613 - val_recall: 1.0000 - val_roc_auc: 0.5824 - val_combined: 0.3432
Epoch 52/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6880 - pr_auc: 0.0966 - precision: 0.1064 - recall: 0.5000 - roc_auc: 0.5696 - val_loss: 0.6863 - val_pr_auc: 0.0935 - val_precision: 0.0602 - val_recall: 1.0000 - val_roc_auc: 0.7335 - val_combined: 0.3654
Epoch 53/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6862 - pr_auc: 0.0994 - precision: 0.1136 - recall: 0.5345 - roc_auc: 0.5897 - val_loss: 0.6868 - val_pr_auc: 0.0613 - val_precision: 0.0610 - val_recall: 1.0000 - val_roc_auc: 0.5797 - val_combined: 0.3429
Epoch 54/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 192ms/step - loss: 0.6848 - pr_auc: 0.1076 - precision: 0.1165 - recall: 0.5603 - roc_auc: 0.6023 - val_loss: 0.6933 - val_pr_auc: 0.0820 - val_precision: 0.0602 - val_recall: 1.0000 - val_roc_auc: 0.6923 - val_combined: 0.3574
Epoch 55/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6860 - pr_auc: 0.0903 - precision: 0.1096 - recall: 0.5690 - roc_auc: 0.5735 - val_loss: 0.6941 - val_pr_auc: 0.0617 - val_precision: 0.0602 - val_recall: 1.0000 - val_roc_auc: 0.5824 - val_combined: 0.3432
Epoch 56/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6869 - pr_auc: 0.0825 - precision: 0.0954 - recall: 0.4828 - roc_auc: 0.5496 - val_loss: 0.6924 - val_pr_auc: 0.0885 - val_precision: 0.0602 - val_recall: 1.0000 - val_roc_auc: 0.7170 - val_combined: 0.3619
Epoch 57/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6868 - pr_auc: 0.1140 - precision: 0.1147 - recall: 0.6121 - roc_auc: 0.5941 - val_loss: 0.6919 - val_pr_auc: 0.0870 - val_precision: 0.0610 - val_recall: 1.0000 - val_roc_auc: 0.7115 - val_combined: 0.3609
Epoch 58/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 195ms/step - loss: 0.6879 - pr_auc: 0.0964 - precision: 0.1065 - recall: 0.5345 - roc_auc: 0.5668 - val_loss: 0.6980 - val_pr_auc: 0.0599 - val_precision: 0.0588 - val_recall: 1.0000 - val_roc_auc: 0.5687 - val_combined: 0.3419
Epoch 59/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6892 - pr_auc: 0.0893 - precision: 0.1055 - recall: 0.5776 - roc_auc: 0.5514 - val_loss: 0.7003 - val_pr_auc: 0.0588 - val_precision: 0.0578 - val_recall: 1.0000 - val_roc_auc: 0.5604 - val_combined: 0.3412
Epoch 60/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6833 - pr_auc: 0.0974 - precision: 0.1097 - recall: 0.5948 - roc_auc: 0.5982 - val_loss: 0.6954 - val_pr_auc: 0.0613 - val_precision: 0.0602 - val_recall: 1.0000 - val_roc_auc: 0.5797 - val_combined: 0.3429
Epoch 61/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 216ms/step - loss: 0.6864 - pr_auc: 0.0901 - precision: 0.1085 - recall: 0.5603 - roc_auc: 0.5676 - val_loss: 0.6958 - val_pr_auc: 0.1767 - val_precision: 0.0606 - val_recall: 1.0000 - val_roc_auc: 0.6217 - val_combined: 0.4237
Epoch 62/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6847 - pr_auc: 0.0941 - precision: 0.1109 - recall: 0.5948 - roc_auc: 0.5779 - val_loss: 0.6984 - val_pr_auc: 0.0767 - val_precision: 0.0599 - val_recall: 1.0000 - val_roc_auc: 0.6027 - val_combined: 0.3537
Epoch 63/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 223ms/step - loss: 0.6856 - pr_auc: 0.0914 - precision: 0.1140 - recall: 0.6121 - roc_auc: 0.5737 - val_loss: 0.6986 - val_pr_auc: 0.4167 - val_precision: 0.0599 - val_recall: 1.0000 - val_roc_auc: 0.9615 - val_combined: 0.5917
Epoch 64/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6872 - pr_auc: 0.0980 - precision: 0.1113 - recall: 0.5948 - roc_auc: 0.5755 - val_loss: 0.6992 - val_pr_auc: 0.1852 - val_precision: 0.0599 - val_recall: 1.0000 - val_roc_auc: 0.8791 - val_combined: 0.4296
Epoch 65/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6829 - pr_auc: 0.0973 - precision: 0.1106 - recall: 0.5948 - roc_auc: 0.5948 - val_loss: 0.6991 - val_pr_auc: 0.0714 - val_precision: 0.0606 - val_recall: 1.0000 - val_roc_auc: 0.6429 - val_combined: 0.3500
Epoch 66/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.6889 - pr_auc: 0.0906 - precision: 0.1109 - recall: 0.5862 - roc_auc: 0.5524 - val_loss: 0.7010 - val_pr_auc: 0.0613 - val_precision: 0.0602 - val_recall: 1.0000 - val_roc_auc: 0.5797 - val_combined: 0.3429
Epoch 67/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6820 - pr_auc: 0.0999 - precision: 0.1097 - recall: 0.5862 - roc_auc: 0.5960 - val_loss: 0.7020 - val_pr_auc: 0.0621 - val_precision: 0.0602 - val_recall: 1.0000 - val_roc_auc: 0.5852 - val_combined: 0.3435
Epoch 68/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6828 - pr_auc: 0.1082 - precision: 0.1079 - recall: 0.5776 - roc_auc: 0.5968 - val_loss: 0.7000 - val_pr_auc: 0.0613 - val_precision: 0.0606 - val_recall: 1.0000 - val_roc_auc: 0.5797 - val_combined: 0.3429
Epoch 69/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.6867 - pr_auc: 0.0935 - precision: 0.1104 - recall: 0.5948 - roc_auc: 0.5664 - val_loss: 0.7073 - val_pr_auc: 0.0560 - val_precision: 0.0595 - val_recall: 1.0000 - val_roc_auc: 0.5451 - val_combined: 0.3392
Epoch 70/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6819 - pr_auc: 0.1080 - precision: 0.1129 - recall: 0.6121 - roc_auc: 0.6021 - val_loss: 0.7081 - val_pr_auc: 0.0637 - val_precision: 0.0602 - val_recall: 1.0000 - val_roc_auc: 0.5962 - val_combined: 0.3446
Epoch 71/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6829 - pr_auc: 0.1091 - precision: 0.1100 - recall: 0.5862 - roc_auc: 0.5980 - val_loss: 0.7139 - val_pr_auc: 0.0735 - val_precision: 0.0581 - val_recall: 1.0000 - val_roc_auc: 0.6538 - val_combined: 0.3515
Epoch 72/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6827 - pr_auc: 0.1017 - precision: 0.1035 - recall: 0.5603 - roc_auc: 0.5845 - val_loss: 0.7173 - val_pr_auc: 0.0595 - val_precision: 0.0578 - val_recall: 1.0000 - val_roc_auc: 0.5659 - val_combined: 0.3417
Epoch 73/200

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 22s 251ms/step - loss: 0.6937 - pr_auc: 0.0690 - precision: 0.0698 - recall: 0.0517 - roc_auc: 0.4501 - val_loss: 0.6869 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 2/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 221ms/step - loss: 0.6934 - pr_auc: 0.0784 - precision: 0.0617 - recall: 0.0431 - roc_auc: 0.4866 - val_loss: 0.6875 - val_pr_auc: 0.0369 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3599 - val_combined: 0.0258
Epoch 3/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6923 - pr_auc: 0.0923 - precision: 0.0870 - recall: 0.0690 - roc_auc: 0.5528 - val_loss: 0.6861 - val_pr_auc: 0.0541 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5192 - val_combined: 0.0378
Epoch 4/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 193ms/step - loss: 0.6934 - pr_auc: 0.0812 - precision: 0.0943 - recall: 0.0862 - roc_auc: 0.5071 - val_loss: 0.6854 - val_pr_auc: 0.0552 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5302 - val_combined: 0.0387
Epoch 5/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 214ms/step - loss: 0.6928 - pr_auc: 0.0997 - precision: 0.1034 - recall: 0.1034 - roc_auc: 0.5470 - val_loss: 0.6854 - val_pr_auc: 0.0556 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5330 - val_combined: 0.0389
Epoch 6/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6935 - pr_auc: 0.0828 - precision: 0.1034 - recall: 0.1034 - roc_auc: 0.5213 - val_loss: 0.6858 - val_pr_auc: 0.0549 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5275 - val_combined: 0.0385
Epoch 7/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 221ms/step - loss: 0.6929 - pr_auc: 0.0802 - precision: 0.0761 - recall: 0.0603 - roc_auc: 0.5176 - val_loss: 0.6861 - val_pr_auc: 0.0402 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.4148 - val_combined: 0.0281
Epoch 8/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 191ms/step - loss: 0.6930 - pr_auc: 0.0763 - precision: 0.0690 - recall: 0.0517 - roc_auc: 0.5012 - val_loss: 0.6869 - val_pr_auc: 0.0368 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3544 - val_combined: 0.0258
Epoch 9/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6929 - pr_auc: 0.0847 - precision: 0.0238 - recall: 0.0086 - roc_auc: 0.5308 - val_loss: 0.6869 - val_pr_auc: 0.0368 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3544 - val_combined: 0.0258
Epoch 10/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6932 - pr_auc: 0.0870 - precision: 0.0784 - recall: 0.0345 - roc_auc: 0.5230 - val_loss: 0.6880 - val_pr_auc: 0.0350 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3132 - val_combined: 0.0245
Epoch 11/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.6927 - pr_auc: 0.0816 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5204 - val_loss: 0.6880 - val_pr_auc: 0.0349 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3104 - val_combined: 0.0244
Epoch 12/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6933 - pr_auc: 0.0809 - precision: 0.1000 - recall: 0.0172 - roc_auc: 0.5080 - val_loss: 0.6885 - val_pr_auc: 0.0328 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2527 - val_combined: 0.0230
Epoch 13/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 221ms/step - loss: 0.6920 - pr_auc: 0.0972 - precision: 0.0455 - recall: 0.0086 - roc_auc: 0.5617 - val_loss: 0.6882 - val_pr_auc: 0.0345 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2995 - val_combined: 0.0242
Epoch 14/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 216ms/step - loss: 0.6929 - pr_auc: 0.0902 - precision: 0.0526 - recall: 0.0086 - roc_auc: 0.5318 - val_loss: 0.6891 - val_pr_auc: 0.0332 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2769 - val_combined: 0.0232
Epoch 15/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 189ms/step - loss: 0.6924 - pr_auc: 0.0915 - precision: 0.0455 - recall: 0.0086 - roc_auc: 0.5388 - val_loss: 0.6890 - val_pr_auc: 0.0335 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2846 - val_combined: 0.0235
Epoch 16/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6925 - pr_auc: 0.0826 - precision: 0.0571 - recall: 0.0172 - roc_auc: 0.5253 - val_loss: 0.6888 - val_pr_auc: 0.0336 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2868 - val_combined: 0.0235
Epoch 17/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6937 - pr_auc: 0.0886 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5294 - val_loss: 0.6895 - val_pr_auc: 0.0369 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3368 - val_combined: 0.0258
Epoch 18/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6913 - pr_auc: 0.0987 - precision: 0.1250 - recall: 0.0086 - roc_auc: 0.5645 - val_loss: 0.6888 - val_pr_auc: 0.0335 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2835 - val_combined: 0.0235
Epoch 19/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 194ms/step - loss: 0.6916 - pr_auc: 0.0889 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5498 - val_loss: 0.6885 - val_pr_auc: 0.0318 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2115 - val_combined: 0.0223
Epoch 20/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6927 - pr_auc: 0.0894 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5382 - val_loss: 0.6887 - val_pr_auc: 0.0337 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2879 - val_combined: 0.0236
Epoch 21/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6918 - pr_auc: 0.0915 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5524 - val_loss: 0.6879 - val_pr_auc: 0.0329 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2445 - val_combined: 0.0230
Epoch 22/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6904 - pr_auc: 0.0937 - precision: 0.0556 - recall: 0.0086 - roc_auc: 0.5578 - val_loss: 0.6879 - val_pr_auc: 0.0324 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2280 - val_combined: 0.0227
Epoch 23/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 195ms/step - loss: 0.6924 - pr_auc: 0.0858 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5336 - val_loss: 0.6880 - val_pr_auc: 0.0369 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3475 - val_combined: 0.0258
Epoch 24/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6904 - pr_auc: 0.0925 - precision: 0.0286 - recall: 0.0086 - roc_auc: 0.5648 - val_loss: 0.6869 - val_pr_auc: 0.0333 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2500 - val_combined: 0.0233
Epoch 25/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 221ms/step - loss: 0.6924 - pr_auc: 0.0862 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5353 - val_loss: 0.6867 - val_pr_auc: 0.0333 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2500 - val_combined: 0.0233
Epoch 26/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.6924 - pr_auc: 0.0833 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5276 - val_loss: 0.6868 - val_pr_auc: 0.0331 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2418 - val_combined: 0.0232
Epoch 27/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.6918 - pr_auc: 0.0926 - precision: 0.0857 - recall: 0.0517 - roc_auc: 0.5537 - val_loss: 0.6863 - val_pr_auc: 0.0339 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2637 - val_combined: 0.0237
Epoch 28/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6946 - pr_auc: 0.0870 - precision: 0.0400 - recall: 0.0259 - roc_auc: 0.5251 - val_loss: 0.6864 - val_pr_auc: 0.0346 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2857 - val_combined: 0.0242
Epoch 29/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6939 - pr_auc: 0.0845 - precision: 0.0317 - recall: 0.0345 - roc_auc: 0.5191 - val_loss: 0.6873 - val_pr_auc: 0.0355 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3247 - val_combined: 0.0248
Epoch 30/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 197ms/step - loss: 0.6918 - pr_auc: 0.0872 - precision: 0.0642 - recall: 0.0603 - roc_auc: 0.5390 - val_loss: 0.6870 - val_pr_auc: 0.0383 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3728 - val_combined: 0.0268
Epoch 31/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6897 - pr_auc: 0.0958 - precision: 0.0880 - recall: 0.0948 - roc_auc: 0.5726 - val_loss: 0.6855 - val_pr_auc: 0.0342 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2692 - val_combined: 0.0240
Epoch 32/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6912 - pr_auc: 0.0855 - precision: 0.0990 - recall: 0.0862 - roc_auc: 0.5400 - val_loss: 0.6843 - val_pr_auc: 0.0343 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2772 - val_combined: 0.0240
Epoch 33/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6917 - pr_auc: 0.0811 - precision: 0.0472 - recall: 0.0517 - roc_auc: 0.5252 - val_loss: 0.6852 - val_pr_auc: 0.0606 - val_precision: 0.0667 - val_recall: 0.3000 - val_roc_auc: 0.5728 - val_combined: 0.1324
Epoch 34/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.6878 - pr_auc: 0.1029 - precision: 0.1316 - recall: 0.0862 - roc_auc: 0.5995 - val_loss: 0.6827 - val_pr_auc: 0.0730 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6330 - val_combined: 0.0511
Epoch 35/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 231ms/step - loss: 0.6917 - pr_auc: 0.1080 - precision: 0.0886 - recall: 0.0603 - roc_auc: 0.5698 - val_loss: 0.6802 - val_pr_auc: 0.1111 - val_precision: 0.0588 - val_recall: 0.1000 - val_roc_auc: 0.7802 - val_combined: 0.1078
Epoch 36/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6869 - pr_auc: 0.1057 - precision: 0.1290 - recall: 0.0690 - roc_auc: 0.6013 - val_loss: 0.6803 - val_pr_auc: 0.0762 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6462 - val_combined: 0.0534
Epoch 37/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6893 - pr_auc: 0.1072 - precision: 0.1486 - recall: 0.0948 - roc_auc: 0.5904 - val_loss: 0.6797 - val_pr_auc: 0.1235 - val_precision: 0.1111 - val_recall: 0.2000 - val_roc_auc: 0.8049 - val_combined: 0.1464
Epoch 38/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 192ms/step - loss: 0.6898 - pr_auc: 0.1179 - precision: 0.0928 - recall: 0.0776 - roc_auc: 0.5995 - val_loss: 0.6769 - val_pr_auc: 0.1351 - val_precision: 0.1250 - val_recall: 0.2000 - val_roc_auc: 0.8242 - val_combined: 0.1546
Epoch 39/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6900 - pr_auc: 0.1031 - precision: 0.1053 - recall: 0.0862 - roc_auc: 0.5788 - val_loss: 0.6732 - val_pr_auc: 0.0759 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7033 - val_combined: 0.0532
Epoch 40/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6899 - pr_auc: 0.1045 - precision: 0.1176 - recall: 0.0690 - roc_auc: 0.5808 - val_loss: 0.6790 - val_pr_auc: 0.0781 - val_precision: 0.0769 - val_recall: 0.4000 - val_roc_auc: 0.6538 - val_combined: 0.1747
Epoch 41/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 214ms/step - loss: 0.6891 - pr_auc: 0.0994 - precision: 0.1358 - recall: 0.1897 - roc_auc: 0.5726 - val_loss: 0.6783 - val_pr_auc: 0.1587 - val_precision: 0.1290 - val_recall: 0.4000 - val_roc_auc: 0.8544 - val_combined: 0.2311
Epoch 42/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6879 - pr_auc: 0.1192 - precision: 0.1333 - recall: 0.1034 - roc_auc: 0.6123 - val_loss: 0.6770 - val_pr_auc: 0.0833 - val_precision: 0.0784 - val_recall: 0.4000 - val_roc_auc: 0.6802 - val_combined: 0.1783
Epoch 43/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6893 - pr_auc: 0.0945 - precision: 0.1242 - recall: 0.1724 - roc_auc: 0.5714 - val_loss: 0.6767 - val_pr_auc: 0.1111 - val_precision: 0.1875 - val_recall: 0.6000 - val_roc_auc: 0.7802 - val_combined: 0.2578
Epoch 44/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6853 - pr_auc: 0.1069 - precision: 0.1316 - recall: 0.1724 - roc_auc: 0.6071 - val_loss: 0.6759 - val_pr_auc: 0.1089 - val_precision: 0.1429 - val_recall: 0.4000 - val_roc_auc: 0.7615 - val_combined: 0.1962
Epoch 45/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6884 - pr_auc: 0.1129 - precision: 0.1429 - recall: 0.1207 - roc_auc: 0.6006 - val_loss: 0.6773 - val_pr_auc: 0.0782 - val_precision: 0.0984 - val_recall: 0.6000 - val_roc_auc: 0.6755 - val_combined: 0.2347
Epoch 46/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.6849 - pr_auc: 0.1152 - precision: 0.1257 - recall: 0.1897 - roc_auc: 0.6152 - val_loss: 0.6737 - val_pr_auc: 0.1256 - val_precision: 0.1364 - val_recall: 0.3000 - val_roc_auc: 0.7901 - val_combined: 0.1779
Epoch 47/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6903 - pr_auc: 0.1055 - precision: 0.1364 - recall: 0.1293 - roc_auc: 0.5806 - val_loss: 0.6778 - val_pr_auc: 0.1280 - val_precision: 0.0690 - val_recall: 0.4000 - val_roc_auc: 0.6146 - val_combined: 0.2096
Epoch 48/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6908 - pr_auc: 0.0961 - precision: 0.1232 - recall: 0.2931 - roc_auc: 0.5595 - val_loss: 0.6792 - val_pr_auc: 0.2921 - val_precision: 0.1613 - val_recall: 1.0000 - val_roc_auc: 0.8791 - val_combined: 0.5044
Epoch 49/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 192ms/step - loss: 0.6902 - pr_auc: 0.1047 - precision: 0.1121 - recall: 0.2069 - roc_auc: 0.5739 - val_loss: 0.6756 - val_pr_auc: 0.1344 - val_precision: 0.1463 - val_recall: 0.6000 - val_roc_auc: 0.8041 - val_combined: 0.2740
Epoch 50/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6872 - pr_auc: 0.1044 - precision: 0.1398 - recall: 0.2241 - roc_auc: 0.5952 - val_loss: 0.6788 - val_pr_auc: 0.1650 - val_precision: 0.1587 - val_recall: 1.0000 - val_roc_auc: 0.8341 - val_combined: 0.4155
Epoch 51/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6872 - pr_auc: 0.1069 - precision: 0.1342 - recall: 0.2672 - roc_auc: 0.5980 - val_loss: 0.6803 - val_pr_auc: 0.1562 - val_precision: 0.1184 - val_recall: 0.9000 - val_roc_auc: 0.8253 - val_combined: 0.3793
Epoch 52/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 216ms/step - loss: 0.6885 - pr_auc: 0.1005 - precision: 0.1301 - recall: 0.3276 - roc_auc: 0.5756 - val_loss: 0.6794 - val_pr_auc: 0.1414 - val_precision: 0.1724 - val_recall: 1.0000 - val_roc_auc: 0.8091 - val_combined: 0.3990
Epoch 53/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 195ms/step - loss: 0.6857 - pr_auc: 0.1214 - precision: 0.1554 - recall: 0.3362 - roc_auc: 0.6200 - val_loss: 0.6807 - val_pr_auc: 0.1517 - val_precision: 0.1099 - val_recall: 1.0000 - val_roc_auc: 0.8313 - val_combined: 0.4062
Epoch 54/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6850 - pr_auc: 0.1118 - precision: 0.1216 - recall: 0.3103 - roc_auc: 0.6068 - val_loss: 0.6814 - val_pr_auc: 0.1333 - val_precision: 0.1111 - val_recall: 1.0000 - val_roc_auc: 0.8005 - val_combined: 0.3933
Epoch 55/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6844 - pr_auc: 0.1065 - precision: 0.1297 - recall: 0.3276 - roc_auc: 0.6137 - val_loss: 0.6821 - val_pr_auc: 0.1299 - val_precision: 0.1020 - val_recall: 1.0000 - val_roc_auc: 0.8159 - val_combined: 0.3909
Epoch 56/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6868 - pr_auc: 0.1017 - precision: 0.1176 - recall: 0.3276 - roc_auc: 0.5903 - val_loss: 0.6814 - val_pr_auc: 0.1226 - val_precision: 0.1087 - val_recall: 1.0000 - val_roc_auc: 0.7841 - val_combined: 0.3858
Epoch 57/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6857 - pr_auc: 0.1072 - precision: 0.1083 - recall: 0.2931 - roc_auc: 0.6012 - val_loss: 0.6842 - val_pr_auc: 0.1955 - val_precision: 0.0971 - val_recall: 1.0000 - val_roc_auc: 0.8396 - val_combined: 0.4369
Epoch 58/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6874 - pr_auc: 0.1092 - precision: 0.1285 - recall: 0.4310 - roc_auc: 0.5910 - val_loss: 0.6849 - val_pr_auc: 0.1371 - val_precision: 0.0952 - val_recall: 1.0000 - val_roc_auc: 0.8016 - val_combined: 0.3960
Epoch 59/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6883 - pr_auc: 0.1181 - precision: 0.1240 - recall: 0.3966 - roc_auc: 0.5906 - val_loss: 0.6862 - val_pr_auc: 0.1921 - val_precision: 0.0617 - val_recall: 1.0000 - val_roc_auc: 0.8313 - val_combined: 0.4345
Epoch 60/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 214ms/step - loss: 0.6850 - pr_auc: 0.0984 - precision: 0.0937 - recall: 0.3448 - roc_auc: 0.5898 - val_loss: 0.6820 - val_pr_auc: 0.1724 - val_precision: 0.1000 - val_recall: 1.0000 - val_roc_auc: 0.8681 - val_combined: 0.4207
Epoch 61/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6874 - pr_auc: 0.1194 - precision: 0.0938 - recall: 0.2845 - roc_auc: 0.5787 - val_loss: 0.6866 - val_pr_auc: 0.2762 - val_precision: 0.0617 - val_recall: 1.0000 - val_roc_auc: 0.9115 - val_combined: 0.4933
Epoch 62/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6852 - pr_auc: 0.0943 - precision: 0.1011 - recall: 0.3879 - roc_auc: 0.5843 - val_loss: 0.6857 - val_pr_auc: 0.1519 - val_precision: 0.0606 - val_recall: 1.0000 - val_roc_auc: 0.8099 - val_combined: 0.4063
Epoch 63/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6840 - pr_auc: 0.1068 - precision: 0.1188 - recall: 0.4138 - roc_auc: 0.6098 - val_loss: 0.6900 - val_pr_auc: 0.1351 - val_precision: 0.0613 - val_recall: 1.0000 - val_roc_auc: 0.8242 - val_combined: 0.3946
Epoch 64/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6835 - pr_auc: 0.1093 - precision: 0.1095 - recall: 0.4483 - roc_auc: 0.5997 - val_loss: 0.6882 - val_pr_auc: 0.1613 - val_precision: 0.0610 - val_recall: 1.0000 - val_roc_auc: 0.8137 - val_combined: 0.4129
Epoch 65/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 212ms/step - loss: 0.6854 - pr_auc: 0.1093 - precision: 0.1253 - recall: 0.4741 - roc_auc: 0.6016 - val_loss: 0.6897 - val_pr_auc: 0.2658 - val_precision: 0.0610 - val_recall: 1.0000 - val_roc_auc: 0.8302 - val_combined: 0.4860
Epoch 66/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6835 - pr_auc: 0.1090 - precision: 0.1104 - recall: 0.4569 - roc_auc: 0.6075 - val_loss: 0.6923 - val_pr_auc: 0.1291 - val_precision: 0.0610 - val_recall: 1.0000 - val_roc_auc: 0.7797 - val_combined: 0.3903
Epoch 67/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 224ms/step - loss: 0.6828 - pr_auc: 0.1030 - precision: 0.1059 - recall: 0.4483 - roc_auc: 0.6019 - val_loss: 0.6894 - val_pr_auc: 0.1818 - val_precision: 0.0602 - val_recall: 1.0000 - val_roc_auc: 0.8764 - val_combined: 0.4273
Epoch 68/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6867 - pr_auc: 0.1131 - precision: 0.1312 - recall: 0.5431 - roc_auc: 0.5968 - val_loss: 0.6930 - val_pr_auc: 0.3381 - val_precision: 0.0610 - val_recall: 1.0000 - val_roc_auc: 0.9115 - val_combined: 0.5366
Epoch 69/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6852 - pr_auc: 0.1116 - precision: 0.1072 - recall: 0.4483 - roc_auc: 0.5921 - val_loss: 0.6934 - val_pr_auc: 0.1928 - val_precision: 0.0595 - val_recall: 1.0000 - val_roc_auc: 0.8330 - val_combined: 0.4349
Epoch 70/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6824 - pr_auc: 0.1122 - precision: 0.1135 - recall: 0.5000 - roc_auc: 0.6161 - val_loss: 0.6970 - val_pr_auc: 0.2326 - val_precision: 0.0599 - val_recall: 1.0000 - val_roc_auc: 0.9093 - val_combined: 0.4628
Epoch 71/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6854 - pr_auc: 0.1100 - precision: 0.1085 - recall: 0.4741 - roc_auc: 0.5923 - val_loss: 0.6952 - val_pr_auc: 0.1639 - val_precision: 0.0602 - val_recall: 1.0000 - val_roc_auc: 0.8258 - val_combined: 0.4147
Epoch 72/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 193ms/step - loss: 0.6793 - pr_auc: 0.1242 - precision: 0.1264 - recall: 0.5776 - roc_auc: 0.6391 - val_loss: 0.6963 - val_pr_auc: 0.1650 - val_precision: 0.0613 - val_recall: 1.0000 - val_roc_auc: 0.8253 - val_combined: 0.4155
Epoch 73/200

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 21s 244ms/step - loss: 0.6934 - pr_auc: 0.0800 - precision: 0.0408 - recall: 0.0690 - roc_auc: 0.5046 - val_loss: 0.6917 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 2/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 213ms/step - loss: 0.6931 - pr_auc: 0.0799 - precision: 0.0345 - recall: 0.0172 - roc_auc: 0.5021 - val_loss: 0.6917 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 3/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 194ms/step - loss: 0.6933 - pr_auc: 0.0798 - precision: 0.0444 - recall: 0.0862 - roc_auc: 0.5180 - val_loss: 0.6911 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 4/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6932 - pr_auc: 0.0835 - precision: 0.0270 - recall: 0.0086 - roc_auc: 0.5267 - val_loss: 0.6909 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 5/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6929 - pr_auc: 0.0800 - precision: 0.0541 - recall: 0.0172 - roc_auc: 0.5107 - val_loss: 0.6908 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 6/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 192ms/step - loss: 0.6930 - pr_auc: 0.0837 - precision: 0.0196 - recall: 0.0086 - roc_auc: 0.5178 - val_loss: 0.6909 - val_pr_auc: 0.0524 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5027 - val_combined: 0.0366
Epoch 7/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 210ms/step - loss: 0.6930 - pr_auc: 0.0816 - precision: 0.0930 - recall: 0.0345 - roc_auc: 0.5131 - val_loss: 0.6911 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 8/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6927 - pr_auc: 0.0811 - precision: 0.0476 - recall: 0.0086 - roc_auc: 0.5150 - val_loss: 0.6908 - val_pr_auc: 0.0532 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5110 - val_combined: 0.0372
Epoch 9/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6929 - pr_auc: 0.0865 - precision: 0.0725 - recall: 0.0431 - roc_auc: 0.5394 - val_loss: 0.6903 - val_pr_auc: 0.0543 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5220 - val_combined: 0.0380
Epoch 10/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 191ms/step - loss: 0.6932 - pr_auc: 0.0817 - precision: 0.0909 - recall: 0.0259 - roc_auc: 0.5092 - val_loss: 0.6902 - val_pr_auc: 0.0541 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5192 - val_combined: 0.0378
Epoch 11/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6931 - pr_auc: 0.0830 - precision: 0.0400 - recall: 0.0086 - roc_auc: 0.5193 - val_loss: 0.6904 - val_pr_auc: 0.0541 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5192 - val_combined: 0.0378
Epoch 12/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 224ms/step - loss: 0.6932 - pr_auc: 0.0812 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5095 - val_loss: 0.6909 - val_pr_auc: 0.0532 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5110 - val_combined: 0.0372
Epoch 13/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 205ms/step - loss: 0.6932 - pr_auc: 0.0814 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5107 - val_loss: 0.6912 - val_pr_auc: 0.0524 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5027 - val_combined: 0.0366
Epoch 14/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6919 - pr_auc: 0.0947 - precision: 0.1026 - recall: 0.0345 - roc_auc: 0.5748 - val_loss: 0.6903 - val_pr_auc: 0.0556 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5330 - val_combined: 0.0389
Epoch 15/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6933 - pr_auc: 0.0822 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5181 - val_loss: 0.6907 - val_pr_auc: 0.0546 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5247 - val_combined: 0.0383
Epoch 16/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6931 - pr_auc: 0.0803 - precision: 0.0877 - recall: 0.0431 - roc_auc: 0.5166 - val_loss: 0.6912 - val_pr_auc: 0.0541 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5192 - val_combined: 0.0378
Epoch 17/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6931 - pr_auc: 0.0780 - precision: 0.0247 - recall: 0.0172 - roc_auc: 0.4961 - val_loss: 0.6911 - val_pr_auc: 0.0535 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5137 - val_combined: 0.0374
Epoch 18/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6932 - pr_auc: 0.0793 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4999 - val_loss: 0.6914 - val_pr_auc: 0.0535 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5137 - val_combined: 0.0374
Epoch 19/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6913 - pr_auc: 0.0876 - precision: 0.1562 - recall: 0.0431 - roc_auc: 0.5557 - val_loss: 0.6911 - val_pr_auc: 0.0546 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5247 - val_combined: 0.0383
Epoch 20/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6931 - pr_auc: 0.0807 - precision: 0.0678 - recall: 0.0345 - roc_auc: 0.5117 - val_loss: 0.6910 - val_pr_auc: 0.0552 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5302 - val_combined: 0.0387
Epoch 21/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 190ms/step - loss: 0.6919 - pr_auc: 0.0815 - precision: 0.0513 - recall: 0.0345 - roc_auc: 0.5330 - val_loss: 0.6912 - val_pr_auc: 0.0556 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5330 - val_combined: 0.0389
Epoch 22/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 216ms/step - loss: 0.6934 - pr_auc: 0.0808 - precision: 0.0879 - recall: 0.0690 - roc_auc: 0.5144 - val_loss: 0.6916 - val_pr_auc: 0.0546 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5247 - val_combined: 0.0383
Epoch 23/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6919 - pr_auc: 0.0937 - precision: 0.0968 - recall: 0.1293 - roc_auc: 0.5598 - val_loss: 0.6921 - val_pr_auc: 0.0552 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5302 - val_combined: 0.0387
Epoch 24/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 210ms/step - loss: 0.6928 - pr_auc: 0.0879 - precision: 0.0816 - recall: 0.1724 - roc_auc: 0.5374 - val_loss: 0.6923 - val_pr_auc: 0.0552 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5302 - val_combined: 0.0387
Epoch 25/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.6930 - pr_auc: 0.0909 - precision: 0.0884 - recall: 0.2241 - roc_auc: 0.5317 - val_loss: 0.6935 - val_pr_auc: 0.0549 - val_precision: 0.0077 - val_recall: 0.1000 - val_roc_auc: 0.5275 - val_combined: 0.0685
Epoch 26/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 223ms/step - loss: 0.6924 - pr_auc: 0.0903 - precision: 0.0726 - recall: 0.1983 - roc_auc: 0.5486 - val_loss: 0.6936 - val_pr_auc: 0.0549 - val_precision: 0.0078 - val_recall: 0.1000 - val_roc_auc: 0.5275 - val_combined: 0.0685
Epoch 27/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6916 - pr_auc: 0.0810 - precision: 0.0735 - recall: 0.2155 - roc_auc: 0.5340 - val_loss: 0.6927 - val_pr_auc: 0.0369 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3283 - val_combined: 0.0259
Epoch 28/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.6926 - pr_auc: 0.0798 - precision: 0.0927 - recall: 0.2414 - roc_auc: 0.5187 - val_loss: 0.6928 - val_pr_auc: 0.0347 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2951 - val_combined: 0.0243
Epoch 29/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.6919 - pr_auc: 0.0863 - precision: 0.0829 - recall: 0.2586 - roc_auc: 0.5444 - val_loss: 0.6928 - val_pr_auc: 0.0356 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.3132 - val_combined: 0.0249
Epoch 30/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6906 - pr_auc: 0.0980 - precision: 0.1014 - recall: 0.3190 - roc_auc: 0.5584 - val_loss: 0.6948 - val_pr_auc: 0.0361 - val_precision: 0.0292 - val_recall: 0.4000 - val_roc_auc: 0.3324 - val_combined: 0.1453
Epoch 31/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6923 - pr_auc: 0.0769 - precision: 0.0748 - recall: 0.3017 - roc_auc: 0.5151 - val_loss: 0.6953 - val_pr_auc: 0.0351 - val_precision: 0.0278 - val_recall: 0.4000 - val_roc_auc: 0.3077 - val_combined: 0.1446
Epoch 32/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 189ms/step - loss: 0.6903 - pr_auc: 0.0900 - precision: 0.0806 - recall: 0.3448 - roc_auc: 0.5587 - val_loss: 0.6927 - val_pr_auc: 0.0331 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2698 - val_combined: 0.0232
Epoch 33/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6944 - pr_auc: 0.0853 - precision: 0.0855 - recall: 0.3103 - roc_auc: 0.5123 - val_loss: 0.6962 - val_pr_auc: 0.0328 - val_precision: 0.0276 - val_recall: 0.4000 - val_roc_auc: 0.2390 - val_combined: 0.1430
Epoch 34/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6900 - pr_auc: 0.0940 - precision: 0.0958 - recall: 0.4483 - roc_auc: 0.5675 - val_loss: 0.7002 - val_pr_auc: 0.0352 - val_precision: 0.0581 - val_recall: 1.0000 - val_roc_auc: 0.3310 - val_combined: 0.3247
Epoch 35/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6897 - pr_auc: 0.0933 - precision: 0.0943 - recall: 0.4310 - roc_auc: 0.5651 - val_loss: 0.6974 - val_pr_auc: 0.0404 - val_precision: 0.0405 - val_recall: 0.6000 - val_roc_auc: 0.3967 - val_combined: 0.2083
Epoch 36/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6945 - pr_auc: 0.0804 - precision: 0.0907 - recall: 0.4224 - roc_auc: 0.5072 - val_loss: 0.6996 - val_pr_auc: 0.0376 - val_precision: 0.0585 - val_recall: 1.0000 - val_roc_auc: 0.3505 - val_combined: 0.3263
Epoch 37/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6929 - pr_auc: 0.0845 - precision: 0.0923 - recall: 0.4569 - roc_auc: 0.5271 - val_loss: 0.7038 - val_pr_auc: 0.0337 - val_precision: 0.0578 - val_recall: 1.0000 - val_roc_auc: 0.2610 - val_combined: 0.3236
Epoch 38/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6928 - pr_auc: 0.0871 - precision: 0.0941 - recall: 0.5086 - roc_auc: 0.5419 - val_loss: 0.7043 - val_pr_auc: 0.0374 - val_precision: 0.0571 - val_recall: 1.0000 - val_roc_auc: 0.3560 - val_combined: 0.3262
Epoch 39/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 194ms/step - loss: 0.6911 - pr_auc: 0.0811 - precision: 0.0911 - recall: 0.4828 - roc_auc: 0.5357 - val_loss: 0.7051 - val_pr_auc: 0.0402 - val_precision: 0.0585 - val_recall: 1.0000 - val_roc_auc: 0.3945 - val_combined: 0.3282
Epoch 40/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6906 - pr_auc: 0.0834 - precision: 0.0985 - recall: 0.5172 - roc_auc: 0.5445 - val_loss: 0.7061 - val_pr_auc: 0.0365 - val_precision: 0.0595 - val_recall: 1.0000 - val_roc_auc: 0.3503 - val_combined: 0.3255
Epoch 41/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6912 - pr_auc: 0.0822 - precision: 0.0941 - recall: 0.4914 - roc_auc: 0.5387 - val_loss: 0.7056 - val_pr_auc: 0.0378 - val_precision: 0.0595 - val_recall: 1.0000 - val_roc_auc: 0.3764 - val_combined: 0.3264
Epoch 42/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 229ms/step - loss: 0.6895 - pr_auc: 0.0890 - precision: 0.1041 - recall: 0.5690 - roc_auc: 0.5602 - val_loss: 0.7076 - val_pr_auc: 0.0405 - val_precision: 0.0588 - val_recall: 1.0000 - val_roc_auc: 0.4148 - val_combined: 0.3283
Epoch 43/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6880 - pr_auc: 0.0862 - precision: 0.1002 - recall: 0.5690 - roc_auc: 0.5593 - val_loss: 0.7075 - val_pr_auc: 0.0493 - val_precision: 0.0599 - val_recall: 1.0000 - val_roc_auc: 0.4890 - val_combined: 0.3345
Epoch 44/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6913 - pr_auc: 0.0833 - precision: 0.0986 - recall: 0.5603 - roc_auc: 0.5397 - val_loss: 0.7070 - val_pr_auc: 0.0487 - val_precision: 0.0595 - val_recall: 1.0000 - val_roc_auc: 0.4835 - val_combined: 0.3341
Epoch 45/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 238ms/step - loss: 0.6883 - pr_auc: 0.0873 - precision: 0.1073 - recall: 0.6207 - roc_auc: 0.5643 - val_loss: 0.7081 - val_pr_auc: 0.0613 - val_precision: 0.0599 - val_recall: 1.0000 - val_roc_auc: 0.5797 - val_combined: 0.3429
Epoch 46/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6883 - pr_auc: 0.0876 - precision: 0.1044 - recall: 0.5776 - roc_auc: 0.5658 - val_loss: 0.7105 - val_pr_auc: 0.0606 - val_precision: 0.0592 - val_recall: 1.0000 - val_roc_auc: 0.5742 - val_combined: 0.3424
Epoch 47/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.6882 - pr_auc: 0.0906 - precision: 0.1106 - recall: 0.6466 - roc_auc: 0.5656 - val_loss: 0.7119 - val_pr_auc: 0.0564 - val_precision: 0.0595 - val_recall: 1.0000 - val_roc_auc: 0.5632 - val_combined: 0.3395
Epoch 48/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 231ms/step - loss: 0.6882 - pr_auc: 0.0958 - precision: 0.1036 - recall: 0.5776 - roc_auc: 0.5705 - val_loss: 0.7155 - val_pr_auc: 0.0347 - val_precision: 0.0585 - val_recall: 1.0000 - val_roc_auc: 0.2857 - val_combined: 0.3243
Epoch 49/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 223ms/step - loss: 0.6867 - pr_auc: 0.0953 - precision: 0.1064 - recall: 0.6121 - roc_auc: 0.5724 - val_loss: 0.7164 - val_pr_auc: 0.0606 - val_precision: 0.0592 - val_recall: 1.0000 - val_roc_auc: 0.5742 - val_combined: 0.3424
Epoch 50/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 223ms/step - loss: 0.6869 - pr_auc: 0.0896 - precision: 0.1081 - recall: 0.6207 - roc_auc: 0.5730 - val_loss: 0.7188 - val_pr_auc: 0.0580 - val_precision: 0.0585 - val_recall: 1.0000 - val_roc_auc: 0.5632 - val_combined: 0.3406
Epoch 51/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6853 - pr_auc: 0.0944 - precision: 0.1043 - recall: 0.6121 - roc_auc: 0.5813 - val_loss: 0.7204 - val_pr_auc: 0.0533 - val_precision: 0.0592 - val_recall: 1.0000 - val_roc_auc: 0.5467 - val_combined: 0.3373
Epoch 52/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.6864 - pr_auc: 0.0932 - precision: 0.0997 - recall: 0.5690 - roc_auc: 0.5716 - val_loss: 0.7191 - val_pr_auc: 0.0531 - val_precision: 0.0595 - val_recall: 1.0000 - val_roc_auc: 0.5467 - val_combined: 0.3371
Epoch 53/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 240ms/step - loss: 0.6885 - pr_auc: 0.0989 - precision: 0.1015 - recall: 0.5948 - roc_auc: 0.5495 - val_loss: 0.7259 - val_pr_auc: 0.0475 - val_precision: 0.0556 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3333
Epoch 54/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 223ms/step - loss: 0.6861 - pr_auc: 0.0918 - precision: 0.0984 - recall: 0.6379 - roc_auc: 0.5789 - val_loss: 0.7296 - val_pr_auc: 0.0434 - val_precision: 0.0568 - val_recall: 1.0000 - val_roc_auc: 0.4209 - val_combined: 0.3304
Epoch 55/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 213ms/step - loss: 0.6880 - pr_auc: 0.0981 - precision: 0.1052 - recall: 0.6121 - roc_auc: 0.5533 - val_loss: 0.7266 - val_pr_auc: 0.0599 - val_precision: 0.0592 - val_recall: 1.0000 - val_roc_auc: 0.5687 - val_combined: 0.3419
Epoch 56/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6849 - pr_auc: 0.0933 - precision: 0.1086 - recall: 0.6293 - roc_auc: 0.5786 - val_loss: 0.7320 - val_pr_auc: 0.0333 - val_precision: 0.0578 - val_recall: 1.0000 - val_roc_auc: 0.2445 - val_combined: 0.3233
Epoch 57/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 222ms/step - loss: 0.6853 - pr_auc: 0.1072 - precision: 0.1004 - recall: 0.6121 - roc_auc: 0.5769 - val_loss: 0.7322 - val_pr_auc: 0.0389 - val_precision: 0.0588 - val_recall: 1.0000 - val_roc_auc: 0.3742 - val_combined: 0.3272
Epoch 58/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6824 - pr_auc: 0.1013 - precision: 0.1043 - recall: 0.5862 - roc_auc: 0.5930 - val_loss: 0.7405 - val_pr_auc: 0.0425 - val_precision: 0.0571 - val_recall: 1.0000 - val_roc_auc: 0.4478 - val_combined: 0.3297
Epoch 59/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 222ms/step - loss: 0.6880 - pr_auc: 0.1045 - precision: 0.1015 - recall: 0.6293 - roc_auc: 0.5598 - val_loss: 0.7450 - val_pr_auc: 0.0370 - val_precision: 0.0565 - val_recall: 1.0000 - val_roc_auc: 0.3522 - val_combined: 0.3259
Epoch 60/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.6855 - pr_auc: 0.0894 - precision: 0.1079 - recall: 0.6379 - roc_auc: 0.5644 - val_loss: 0.7406 - val_pr_auc: 0.0440 - val_precision: 0.0595 - val_recall: 1.0000 - val_roc_auc: 0.4637 - val_combined: 0.3308
Epoch 61/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 224ms/step - loss: 0.6850 - pr_auc: 0.0893 - precision: 0.1049 - recall: 0.6034 - roc_auc: 0.5701 - val_loss: 0.7451 - val_pr_auc: 0.0346 - val_precision: 0.0571 - val_recall: 1.0000 - val_roc_auc: 0.3121 - val_combined: 0.3242
Epoch 62/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 232ms/step - loss: 0.6846 - pr_auc: 0.1058 - precision: 0.1051 - recall: 0.6379 - roc_auc: 0.5786 - val_loss: 0.7496 - val_pr_auc: 0.0396 - val_precision: 0.0578 - val_recall: 1.0000 - val_roc_auc: 0.4088 - val_combined: 0.3277
Epoch 63/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6832 - pr_auc: 0.0985 - precision: 0.1134 - recall: 0.6552 - roc_auc: 0.5805 - val_loss: 0.7447 - val_pr_auc: 0.0427 - val_precision: 0.0592 - val_recall: 1.0000 - val_roc_auc: 0.4505 - val_combined: 0.3299
Epoch 64/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6829 - pr_auc: 0.0977 - precision: 0.1083 - recall: 0.6207 - roc_auc: 0.5800 - val_loss: 0.7592 - val_pr_auc: 0.0368 - val_precision: 0.0568 - val_recall: 1.0000 - val_roc_auc: 0.3462 - val_combined: 0.3258
Epoch 65/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 223ms/step - loss: 0.6893 - pr_auc: 0.0959 - precision: 0.1015 - recall: 0.6293 - roc_auc: 0.5429 - val_loss: 0.7601 - val_pr_auc: 0.0417 - val_precision: 0.0578 - val_recall: 1.0000 - val_roc_auc: 0.4396 - val_combined: 0.3292
Epoch 66/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 221ms/step - loss: 0.6819 - pr_auc: 0.1019 - precision: 0.1089 - recall: 0.6207 - roc_auc: 0.5870 - val_loss: 0.7509 - val_pr_auc: 0.0437 - val_precision: 0.0588 - val_recall: 1.0000 - val_roc_auc: 0.4643 - val_combined: 0.3306
Epoch 67/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 205ms/step - loss: 0.6837 - pr_auc: 0.1156 - precision: 0.1073 - recall: 0.6121 - roc_auc: 0.5740 - val_loss: 0.7607 - val_pr_auc: 0.0583 - val_precision: 0.0578 - val_recall: 1.0000 - val_roc_auc: 0.6016 - val_combined: 0.3408
Epoch 68/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6875 - pr_auc: 0.0921 - precision: 0.1076 - recall: 0.6379 - roc_auc: 0.5506 - val_loss: 0.7604 - val_pr_auc: 0.0494 - val_precision: 0.0588 - val_recall: 1.0000 - val_roc_auc: 0.5082 - val_combined: 0.3346
Epoch 69/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 240ms/step - loss: 0.6799 - pr_auc: 0.1245 - precision: 0.1084 - recall: 0.6207 - roc_auc: 0.5911 - val_loss: 0.7476 - val_pr_auc: 0.0437 - val_precision: 0.0585 - val_recall: 1.0000 - val_roc_auc: 0.4643 - val_combined: 0.3306
Epoch 70/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6818 - pr_auc: 0.1181 - precision: 0.1074 - recall: 0.6293 - roc_auc: 0.5881 - val_loss: 0.7552 - val_pr_auc: 0.0398 - val_precision: 0.0578 - val_recall: 1.0000 - val_roc_auc: 0.4066 - val_combined: 0.3279
Epoch 71/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6829 - pr_auc: 0.1125 - precision: 0.1050 - recall: 0.6121 - roc_auc: 0.5699 - val_loss: 0.7760 - val_pr_auc: 0.0511 - val_precision: 0.0565 - val_recall: 1.0000 - val_roc_auc: 0.5302 - val_combined: 0.3358
Epoch 72/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.6865 - pr_auc: 0.1100 - precision: 0.1027 - recall: 0.6207 - roc_auc: 0.5461 - val_loss: 0.7731 - val_pr_auc: 0.0454 - val_precision: 0.0585 - val_recall: 1.0000 - val_roc_auc: 0.4478 - val_combined: 0.3318
Epoch 73/200

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 22s 238ms/step - loss: 0.6936 - pr_auc: 0.0696 - precision: 0.0612 - recall: 0.4310 - roc_auc: 0.4664 - val_loss: 0.6958 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 2/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6935 - pr_auc: 0.0685 - precision: 0.0806 - recall: 0.6293 - roc_auc: 0.4621 - val_loss: 0.6930 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 3/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6931 - pr_auc: 0.0777 - precision: 0.0790 - recall: 0.3793 - roc_auc: 0.5080 - val_loss: 0.6925 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 4/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 221ms/step - loss: 0.6931 - pr_auc: 0.0806 - precision: 0.0752 - recall: 0.2672 - roc_auc: 0.5154 - val_loss: 0.6927 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 5/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6934 - pr_auc: 0.0710 - precision: 0.0764 - recall: 0.2845 - roc_auc: 0.4686 - val_loss: 0.6912 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 6/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 211ms/step - loss: 0.6933 - pr_auc: 0.0801 - precision: 0.0538 - recall: 0.1207 - roc_auc: 0.5119 - val_loss: 0.6927 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 7/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 242ms/step - loss: 0.6931 - pr_auc: 0.0835 - precision: 0.0486 - recall: 0.1207 - roc_auc: 0.5425 - val_loss: 0.6903 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 8/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 12s 272ms/step - loss: 0.6933 - pr_auc: 0.0784 - precision: 0.0567 - recall: 0.0948 - roc_auc: 0.5071 - val_loss: 0.6905 - val_pr_auc: 0.0521 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0365
Epoch 9/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 12s 254ms/step - loss: 0.6932 - pr_auc: 0.0783 - precision: 0.0657 - recall: 0.0776 - roc_auc: 0.5048 - val_loss: 0.6903 - val_pr_auc: 0.0524 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5027 - val_combined: 0.0366
Epoch 10/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 250ms/step - loss: 0.6928 - pr_auc: 0.0925 - precision: 0.0867 - recall: 0.1121 - roc_auc: 0.5616 - val_loss: 0.6900 - val_pr_auc: 0.0538 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5165 - val_combined: 0.0376
Epoch 11/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 213ms/step - loss: 0.6931 - pr_auc: 0.0761 - precision: 0.0631 - recall: 0.1121 - roc_auc: 0.4997 - val_loss: 0.6900 - val_pr_auc: 0.0541 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5192 - val_combined: 0.0378
Epoch 12/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 236ms/step - loss: 0.6926 - pr_auc: 0.0833 - precision: 0.0928 - recall: 0.1552 - roc_auc: 0.5179 - val_loss: 0.6901 - val_pr_auc: 0.0549 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5275 - val_combined: 0.0385
Epoch 13/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 241ms/step - loss: 0.6932 - pr_auc: 0.0802 - precision: 0.0606 - recall: 0.1034 - roc_auc: 0.5197 - val_loss: 0.6903 - val_pr_auc: 0.0546 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5247 - val_combined: 0.0383
Epoch 14/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6931 - pr_auc: 0.0828 - precision: 0.0458 - recall: 0.0603 - roc_auc: 0.5230 - val_loss: 0.6912 - val_pr_auc: 0.0535 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5137 - val_combined: 0.0374
Epoch 15/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6932 - pr_auc: 0.0907 - precision: 0.0875 - recall: 0.1207 - roc_auc: 0.5108 - val_loss: 0.6917 - val_pr_auc: 0.0529 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5082 - val_combined: 0.0370
Epoch 16/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 237ms/step - loss: 0.6927 - pr_auc: 0.0951 - precision: 0.0686 - recall: 0.1034 - roc_auc: 0.5526 - val_loss: 0.6919 - val_pr_auc: 0.0529 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5082 - val_combined: 0.0370
Epoch 17/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 12s 252ms/step - loss: 0.6931 - pr_auc: 0.0824 - precision: 0.0456 - recall: 0.0948 - roc_auc: 0.5277 - val_loss: 0.6919 - val_pr_auc: 0.0532 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5110 - val_combined: 0.0372
Epoch 18/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 245ms/step - loss: 0.6924 - pr_auc: 0.0936 - precision: 0.0787 - recall: 0.1466 - roc_auc: 0.5615 - val_loss: 0.6918 - val_pr_auc: 0.0543 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5220 - val_combined: 0.0380
Epoch 19/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 12s 250ms/step - loss: 0.6929 - pr_auc: 0.0901 - precision: 0.0671 - recall: 0.1638 - roc_auc: 0.5337 - val_loss: 0.6924 - val_pr_auc: 0.0538 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5165 - val_combined: 0.0376
Epoch 20/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6925 - pr_auc: 0.0880 - precision: 0.0943 - recall: 0.3017 - roc_auc: 0.5500 - val_loss: 0.6933 - val_pr_auc: 0.0535 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5137 - val_combined: 0.0374
Epoch 21/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.6927 - pr_auc: 0.0880 - precision: 0.0841 - recall: 0.3362 - roc_auc: 0.5480 - val_loss: 0.6940 - val_pr_auc: 0.0538 - val_precision: 0.0288 - val_recall: 0.4000 - val_roc_auc: 0.5165 - val_combined: 0.1576
Epoch 22/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 232ms/step - loss: 0.6929 - pr_auc: 0.0981 - precision: 0.1012 - recall: 0.4224 - roc_auc: 0.5497 - val_loss: 0.6951 - val_pr_auc: 0.0535 - val_precision: 0.0375 - val_recall: 0.6000 - val_roc_auc: 0.5137 - val_combined: 0.2174
Epoch 23/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6933 - pr_auc: 0.0875 - precision: 0.0869 - recall: 0.4741 - roc_auc: 0.5232 - val_loss: 0.6979 - val_pr_auc: 0.0301 - val_precision: 0.0549 - val_recall: 1.0000 - val_roc_auc: 0.1676 - val_combined: 0.3211
Epoch 24/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 220ms/step - loss: 0.6922 - pr_auc: 0.0889 - precision: 0.1068 - recall: 0.6379 - roc_auc: 0.5431 - val_loss: 0.7002 - val_pr_auc: 0.0578 - val_precision: 0.0543 - val_recall: 1.0000 - val_roc_auc: 0.5522 - val_combined: 0.3405
Epoch 25/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6919 - pr_auc: 0.0871 - precision: 0.0917 - recall: 0.5690 - roc_auc: 0.5444 - val_loss: 0.7000 - val_pr_auc: 0.0386 - val_precision: 0.0556 - val_recall: 1.0000 - val_roc_auc: 0.3558 - val_combined: 0.3270
Epoch 26/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6936 - pr_auc: 0.0790 - precision: 0.0937 - recall: 0.5517 - roc_auc: 0.4985 - val_loss: 0.7021 - val_pr_auc: 0.0571 - val_precision: 0.0546 - val_recall: 1.0000 - val_roc_auc: 0.5467 - val_combined: 0.3400
Epoch 27/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 228ms/step - loss: 0.6920 - pr_auc: 0.0855 - precision: 0.1001 - recall: 0.6207 - roc_auc: 0.5339 - val_loss: 0.7036 - val_pr_auc: 0.0391 - val_precision: 0.0552 - val_recall: 1.0000 - val_roc_auc: 0.3956 - val_combined: 0.3274
Epoch 28/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 250ms/step - loss: 0.6923 - pr_auc: 0.0823 - precision: 0.1010 - recall: 0.6207 - roc_auc: 0.5239 - val_loss: 0.7050 - val_pr_auc: 0.0367 - val_precision: 0.0552 - val_recall: 1.0000 - val_roc_auc: 0.3462 - val_combined: 0.3257
Epoch 29/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 20s 230ms/step - loss: 0.6920 - pr_auc: 0.0926 - precision: 0.1001 - recall: 0.6466 - roc_auc: 0.5412 - val_loss: 0.7080 - val_pr_auc: 0.0382 - val_precision: 0.0549 - val_recall: 1.0000 - val_roc_auc: 0.3604 - val_combined: 0.3267
Epoch 30/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 12s 253ms/step - loss: 0.6916 - pr_auc: 0.0900 - precision: 0.1000 - recall: 0.6466 - roc_auc: 0.5480 - val_loss: 0.7117 - val_pr_auc: 0.0394 - val_precision: 0.0549 - val_recall: 1.0000 - val_roc_auc: 0.3984 - val_combined: 0.3276
Epoch 31/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 12s 261ms/step - loss: 0.6935 - pr_auc: 0.0770 - precision: 0.0937 - recall: 0.6121 - roc_auc: 0.5020 - val_loss: 0.7113 - val_pr_auc: 0.0405 - val_precision: 0.0543 - val_recall: 1.0000 - val_roc_auc: 0.4176 - val_combined: 0.3284
Epoch 32/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 12s 252ms/step - loss: 0.6910 - pr_auc: 0.0877 - precision: 0.1023 - recall: 0.6638 - roc_auc: 0.5484 - val_loss: 0.7132 - val_pr_auc: 0.0378 - val_precision: 0.0549 - val_recall: 1.0000 - val_roc_auc: 0.3654 - val_combined: 0.3264
Epoch 33/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 210ms/step - loss: 0.6926 - pr_auc: 0.0798 - precision: 0.0952 - recall: 0.5948 - roc_auc: 0.5212 - val_loss: 0.7137 - val_pr_auc: 0.0373 - val_precision: 0.0549 - val_recall: 1.0000 - val_roc_auc: 0.3571 - val_combined: 0.3261
Epoch 34/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 222ms/step - loss: 0.6915 - pr_auc: 0.0863 - precision: 0.0988 - recall: 0.6466 - roc_auc: 0.5417 - val_loss: 0.7157 - val_pr_auc: 0.0357 - val_precision: 0.0549 - val_recall: 1.0000 - val_roc_auc: 0.3313 - val_combined: 0.3250
Epoch 35/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 232ms/step - loss: 0.6909 - pr_auc: 0.0915 - precision: 0.1000 - recall: 0.6552 - roc_auc: 0.5541 - val_loss: 0.7192 - val_pr_auc: 0.0357 - val_precision: 0.0546 - val_recall: 1.0000 - val_roc_auc: 0.3341 - val_combined: 0.3250
Epoch 36/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 234ms/step - loss: 0.6904 - pr_auc: 0.0965 - precision: 0.1019 - recall: 0.6638 - roc_auc: 0.5607 - val_loss: 0.7222 - val_pr_auc: 0.0380 - val_precision: 0.0549 - val_recall: 1.0000 - val_roc_auc: 0.3681 - val_combined: 0.3266
Epoch 37/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 13s 279ms/step - loss: 0.6891 - pr_auc: 0.0935 - precision: 0.1049 - recall: 0.6810 - roc_auc: 0.5691 - val_loss: 0.7280 - val_pr_auc: 0.0367 - val_precision: 0.0556 - val_recall: 1.0000 - val_roc_auc: 0.3495 - val_combined: 0.3257
Epoch 38/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 19s 234ms/step - loss: 0.6894 - pr_auc: 0.0946 - precision: 0.1003 - recall: 0.6638 - roc_auc: 0.5665 - val_loss: 0.7343 - val_pr_auc: 0.0366 - val_precision: 0.0552 - val_recall: 1.0000 - val_roc_auc: 0.3484 - val_combined: 0.3256
Epoch 39/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 236ms/step - loss: 0.6908 - pr_auc: 0.0893 - precision: 0.0986 - recall: 0.6552 - roc_auc: 0.5448 - val_loss: 0.7364 - val_pr_auc: 0.0361 - val_precision: 0.0552 - val_recall: 1.0000 - val_roc_auc: 0.3365 - val_combined: 0.3253
Epoch 40/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 222ms/step - loss: 0.6902 - pr_auc: 0.0883 - precision: 0.1003 - recall: 0.6638 - roc_auc: 0.5483 - val_loss: 0.7408 - val_pr_auc: 0.0354 - val_precision: 0.0552 - val_recall: 1.0000 - val_roc_auc: 0.3118 - val_combined: 0.3248
Epoch 41/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6908 - pr_auc: 0.0847 - precision: 0.0987 - recall: 0.6466 - roc_auc: 0.5447 - val_loss: 0.7409 - val_pr_auc: 0.0363 - val_precision: 0.0556 - val_recall: 1.0000 - val_roc_auc: 0.3357 - val_combined: 0.3254
Epoch 42/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 236ms/step - loss: 0.6884 - pr_auc: 0.0873 - precision: 0.1046 - recall: 0.6810 - roc_auc: 0.5629 - val_loss: 0.7413 - val_pr_auc: 0.0376 - val_precision: 0.0565 - val_recall: 1.0000 - val_roc_auc: 0.3643 - val_combined: 0.3263
Epoch 43/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 245ms/step - loss: 0.6891 - pr_auc: 0.0850 - precision: 0.1033 - recall: 0.6552 - roc_auc: 0.5535 - val_loss: 0.7428 - val_pr_auc: 0.0359 - val_precision: 0.0575 - val_recall: 1.0000 - val_roc_auc: 0.3269 - val_combined: 0.3251
Epoch 44/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6884 - pr_auc: 0.0850 - precision: 0.1053 - recall: 0.6724 - roc_auc: 0.5498 - val_loss: 0.7518 - val_pr_auc: 0.0349 - val_precision: 0.0585 - val_recall: 1.0000 - val_roc_auc: 0.2868 - val_combined: 0.3244
Epoch 45/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.6897 - pr_auc: 0.0856 - precision: 0.1011 - recall: 0.6552 - roc_auc: 0.5410 - val_loss: 0.7532 - val_pr_auc: 0.0354 - val_precision: 0.0578 - val_recall: 1.0000 - val_roc_auc: 0.2940 - val_combined: 0.3248
Epoch 46/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6887 - pr_auc: 0.0876 - precision: 0.0970 - recall: 0.6379 - roc_auc: 0.5486 - val_loss: 0.7612 - val_pr_auc: 0.0376 - val_precision: 0.0585 - val_recall: 1.0000 - val_roc_auc: 0.3651 - val_combined: 0.3263
Epoch 47/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6884 - pr_auc: 0.0839 - precision: 0.1005 - recall: 0.6379 - roc_auc: 0.5487 - val_loss: 0.7686 - val_pr_auc: 0.0378 - val_precision: 0.0578 - val_recall: 1.0000 - val_roc_auc: 0.3621 - val_combined: 0.3264
Epoch 48/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 229ms/step - loss: 0.6855 - pr_auc: 0.0955 - precision: 0.0981 - recall: 0.6552 - roc_auc: 0.5762 - val_loss: 0.7742 - val_pr_auc: 0.0363 - val_precision: 0.0581 - val_recall: 1.0000 - val_roc_auc: 0.3187 - val_combined: 0.3254
Epoch 49/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.6867 - pr_auc: 0.0921 - precision: 0.0977 - recall: 0.6466 - roc_auc: 0.5615 - val_loss: 0.7755 - val_pr_auc: 0.0416 - val_precision: 0.0588 - val_recall: 1.0000 - val_roc_auc: 0.4159 - val_combined: 0.3291
Epoch 50/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 215ms/step - loss: 0.6871 - pr_auc: 0.0905 - precision: 0.0975 - recall: 0.6379 - roc_auc: 0.5596 - val_loss: 0.7741 - val_pr_auc: 0.0430 - val_precision: 0.0585 - val_recall: 1.0000 - val_roc_auc: 0.4352 - val_combined: 0.3301
Epoch 51/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 224ms/step - loss: 0.6840 - pr_auc: 0.1000 - precision: 0.1023 - recall: 0.6552 - roc_auc: 0.5777 - val_loss: 0.7771 - val_pr_auc: 0.0375 - val_precision: 0.0585 - val_recall: 1.0000 - val_roc_auc: 0.3695 - val_combined: 0.3263
Epoch 52/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6909 - pr_auc: 0.0819 - precision: 0.0980 - recall: 0.6293 - roc_auc: 0.5275 - val_loss: 0.7710 - val_pr_auc: 0.0351 - val_precision: 0.0592 - val_recall: 1.0000 - val_roc_auc: 0.2929 - val_combined: 0.3246
Epoch 53/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.6862 - pr_auc: 0.0852 - precision: 0.1036 - recall: 0.6466 - roc_auc: 0.5597 - val_loss: 0.7730 - val_pr_auc: 0.0356 - val_precision: 0.0575 - val_recall: 1.0000 - val_roc_auc: 0.3228 - val_combined: 0.3249
Epoch 54/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6867 - pr_auc: 0.0919 - precision: 0.1016 - recall: 0.6638 - roc_auc: 0.5581 - val_loss: 0.7748 - val_pr_auc: 0.0354 - val_precision: 0.0571 - val_recall: 1.0000 - val_roc_auc: 0.3187 - val_combined: 0.3248
Epoch 55/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 233ms/step - loss: 0.6836 - pr_auc: 0.0943 - precision: 0.1046 - recall: 0.6810 - roc_auc: 0.5745 - val_loss: 0.7754 - val_pr_auc: 0.0380 - val_precision: 0.0592 - val_recall: 1.0000 - val_roc_auc: 0.3764 - val_combined: 0.3266
Epoch 56/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 225ms/step - loss: 0.6804 - pr_auc: 0.1115 - precision: 0.1008 - recall: 0.6379 - roc_auc: 0.6050 - val_loss: 0.7834 - val_pr_auc: 0.0345 - val_precision: 0.0578 - val_recall: 1.0000 - val_roc_auc: 0.2720 - val_combined: 0.3241
Epoch 57/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.6843 - pr_auc: 0.0931 - precision: 0.1001 - recall: 0.6552 - roc_auc: 0.5757 - val_loss: 0.7837 - val_pr_auc: 0.0362 - val_precision: 0.0575 - val_recall: 1.0000 - val_roc_auc: 0.3187 - val_combined: 0.3253
Epoch 58/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6808 - pr_auc: 0.0941 - precision: 0.1072 - recall: 0.6810 - roc_auc: 0.5945 - val_loss: 0.7812 - val_pr_auc: 0.0418 - val_precision: 0.0588 - val_recall: 1.0000 - val_roc_auc: 0.4187 - val_combined: 0.3293
Epoch 59/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 219ms/step - loss: 0.6858 - pr_auc: 0.0899 - precision: 0.1036 - recall: 0.6379 - roc_auc: 0.5601 - val_loss: 0.7789 - val_pr_auc: 0.0366 - val_precision: 0.0588 - val_recall: 1.0000 - val_roc_auc: 0.3104 - val_combined: 0.3256
Epoch 60/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6827 - pr_auc: 0.0992 - precision: 0.1050 - recall: 0.6552 - roc_auc: 0.5780 - val_loss: 0.7806 - val_pr_auc: 0.0436 - val_precision: 0.0592 - val_recall: 1.0000 - val_roc_auc: 0.4341 - val_combined: 0.3305
Epoch 61/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.6869 - pr_auc: 0.0868 - precision: 0.1008 - recall: 0.6293 - roc_auc: 0.5551 - val_loss: 0.7850 - val_pr_auc: 0.0364 - val_precision: 0.0571 - val_recall: 1.0000 - val_roc_auc: 0.3401 - val_combined: 0.3254
Epoch 62/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 230ms/step - loss: 0.6849 - pr_auc: 0.1003 - precision: 0.1013 - recall: 0.6552 - roc_auc: 0.5701 - val_loss: 0.7877 - val_pr_auc: 0.0412 - val_precision: 0.0568 - val_recall: 1.0000 - val_roc_auc: 0.4093 - val_combined: 0.3288
Epoch 63/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 232ms/step - loss: 0.6853 - pr_auc: 0.0899 - precision: 0.1039 - recall: 0.6379 - roc_auc: 0.5606 - val_loss: 0.7840 - val_pr_auc: 0.0406 - val_precision: 0.0585 - val_recall: 1.0000 - val_roc_auc: 0.4005 - val_combined: 0.3284
Epoch 64/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 241ms/step - loss: 0.6849 - pr_auc: 0.0917 - precision: 0.1057 - recall: 0.6379 - roc_auc: 0.5607 - val_loss: 0.7860 - val_pr_auc: 0.0372 - val_precision: 0.0581 - val_recall: 1.0000 - val_roc_auc: 0.3577 - val_combined: 0.3260
Epoch 65/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 229ms/step - loss: 0.6811 - pr_auc: 0.0976 - precision: 0.1053 - recall: 0.6379 - roc_auc: 0.5896 - val_loss: 0.7862 - val_pr_auc: 0.0363 - val_precision: 0.0585 - val_recall: 1.0000 - val_roc_auc: 0.3379 - val_combined: 0.3254
Epoch 66/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 21s 231ms/step - loss: 0.6840 - pr_auc: 0.0975 - precision: 0.1074 - recall: 0.6466 - roc_auc: 0.5661 - val_loss: 0.7865 - val_pr_auc: 0.0350 - val_precision: 0.0588 - val_recall: 1.0000 - val_roc_auc: 0.2830 - val_combined: 0.3245
Epoch 67/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 244ms/step - loss: 0.6822 - pr_auc: 0.0943 - precision: 0.1066 - recall: 0.6293 - roc_auc: 0.5786 - val_loss: 0.7888 - val_pr_auc: 0.0430 - val_precision: 0.0585 - val_recall: 1.0000 - val_roc_auc: 0.4352 - val_combined: 0.3301
Epoch 68/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6791 - pr_auc: 0.1020 - precision: 0.1082 - recall: 0.6466 - roc_auc: 0.5940 - val_loss: 0.7873 - val_pr_auc: 0.0473 - val_precision: 0.0592 - val_recall: 1.0000 - val_roc_auc: 0.4703 - val_combined: 0.3331
Epoch 69/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6789 - pr_auc: 0.0980 - precision: 0.1071 - recall: 0.6379 - roc_auc: 0.5978 - val_loss: 0.7907 - val_pr_auc: 0.0405 - val_precision: 0.0581 - val_recall: 1.0000 - val_roc_auc: 0.3989 - val_combined: 0.3283
Epoch 70/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 223ms/step - loss: 0.6794 - pr_auc: 0.1073 - precision: 0.1066 - recall: 0.6552 - roc_auc: 0.5930 - val_loss: 0.7875 - val_pr_auc: 0.0411 - val_precision: 0.0588 - val_recall: 1.0000 - val_roc_auc: 0.4088 - val_combined: 0.3288
Epoch 71/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 236ms/step - loss: 0.6778 - pr_auc: 0.0961 - precision: 0.1090 - recall: 0.6293 - roc_auc: 0.6051 - val_loss: 0.7940 - val_pr_auc: 0.0447 - val_precision: 0.0575 - val_recall: 1.0000 - val_roc_auc: 0.4396 - val_combined: 0.3313
Epoch 72/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 231ms/step - loss: 0.6802 - pr_auc: 0.1010 - precision: 0.1078 - recall: 0.6552 - roc_auc: 0.5872 - val_loss: 0.7972 - val_pr_auc: 0.0443 - val_precision: 0.0571 - val_recall: 1.0000 - val_roc_auc: 0.4484 - val_combined: 0.3310
Epoch 73/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 226ms/step - loss: 0.6813 - pr_auc: 0.0971 - precision: 0.1072 - recall: 0.6379 - roc_auc: 0.5795 - val_loss: 0.7865 - val_pr_auc: 0.0834 - val_precision: 0.0595 - val_recall: 1.0000 - val_roc_auc: 0.7060 - val_combined: 0.3584

In [ ]:
df_robustness = pd.DataFrame(robustness_results)
df_robustness = pd.concat([df_robustness, pd.DataFrame({'seed': 23,
                                                        'recall': 0.75,
                                                        'f1': 0.18,
                                                        'roc_auc': 0.77,
                                                        'tn': 239,
                                                        'fp': 153,
                                                        'fn': 6,
                                                        'tp': 18},
                                                        index=[0])], ignore_index=True) #add results from baseline model
df_robustness

   seed  recall        f1   roc_auc   tn   fp  fn  tp
0    38   1.000  0.109091  0.551339    0  392   0  24
1    60   0.750  0.178218  0.700893  232  160   6  18
2    96   0.750  0.180905  0.729911  235  157   6  18
3   146   0.750  0.167442  0.554953  219  173   6  18
4   162   0.625  0.194805  0.663690  277  115   9  15
5    23   0.750  0.180000  0.770000  239  153   6  18

```python
df_robustness.to_csv("df_robustness.csv", index=True)
files.download("df_robustness.csv")
df_robustness.to_parquet("df_robustness.parquet", index=True)
files.download("df_robustness.parquet")
```

In [ ]:
#df_robustness = import_data(file_path)

In [ ]:
df_robustness = df_robustness.set_index('seed')[['recall',	'f1',	'roc_auc']].sort_index()
df_robustness = df_robustness.rename(columns={'recall':'Recall',	'f1':'F1-Score',	'roc_auc':'ROC-AUC'})

In [ ]:
df_robustness.round(2)

      Recall  F1-Score  ROC-AUC
seed
23      0.75      0.18     0.77
38      1.00      0.11     0.55
60      0.75      0.18     0.70
96      0.75      0.18     0.73
146     0.75      0.17     0.55
162     0.62      0.19     0.66

In [ ]:
df_robustness.mean().round(2).rename('mean')

Recall      0.77
F1-Score    0.17
ROC-AUC     0.66
Name: mean, dtype: float64

In [ ]:
df_robustness.std().round(2).rename('std')

Recall      0.12
F1-Score    0.03
ROC-AUC     0.09
Name: std, dtype: float64