# Appendix C3. 20-day Rolling Volatility as a Stress Proxy: Sensitivity of LSTM Results to Random Initialization

In [ ]:
# --- ENV FIRST ---
import os
os.environ["TF_DETERMINISTIC_OPS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["TF_NUM_INTRAOP_THREADS"] = "1"
os.environ["TF_NUM_INTEROP_THREADS"] = "1"
# --- IMPORTS ---
import random
import numpy as np
import tensorflow as tf
# --- TF CONFIG ---
tf.config.threading.set_inter_op_parallelism_threads(1)
tf.config.threading.set_intra_op_parallelism_threads(1)
tf.config.set_visible_devices([], 'GPU')
# --- RESET ---
tf.keras.backend.clear_session()

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import recall_score, f1_score, roc_auc_score, confusion_matrix, accuracy_score, roc_curve
import itertools
from sklearn.utils.class_weight import compute_class_weight
from tensorflow import keras
from tensorflow.keras import layers
try:
  import keras_tuner as kt
except:
  !pip install keras-tuner
  import keras_tuner as kt
from google.colab import files
from google.colab import drive
import pandas as pd
import io
import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.1)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.80.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.4.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 1.7 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [ ]:
def import_data(file_path):
  try:
    drive.mount('/content/drive', force_remount=True)
    # Check if file exists
    if os.path.exists(file_path):
      df = pd.read_parquet(file_path)
      print(f"Loaded dataframe from Drive ({file_path})")
    else:
      raise FileNotFoundError(f"File not found at {file_path}")

  except Exception as e:
    print(f"Drive not available or file missing: {e}")
    print("Please upload dataframe manually.")
    uploaded = files.upload()

    # Automatically read the uploaded file
    file_name = list(uploaded.keys())[0]  # pick the first uploaded file
    try:
      df = pd.read_parquet(io.BytesIO(uploaded[file_name]))
    except:
      print("Wrong file extension. Parquet file required.")
    print(f"Loaded {file_name} from manual upload.")
    return df

In [ ]:
def train_classifier(model, X_train, y_train, X_test, y_test, X_val=False, y_val=False, threshold=0.5, early_stopping=False):
  is_keras = hasattr(model, "fit") and hasattr(model, "predict") and not hasattr(model, "predict_proba")
  if is_keras:
    if early_stopping:
      model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, class_weight=class_weight, validation_data=(X_val, y_val), shuffle=False, callbacks=[combined_metric, es])
    else:
      model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, class_weight=class_weight, validation_data=(X_val, y_val), shuffle=False)
    y_score = model.predict(X_test).ravel()
    y_pred = (y_score >= threshold).astype(int)
  else:
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_score = model.predict_proba(X_test)[:, 1]

  # Output Following Metrics:
  recall = recall_score(y_test, y_pred)
  f1 = f1_score(y_test, y_pred)
  roc_auc = roc_auc_score(y_test, y_score)
  cm = confusion_matrix(y_test, y_pred)

  return recall, f1, roc_auc, cm, y_score, y_pred

In [ ]:
file_path = "..."
df_model_2 = import_data(file_path)

Drive not available or file missing: Error: credential propagation was unsuccessful
Please upload dataframe manually.

Saving df_model_2.parquet to df_model_2.parquet
Loaded df_model_2.parquet from manual upload.

In [ ]:
# align the dataframe at the same starting date of the VSRI
df_model_2 = df_model_2.loc['2017-01-03':].dropna()

In [ ]:
df_model_2.shape

(2384, 2)

In [ ]:
# split data in training and test set and apply purging
split_date = "2024-03-31"
purge = 20
train_2 = df_model_2.loc[:split_date].iloc[:-purge]
test_2  = df_model_2[df_model_2.index > split_date]
X_train_2 = train_2[["vn_volatility"]]
y_train_2 = train_2["systemic_stress_event"]
X_test_2  = test_2[["vn_volatility"]]
y_test_2  = test_2["systemic_stress_event"]

In [ ]:
timesteps = 60
split_idx = pd.Timestamp("2023-03-01")
X_train_lstm_bench_2 = X_train_2[X_train_2.index < split_idx].iloc[:-purge]
y_train_lstm_bench_2 = y_train_2[y_train_2.index < split_idx].iloc[:-purge]
X_val_lstm_bench_2 = X_train_2.loc[split_idx:]
y_val_lstm_bench_2 = y_train_2.loc[split_idx:]

X_train_values_bench_2 = X_train_lstm_bench_2.values
y_train_values_bench_2 = y_train_lstm_bench_2.values
X_test_values_bench_2 = X_test_2.values
y_test_values_bench_2 = y_test_2.values
X_val_values_bench_2 = X_val_lstm_bench_2.values
y_val_values_bench_2 = y_val_lstm_bench_2.values
X_train_seq_bench_2 = []
y_train_seq_bench_2 = []
X_test_seq_bench_2 = []
y_test_seq_bench_2 = []
X_val_seq_bench_2 = []
y_val_seq_bench_2 = []
for i in range(timesteps, len(X_train_values_bench_2)):
  X_train_seq_bench_2.append(X_train_values_bench_2[i - timesteps:i])
  y_train_seq_bench_2.append(y_train_values_bench_2[i])
for i in range(timesteps, len(X_test_values_bench_2)):
  X_test_seq_bench_2.append(X_test_values_bench_2[i - timesteps:i])
  y_test_seq_bench_2.append(y_test_values_bench_2[i])
for i in range(timesteps, len(X_val_values_bench_2)):
  X_val_seq_bench_2.append(X_val_values_bench_2[i - timesteps:i])
  y_val_seq_bench_2.append(y_val_values_bench_2[i])

X_train_seq_bench_2 = np.array(X_train_seq_bench_2)
y_train_seq_bench_2 = np.array(y_train_seq_bench_2)
X_test_seq_bench_2 = np.array(X_test_seq_bench_2)
y_test_seq_bench_2 = np.array(y_test_seq_bench_2)
X_val_seq_bench_2 = np.array(X_val_seq_bench_2)
y_val_seq_bench_2 = np.array(y_val_seq_bench_2)

In [ ]:
print(X_train_seq_bench_2.shape,
      y_train_seq_bench_2.shape,
      X_val_seq_bench_2.shape,
      y_val_seq_bench_2.shape,
      X_test_seq_bench_2.shape,
      y_test_seq_bench_2.shape)

(1522, 60, 1) (1522,) (202, 60, 1) (202,) (440, 60, 1) (440,)

In [ ]:
class CombinedMetric(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs=None):
    logs = logs or {}
    recall = logs.get("val_recall", 0)
    pr_auc = logs.get("val_pr_auc", 0)
    logs["val_combined"] = 0.3 * recall + 0.7 * pr_auc

In [ ]:
classes = np.unique(y_train_seq_bench_2)
weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train_seq_bench_2)
class_weight = dict(zip(classes, weights))
epochs=200
batch_size=32

In [ ]:
seeds = [38, 60, 96, 146, 162]
robustness_results_bench_2 = []
input_shape = X_train_seq_bench_2.shape[1:]

In [ ]:
for seed in seeds:
  print(f"\nRunning seed {seed}")
  tf.keras.backend.clear_session()
  random.seed(seed)
  np.random.seed(seed)
  tf.keras.utils.set_random_seed(seed)

  # LSTM MODEL
  lstm_model_bench_2 = keras.Sequential()
  lstm_model_bench_2.add(layers.LSTM(128, return_sequences=True, input_shape=input_shape))
  lstm_model_bench_2.add(layers.Dropout(0.5))
  lstm_model_bench_2.add(layers.LSTM(128, return_sequences=True))
  lstm_model_bench_2.add(layers.LSTM(16, return_sequences=True))
  lstm_model_bench_2.add(layers.LSTM(8, return_sequences=True))
  lstm_model_bench_2.add(layers.Dropout(0.3))
  lstm_model_bench_2.add(layers.LSTM(8, return_sequences=False))
  lstm_model_bench_2.add(layers.Dropout(0.3))
  # Dense layers
  lstm_model_bench_2.add(layers.Dense(16, activation="relu"))
  lstm_model_bench_2.add(layers.Dense(1, activation="sigmoid"))
  # Compile
  lstm_model_bench_2.compile(optimizer=keras.optimizers.Adam(learning_rate=0.0001),
                             loss="binary_crossentropy",
                             metrics=[keras.metrics.AUC(name="pr_auc", curve="PR"),
                                      keras.metrics.AUC(name="roc_auc", curve="ROC"),
                                      tf.keras.metrics.Recall(name="recall"),
                                      tf.keras.metrics.Precision(name="precision")])

  combined_metric = CombinedMetric()
  es = tf.keras.callbacks.EarlyStopping(monitor="val_combined",
                                        mode="max",
                                        patience=50,
                                        restore_best_weights=True,
                                        verbose=1)

  # TRAIN
  lstm_results_bench_2 = train_classifier(lstm_model_bench_2, X_train_seq_bench_2, y_train_seq_bench_2, X_test_seq_bench_2, y_test_seq_bench_2, X_val=X_val_seq_bench_2, y_val=y_val_seq_bench_2, early_stopping=True)
  lstm_recall_bench_2, lstm_f1_bench_2, lstm_roc_auc_bench_2, lstm_cm_bench_2, lstm_probs_bench_2, lstm_preds_bench_2 = lstm_results_bench_2
  # Store results
  robustness_results_bench_2.append({"seed": seed,
                                     "recall": lstm_recall_bench_2,
                                     "f1": lstm_f1_bench_2,
                                     "roc_auc": lstm_roc_auc_bench_2,
                                     "tn": lstm_cm_bench_2[0,0],
                                     "fp": lstm_cm_bench_2[0,1],
                                     "fn": lstm_cm_bench_2[1,0],
                                     "tp": lstm_cm_bench_2[1,1]})

Running seed 38

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 33s 223ms/step - loss: 0.6933 - pr_auc: 0.0834 - precision: 0.0675 - recall: 0.5354 - roc_auc: 0.5000 - val_loss: 0.6940 - val_pr_auc: 0.0495 - val_precision: 0.0495 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3347
Epoch 2/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 11s 221ms/step - loss: 0.6933 - pr_auc: 0.0834 - precision: 0.0762 - recall: 0.8110 - roc_auc: 0.5000 - val_loss: 0.6937 - val_pr_auc: 0.0495 - val_precision: 0.0495 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3347
Epoch 3/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6933 - pr_auc: 0.0834 - precision: 0.0816 - recall: 0.8819 - roc_auc: 0.5000 - val_loss: 0.6935 - val_pr_auc: 0.0495 - val_precision: 0.0495 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3347
Epoch 4/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 195ms/step - loss: 0.6933 - pr_auc: 0.0834 - precision: 0.0703 - recall: 0.6929 - roc_auc: 0.5000 - val_loss: 0.6933 - val_pr_auc: 0.0495 - val_precision: 0.0495 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3347
Epoch 5/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 12s 259ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0647 - recall: 0.4882 - roc_auc: 0.5000 - val_loss: 0.6931 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 6/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 187ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0648 - recall: 0.2520 - roc_auc: 0.5000 - val_loss: 0.6928 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 7/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0280 - recall: 0.0315 - roc_auc: 0.5000 - val_loss: 0.6927 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 8/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6927 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 9/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0769 - recall: 0.0079 - roc_auc: 0.5000 - val_loss: 0.6927 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 10/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 210ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6927 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 11/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 218ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6927 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 12/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6927 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 13/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 177ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6927 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 14/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6927 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 15/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6927 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 16/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 180ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6926 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 17/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 198ms/step - loss: 0.6931 - pr_auc: 0.0834 - precision: 0.0758 - recall: 0.0394 - roc_auc: 0.5000 - val_loss: 0.6926 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 18/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0400 - recall: 0.0157 - roc_auc: 0.5000 - val_loss: 0.6926 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 19/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 199ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6926 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 20/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 178ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.1000 - recall: 0.0079 - roc_auc: 0.5000 - val_loss: 0.6927 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 21/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.1111 - recall: 0.0079 - roc_auc: 0.5000 - val_loss: 0.6926 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 22/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6926 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 23/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 182ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6926 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 24/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 197ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6926 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 25/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6926 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 26/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6926 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 27/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 179ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6926 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 28/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6926 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 29/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6926 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 30/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 8s 176ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6925 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 31/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6925 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 32/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6926 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 33/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 190ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6925 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 34/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 188ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6925 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 35/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6925 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 36/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6925 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 37/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 8s 177ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0204 - recall: 0.0079 - roc_auc: 0.5000 - val_loss: 0.6924 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 38/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6925 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 39/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.1000 - recall: 0.0079 - roc_auc: 0.5000 - val_loss: 0.6924 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 40/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 178ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0385 - recall: 0.0157 - roc_auc: 0.5000 - val_loss: 0.6925 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 41/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 201ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6925 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 42/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6925 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 43/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 191ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6925 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 44/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 186ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6925 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 45/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0556 - recall: 0.0079 - roc_auc: 0.5000 - val_loss: 0.6924 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 46/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6924 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 47/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 176ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0500 - recall: 0.0079 - roc_auc: 0.5000 - val_loss: 0.6924 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 48/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6924 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 49/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6924 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 50/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 179ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6924 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 51/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 198ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6924 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 51: early stopping
Restoring model weights from the end of the best epoch: 1.
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step

Running seed 60

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 20s 227ms/step - loss: 0.6935 - pr_auc: 0.0725 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4409 - val_loss: 0.6882 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 2/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 185ms/step - loss: 0.6935 - pr_auc: 0.0749 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4600 - val_loss: 0.6887 - val_pr_auc: 0.0552 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5547 - val_combined: 0.0387
Epoch 3/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 190ms/step - loss: 0.6933 - pr_auc: 0.0757 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4610 - val_loss: 0.6888 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 4/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6933 - pr_auc: 0.0744 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4538 - val_loss: 0.6889 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 5/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 201ms/step - loss: 0.6934 - pr_auc: 0.0748 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4552 - val_loss: 0.6893 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 6/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - loss: 0.6932 - pr_auc: 0.0737 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4473 - val_loss: 0.6888 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 7/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6932 - pr_auc: 0.0762 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4650 - val_loss: 0.6884 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 8/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6933 - pr_auc: 0.0720 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4442 - val_loss: 0.6886 - val_pr_auc: 0.0400 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.4109 - val_combined: 0.0280
Epoch 9/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - loss: 0.6932 - pr_auc: 0.0847 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5058 - val_loss: 0.6884 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 10/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6933 - pr_auc: 0.0819 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4937 - val_loss: 0.6882 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 11/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6933 - pr_auc: 0.0811 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4893 - val_loss: 0.6884 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 12/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 189ms/step - loss: 0.6935 - pr_auc: 0.0756 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4625 - val_loss: 0.6890 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 13/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 185ms/step - loss: 0.6933 - pr_auc: 0.0752 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4563 - val_loss: 0.6891 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 14/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6934 - pr_auc: 0.0719 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4351 - val_loss: 0.6895 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 15/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0782 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4720 - val_loss: 0.6894 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 16/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - loss: 0.6934 - pr_auc: 0.0772 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4641 - val_loss: 0.6897 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 17/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6933 - pr_auc: 0.0720 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4308 - val_loss: 0.6897 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 18/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6933 - pr_auc: 0.0797 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4776 - val_loss: 0.6902 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 19/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 182ms/step - loss: 0.6932 - pr_auc: 0.0807 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4837 - val_loss: 0.6898 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 20/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 197ms/step - loss: 0.6933 - pr_auc: 0.0806 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4833 - val_loss: 0.6899 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 21/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6933 - pr_auc: 0.0718 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4308 - val_loss: 0.6897 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 22/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6931 - pr_auc: 0.0811 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4874 - val_loss: 0.6890 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 23/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 8s 176ms/step - loss: 0.6933 - pr_auc: 0.0791 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4778 - val_loss: 0.6893 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 24/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6932 - pr_auc: 0.0835 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5003 - val_loss: 0.6892 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 25/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0839 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5024 - val_loss: 0.6892 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 26/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 8s 176ms/step - loss: 0.6932 - pr_auc: 0.0870 - precision: 0.1111 - recall: 0.0079 - roc_auc: 0.5168 - val_loss: 0.6890 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 27/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 179ms/step - loss: 0.6932 - pr_auc: 0.0888 - precision: 0.1538 - recall: 0.0157 - roc_auc: 0.5250 - val_loss: 0.6889 - val_pr_auc: 0.0526 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5312 - val_combined: 0.0368
Epoch 28/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6934 - pr_auc: 0.0779 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4713 - val_loss: 0.6894 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 29/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0785 - precision: 0.0769 - recall: 0.0079 - roc_auc: 0.4745 - val_loss: 0.6898 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 30/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 178ms/step - loss: 0.6933 - pr_auc: 0.0803 - precision: 0.0556 - recall: 0.0315 - roc_auc: 0.4831 - val_loss: 0.6898 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 31/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0845 - precision: 0.0385 - recall: 0.0079 - roc_auc: 0.5053 - val_loss: 0.6898 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 32/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6934 - pr_auc: 0.0750 - precision: 0.0357 - recall: 0.0079 - roc_auc: 0.4527 - val_loss: 0.6900 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 33/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 195ms/step - loss: 0.6932 - pr_auc: 0.0814 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4888 - val_loss: 0.6899 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 34/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 187ms/step - loss: 0.6933 - pr_auc: 0.0772 - precision: 0.0600 - recall: 0.0236 - roc_auc: 0.4652 - val_loss: 0.6898 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 35/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6933 - pr_auc: 0.0777 - precision: 0.0714 - recall: 0.0236 - roc_auc: 0.4680 - val_loss: 0.6898 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 36/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6934 - pr_auc: 0.0755 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4537 - val_loss: 0.6901 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 37/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 179ms/step - loss: 0.6932 - pr_auc: 0.0763 - precision: 0.1111 - recall: 0.0079 - roc_auc: 0.4591 - val_loss: 0.6897 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 38/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6931 - pr_auc: 0.0831 - precision: 0.0385 - recall: 0.0079 - roc_auc: 0.4981 - val_loss: 0.6897 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 39/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6934 - pr_auc: 0.0755 - precision: 0.0345 - recall: 0.0079 - roc_auc: 0.4559 - val_loss: 0.6900 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 40/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 192ms/step - loss: 0.6933 - pr_auc: 0.0807 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4844 - val_loss: 0.6900 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 41/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 176ms/step - loss: 0.6933 - pr_auc: 0.0794 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4758 - val_loss: 0.6902 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 42/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6933 - pr_auc: 0.0734 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4353 - val_loss: 0.6902 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 43/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6933 - pr_auc: 0.0803 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4796 - val_loss: 0.6907 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 44/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 177ms/step - loss: 0.6933 - pr_auc: 0.0830 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4972 - val_loss: 0.6906 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 45/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6932 - pr_auc: 0.0813 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4861 - val_loss: 0.6907 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 46/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6933 - pr_auc: 0.0836 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5011 - val_loss: 0.6909 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 47/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0843 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5054 - val_loss: 0.6906 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 48/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 179ms/step - loss: 0.6933 - pr_auc: 0.0828 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4957 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 49/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0841 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5040 - val_loss: 0.6907 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 50/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6933 - pr_auc: 0.0819 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4896 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 51/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 179ms/step - loss: 0.6932 - pr_auc: 0.0833 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4989 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 52/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0843 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5057 - val_loss: 0.6909 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 52: early stopping
Restoring model weights from the end of the best epoch: 2.
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 91ms/step

Running seed 96

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 20s 229ms/step - loss: 0.6936 - pr_auc: 0.0725 - precision: 0.0270 - recall: 0.0079 - roc_auc: 0.4431 - val_loss: 0.6887 - val_pr_auc: 0.0645 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6224 - val_combined: 0.0452
Epoch 2/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 185ms/step - loss: 0.6933 - pr_auc: 0.0778 - precision: 0.0769 - recall: 0.0236 - roc_auc: 0.4736 - val_loss: 0.6886 - val_pr_auc: 0.0323 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2943 - val_combined: 0.0226
Epoch 3/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 193ms/step - loss: 0.6933 - pr_auc: 0.0799 - precision: 0.0851 - recall: 0.0315 - roc_auc: 0.4840 - val_loss: 0.6887 - val_pr_auc: 0.0704 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6562 - val_combined: 0.0493
Epoch 4/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6931 - pr_auc: 0.0858 - precision: 0.0727 - recall: 0.0315 - roc_auc: 0.5094 - val_loss: 0.6879 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 5/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6935 - pr_auc: 0.0766 - precision: 0.0843 - recall: 0.0551 - roc_auc: 0.4708 - val_loss: 0.6884 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 6/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 178ms/step - loss: 0.6934 - pr_auc: 0.0828 - precision: 0.0588 - recall: 0.0315 - roc_auc: 0.4972 - val_loss: 0.6888 - val_pr_auc: 0.0549 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5521 - val_combined: 0.0385
Epoch 7/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6933 - pr_auc: 0.0766 - precision: 0.0690 - recall: 0.0157 - roc_auc: 0.4660 - val_loss: 0.6891 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 8/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6934 - pr_auc: 0.0748 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4519 - val_loss: 0.6896 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 9/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 185ms/step - loss: 0.6933 - pr_auc: 0.0764 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4561 - val_loss: 0.6897 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 10/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 195ms/step - loss: 0.6932 - pr_auc: 0.0776 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4669 - val_loss: 0.6895 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 11/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0817 - precision: 0.2000 - recall: 0.0079 - roc_auc: 0.4902 - val_loss: 0.6900 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 12/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6932 - pr_auc: 0.0807 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4841 - val_loss: 0.6899 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 13/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 177ms/step - loss: 0.6932 - pr_auc: 0.0813 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4880 - val_loss: 0.6897 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 14/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 211ms/step - loss: 0.6933 - pr_auc: 0.0770 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4612 - val_loss: 0.6899 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 15/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6932 - pr_auc: 0.0771 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4622 - val_loss: 0.6900 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 16/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 190ms/step - loss: 0.6933 - pr_auc: 0.0772 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4626 - val_loss: 0.6897 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 17/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 189ms/step - loss: 0.6932 - pr_auc: 0.0773 - precision: 0.1538 - recall: 0.0157 - roc_auc: 0.4648 - val_loss: 0.6897 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 18/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0804 - precision: 0.5000 - recall: 0.0157 - roc_auc: 0.4815 - val_loss: 0.6897 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 19/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6933 - pr_auc: 0.0775 - precision: 0.2000 - recall: 0.0079 - roc_auc: 0.4644 - val_loss: 0.6893 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 20/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 178ms/step - loss: 0.6933 - pr_auc: 0.0740 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4404 - val_loss: 0.6891 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 21/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6931 - pr_auc: 0.0769 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4608 - val_loss: 0.6892 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 22/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6933 - pr_auc: 0.0722 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4387 - val_loss: 0.6889 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 23/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 191ms/step - loss: 0.6933 - pr_auc: 0.0753 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4519 - val_loss: 0.6892 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 24/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 189ms/step - loss: 0.6933 - pr_auc: 0.0687 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4024 - val_loss: 0.6890 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 25/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0778 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4636 - val_loss: 0.6891 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 26/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0797 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4761 - val_loss: 0.6890 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 27/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 178ms/step - loss: 0.6933 - pr_auc: 0.0700 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4175 - val_loss: 0.6891 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 28/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6932 - pr_auc: 0.0776 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4625 - val_loss: 0.6892 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 29/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0704 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4160 - val_loss: 0.6890 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 30/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 184ms/step - loss: 0.6932 - pr_auc: 0.0794 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4758 - val_loss: 0.6891 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 31/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 196ms/step - loss: 0.6932 - pr_auc: 0.0820 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4920 - val_loss: 0.6890 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 32/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0739 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4426 - val_loss: 0.6889 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 33/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0672 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.3953 - val_loss: 0.6889 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 34/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 178ms/step - loss: 0.6932 - pr_auc: 0.0761 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4558 - val_loss: 0.6889 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 35/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6932 - pr_auc: 0.0751 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4497 - val_loss: 0.6890 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 36/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0807 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4841 - val_loss: 0.6888 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 37/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 183ms/step - loss: 0.6932 - pr_auc: 0.0727 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4354 - val_loss: 0.6890 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 38/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 198ms/step - loss: 0.6932 - pr_auc: 0.0730 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4332 - val_loss: 0.6892 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 39/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0748 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4461 - val_loss: 0.6892 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 40/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 199ms/step - loss: 0.6932 - pr_auc: 0.0753 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4460 - val_loss: 0.6892 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 41/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 179ms/step - loss: 0.6932 - pr_auc: 0.0821 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4915 - val_loss: 0.6892 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 42/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0752 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4479 - val_loss: 0.6891 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 43/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0771 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4615 - val_loss: 0.6891 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 44/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 179ms/step - loss: 0.6932 - pr_auc: 0.0737 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4389 - val_loss: 0.6890 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 45/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0636 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.3721 - val_loss: 0.6888 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 46/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0644 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.3796 - val_loss: 0.6889 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 47/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0665 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.3950 - val_loss: 0.6888 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 48/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 178ms/step - loss: 0.6932 - pr_auc: 0.0683 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4151 - val_loss: 0.6887 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 49/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0729 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4449 - val_loss: 0.6886 - val_pr_auc: 0.0312 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.2630 - val_combined: 0.0218
Epoch 50/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6932 - pr_auc: 0.0800 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4850 - val_loss: 0.6887 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 51/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 178ms/step - loss: 0.6932 - pr_auc: 0.0695 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4245 - val_loss: 0.6888 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 52/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 201ms/step - loss: 0.6932 - pr_auc: 0.0756 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4595 - val_loss: 0.6886 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 53/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0757 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4643 - val_loss: 0.6884 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 53: early stopping
Restoring model weights from the end of the best epoch: 3.
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 92ms/step

Running seed 146

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 19s 215ms/step - loss: 0.6933 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6917 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 2/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 189ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6916 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 3/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6918 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 4/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.1111 - recall: 0.0236 - roc_auc: 0.5000 - val_loss: 0.6918 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 5/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 8s 176ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0417 - recall: 0.0079 - roc_auc: 0.5000 - val_loss: 0.6917 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 6/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.1207 - recall: 0.0551 - roc_auc: 0.5000 - val_loss: 0.6922 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 7/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6933 - pr_auc: 0.0834 - precision: 0.0330 - recall: 0.0236 - roc_auc: 0.5000 - val_loss: 0.6921 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 8/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 187ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6918 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 9/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 192ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6917 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 10/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6921 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 11/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6918 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 12/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 178ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6916 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 13/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6916 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 14/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6918 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 15/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 185ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6913 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 16/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 192ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0667 - recall: 0.0079 - roc_auc: 0.5000 - val_loss: 0.6915 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 17/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0836 - precision: 0.0435 - recall: 0.0079 - roc_auc: 0.5007 - val_loss: 0.6915 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 18/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0370 - recall: 0.0079 - roc_auc: 0.5000 - val_loss: 0.6920 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 19/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 177ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0270 - recall: 0.0079 - roc_auc: 0.5000 - val_loss: 0.6913 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 20/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6910 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 21/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0830 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4971 - val_loss: 0.6913 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 22/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 187ms/step - loss: 0.6933 - pr_auc: 0.0811 - precision: 0.1429 - recall: 0.0079 - roc_auc: 0.4843 - val_loss: 0.6915 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 23/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 193ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.5000 - recall: 0.0079 - roc_auc: 0.5000 - val_loss: 0.6915 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 24/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6913 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 25/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6913 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 26/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 177ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6910 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 27/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6912 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 28/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0837 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5014 - val_loss: 0.6909 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 29/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 180ms/step - loss: 0.6932 - pr_auc: 0.0814 - precision: 0.0526 - recall: 0.0079 - roc_auc: 0.4868 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 30/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 201ms/step - loss: 0.6932 - pr_auc: 0.0809 - precision: 0.0769 - recall: 0.0157 - roc_auc: 0.4832 - val_loss: 0.6909 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 31/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6932 - pr_auc: 0.0830 - precision: 0.2000 - recall: 0.0079 - roc_auc: 0.4972 - val_loss: 0.6911 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 32/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6933 - pr_auc: 0.0825 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4936 - val_loss: 0.6911 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 33/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 180ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 34/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6931 - pr_auc: 0.0838 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5025 - val_loss: 0.6903 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 35/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6933 - pr_auc: 0.0815 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4875 - val_loss: 0.6909 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 36/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 178ms/step - loss: 0.6932 - pr_auc: 0.0838 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5022 - val_loss: 0.6904 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 37/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.6933 - pr_auc: 0.0823 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4925 - val_loss: 0.6911 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 38/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6907 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 39/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 197ms/step - loss: 0.6932 - pr_auc: 0.0830 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4971 - val_loss: 0.6906 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 40/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 183ms/step - loss: 0.6932 - pr_auc: 0.0831 - precision: 0.1111 - recall: 0.0079 - roc_auc: 0.4975 - val_loss: 0.6909 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 41/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.5000 - val_loss: 0.6909 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 42/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0832 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4982 - val_loss: 0.6906 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 43/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 178ms/step - loss: 0.6932 - pr_auc: 0.0830 - precision: 0.0769 - recall: 0.0079 - roc_auc: 0.4968 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 44/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0833 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4993 - val_loss: 0.6906 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 45/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6932 - pr_auc: 0.0821 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4914 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 46/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 199ms/step - loss: 0.6932 - pr_auc: 0.0841 - precision: 0.0769 - recall: 0.0157 - roc_auc: 0.5043 - val_loss: 0.6904 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 47/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 182ms/step - loss: 0.6932 - pr_auc: 0.0826 - precision: 0.0566 - recall: 0.0236 - roc_auc: 0.4943 - val_loss: 0.6905 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 48/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0836 - precision: 0.0849 - recall: 0.0709 - roc_auc: 0.5007 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 49/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0303 - recall: 0.0157 - roc_auc: 0.4996 - val_loss: 0.6909 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 50/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 178ms/step - loss: 0.6932 - pr_auc: 0.0837 - precision: 0.0714 - recall: 0.0315 - roc_auc: 0.5018 - val_loss: 0.6911 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 51/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0838 - precision: 0.1034 - recall: 0.0472 - roc_auc: 0.5025 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 51: early stopping
Restoring model weights from the end of the best epoch: 1.
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 91ms/step

Running seed 162

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 20s 230ms/step - loss: 0.6933 - pr_auc: 0.0834 - precision: 0.0569 - recall: 0.2756 - roc_auc: 0.5000 - val_loss: 0.6933 - val_pr_auc: 0.0495 - val_precision: 0.0495 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3347
Epoch 2/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 187ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0660 - recall: 0.3937 - roc_auc: 0.5000 - val_loss: 0.6933 - val_pr_auc: 0.0495 - val_precision: 0.0495 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3347
Epoch 3/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 191ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0809 - recall: 0.5827 - roc_auc: 0.5000 - val_loss: 0.6937 - val_pr_auc: 0.0495 - val_precision: 0.0495 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3347
Epoch 4/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6933 - pr_auc: 0.0834 - precision: 0.0758 - recall: 0.5591 - roc_auc: 0.5000 - val_loss: 0.6928 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 5/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6934 - pr_auc: 0.0834 - precision: 0.0495 - recall: 0.2283 - roc_auc: 0.5000 - val_loss: 0.6918 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 6/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 179ms/step - loss: 0.6933 - pr_auc: 0.0834 - precision: 0.0526 - recall: 0.1102 - roc_auc: 0.5000 - val_loss: 0.6919 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 7/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0615 - recall: 0.0630 - roc_auc: 0.5000 - val_loss: 0.6915 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 8/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6933 - pr_auc: 0.0834 - precision: 0.0488 - recall: 0.0157 - roc_auc: 0.5000 - val_loss: 0.6914 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 9/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 193ms/step - loss: 0.6932 - pr_auc: 0.0835 - precision: 0.0845 - recall: 0.0472 - roc_auc: 0.5004 - val_loss: 0.6914 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 10/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 188ms/step - loss: 0.6933 - pr_auc: 0.0835 - precision: 0.0357 - recall: 0.0315 - roc_auc: 0.5004 - val_loss: 0.6913 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 11/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0836 - precision: 0.1139 - recall: 0.0709 - roc_auc: 0.5007 - val_loss: 0.6911 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 12/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0217 - recall: 0.0079 - roc_auc: 0.5000 - val_loss: 0.6909 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 13/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 179ms/step - loss: 0.6932 - pr_auc: 0.0832 - precision: 0.0787 - recall: 0.1102 - roc_auc: 0.4982 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 14/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6932 - pr_auc: 0.0842 - precision: 0.0833 - recall: 0.1260 - roc_auc: 0.5050 - val_loss: 0.6903 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 15/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.6931 - pr_auc: 0.0814 - precision: 0.0772 - recall: 0.1890 - roc_auc: 0.5003 - val_loss: 0.6904 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 16/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 191ms/step - loss: 0.6933 - pr_auc: 0.0837 - precision: 0.0613 - recall: 0.1024 - roc_auc: 0.5084 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 17/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 190ms/step - loss: 0.6933 - pr_auc: 0.0849 - precision: 0.0592 - recall: 0.0709 - roc_auc: 0.5094 - val_loss: 0.6910 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 18/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6930 - pr_auc: 0.0852 - precision: 0.1074 - recall: 0.1260 - roc_auc: 0.5108 - val_loss: 0.6911 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 19/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6931 - pr_auc: 0.0837 - precision: 0.0821 - recall: 0.2126 - roc_auc: 0.5019 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 20/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 180ms/step - loss: 0.6933 - pr_auc: 0.0787 - precision: 0.0717 - recall: 0.1575 - roc_auc: 0.4711 - val_loss: 0.6904 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 21/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6933 - pr_auc: 0.0832 - precision: 0.0625 - recall: 0.1102 - roc_auc: 0.4983 - val_loss: 0.6903 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 22/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6932 - pr_auc: 0.0863 - precision: 0.0556 - recall: 0.0945 - roc_auc: 0.5191 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 23/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 195ms/step - loss: 0.6933 - pr_auc: 0.0833 - precision: 0.0758 - recall: 0.1654 - roc_auc: 0.4990 - val_loss: 0.6911 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 24/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 188ms/step - loss: 0.6932 - pr_auc: 0.0809 - precision: 0.0922 - recall: 0.1575 - roc_auc: 0.4840 - val_loss: 0.6903 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 25/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6933 - pr_auc: 0.0792 - precision: 0.0596 - recall: 0.1024 - roc_auc: 0.4796 - val_loss: 0.6898 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 26/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6929 - pr_auc: 0.0859 - precision: 0.1150 - recall: 0.2047 - roc_auc: 0.5150 - val_loss: 0.6897 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 27/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 179ms/step - loss: 0.6933 - pr_auc: 0.0761 - precision: 0.0748 - recall: 0.1496 - roc_auc: 0.4654 - val_loss: 0.6898 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 28/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.6933 - pr_auc: 0.0809 - precision: 0.0708 - recall: 0.1181 - roc_auc: 0.4885 - val_loss: 0.6900 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 29/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6932 - pr_auc: 0.0828 - precision: 0.0725 - recall: 0.1496 - roc_auc: 0.4976 - val_loss: 0.6905 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 30/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 200ms/step - loss: 0.6932 - pr_auc: 0.0849 - precision: 0.0556 - recall: 0.1339 - roc_auc: 0.5109 - val_loss: 0.6903 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 31/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 182ms/step - loss: 0.6934 - pr_auc: 0.0803 - precision: 0.0615 - recall: 0.1181 - roc_auc: 0.4823 - val_loss: 0.6903 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 32/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6932 - pr_auc: 0.0829 - precision: 0.0841 - recall: 0.1417 - roc_auc: 0.4965 - val_loss: 0.6909 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 33/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6932 - pr_auc: 0.0850 - precision: 0.0721 - recall: 0.1181 - roc_auc: 0.5094 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 34/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 187ms/step - loss: 0.6933 - pr_auc: 0.0803 - precision: 0.0622 - recall: 0.1181 - roc_auc: 0.4800 - val_loss: 0.6914 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 35/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 195ms/step - loss: 0.6932 - pr_auc: 0.0834 - precision: 0.0760 - recall: 0.1496 - roc_auc: 0.4997 - val_loss: 0.6910 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 36/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6933 - pr_auc: 0.0804 - precision: 0.0747 - recall: 0.1654 - roc_auc: 0.4811 - val_loss: 0.6909 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 37/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6932 - pr_auc: 0.0839 - precision: 0.0687 - recall: 0.1260 - roc_auc: 0.5026 - val_loss: 0.6907 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 38/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 180ms/step - loss: 0.6930 - pr_auc: 0.0859 - precision: 0.1037 - recall: 0.2205 - roc_auc: 0.5163 - val_loss: 0.6904 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 39/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6933 - pr_auc: 0.0787 - precision: 0.0586 - recall: 0.1417 - roc_auc: 0.4757 - val_loss: 0.6902 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 40/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6932 - pr_auc: 0.0833 - precision: 0.0848 - recall: 0.2283 - roc_auc: 0.5062 - val_loss: 0.6900 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 41/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 188ms/step - loss: 0.6932 - pr_auc: 0.0926 - precision: 0.0735 - recall: 0.1811 - roc_auc: 0.5199 - val_loss: 0.6907 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 42/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 196ms/step - loss: 0.6933 - pr_auc: 0.0806 - precision: 0.0418 - recall: 0.0945 - roc_auc: 0.4822 - val_loss: 0.6912 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 43/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 205ms/step - loss: 0.6932 - pr_auc: 0.0855 - precision: 0.0742 - recall: 0.1339 - roc_auc: 0.5122 - val_loss: 0.6913 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 44/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6932 - pr_auc: 0.0823 - precision: 0.0755 - recall: 0.1260 - roc_auc: 0.4933 - val_loss: 0.6911 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 45/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 180ms/step - loss: 0.6932 - pr_auc: 0.0823 - precision: 0.0711 - recall: 0.1260 - roc_auc: 0.4933 - val_loss: 0.6906 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 46/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6932 - pr_auc: 0.0836 - precision: 0.0712 - recall: 0.1575 - roc_auc: 0.5008 - val_loss: 0.6909 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 47/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6932 - pr_auc: 0.0845 - precision: 0.0909 - recall: 0.2047 - roc_auc: 0.5062 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 48/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 9s 189ms/step - loss: 0.6932 - pr_auc: 0.0832 - precision: 0.1101 - recall: 0.1969 - roc_auc: 0.4987 - val_loss: 0.6908 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 49/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 196ms/step - loss: 0.6932 - pr_auc: 0.0869 - precision: 0.0427 - recall: 0.0787 - roc_auc: 0.5205 - val_loss: 0.6912 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 50/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6931 - pr_auc: 0.0855 - precision: 0.0644 - recall: 0.1496 - roc_auc: 0.5126 - val_loss: 0.6914 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 51/200
48/48 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6932 - pr_auc: 0.0814 - precision: 0.0880 - recall: 0.1969 - roc_auc: 0.4876 - val_loss: 0.6911 - val_pr_auc: 0.0495 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5000 - val_combined: 0.0347
Epoch 51: early stopping
Restoring model weights from the end of the best epoch: 1.
14/14 ━━━━━━━━━━━━━━━━━━━━ 2s 91ms/step

In [ ]:
df_robustness_bench_2 = pd.DataFrame(robustness_results_bench_2)
df_robustness_bench_2 = pd.concat([df_robustness_bench_2,pd.DataFrame({'seed': 23,
                                                                       'recall': 1,
                                                                       'f1': 0.11,
                                                                       'roc_auc': 0.69,
                                                                       'tn': 0,
                                                                       'fp': 415,
                                                                       'fn': 0,
                                                                       'tp': 25},
                                                                      index=[0])], ignore_index=True) #add results from baseline model
df_robustness_bench_2

   seed  recall        f1   roc_auc   tn   fp  fn  tp
0    38     1.0  0.107527  0.276145    0  415   0  25
1    60     0.0  0.000000  0.725494  415    0  25   0
2    96     0.0  0.000000  0.703373  415    0  25   0
3   146     0.0  0.000000  0.272964  415    0  25   0
4   162     1.0  0.107527  0.297060    0  415   0  25
5    23     1.0  0.110000  0.690000    0  415   0  25

```python
df_robustness_bench_2.to_csv("df_robustness_bench_2.csv", index=True)
files.download("df_robustness_bench_2.csv")
df_robustness_bench_2.to_parquet("df_robustness_bench_2.parquet", index=True)
files.download("df_robustness_bench_2.parquet")
```

In [ ]:
#df_robustness_bench_2 = import_data(file_path)

In [ ]:
df_robustness_bench_2 = df_robustness_bench_2.set_index('seed')[['recall',	'f1',	'roc_auc']].sort_index()
df_robustness_bench_2 = df_robustness_bench_2.rename(columns={'recall':'Recall',	'f1':'F1-Score',	'roc_auc':'ROC-AUC'})

In [ ]:
df_robustness_bench_2.round(2)

      Recall  F1-Score  ROC-AUC
seed
23       1.0      0.11     0.69
38       1.0      0.11     0.28
60       0.0      0.00     0.73
96       0.0      0.00     0.70
146      0.0      0.00     0.27
162      1.0      0.11     0.30

In [ ]:
df_robustness_bench_2.mean().round(2).rename('mean')

Recall      0.50
F1-Score    0.05
ROC-AUC     0.49
Name: mean, dtype: float64

In [ ]:
df_robustness_bench_2.std().round(2).rename('std')

Recall      0.55
F1-Score    0.06
ROC-AUC     0.23
Name: std, dtype: float64