# Appendix C2. Disaggregated Sub-Indices: Sensitivity of LSTM Results to Random Initialization

In [ ]:
# --- ENV FIRST ---
import os
os.environ["TF_DETERMINISTIC_OPS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["TF_NUM_INTRAOP_THREADS"] = "1"
os.environ["TF_NUM_INTEROP_THREADS"] = "1"
# --- IMPORTS ---
import random
import numpy as np
import tensorflow as tf
# --- TF CONFIG ---
tf.config.threading.set_inter_op_parallelism_threads(1)
tf.config.threading.set_intra_op_parallelism_threads(1)
tf.config.set_visible_devices([], 'GPU')
# --- RESET ---
tf.keras.backend.clear_session()

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import recall_score, f1_score, roc_auc_score, confusion_matrix, accuracy_score, roc_curve
import itertools
from sklearn.utils.class_weight import compute_class_weight
from tensorflow import keras
from tensorflow.keras import layers
try:
  import keras_tuner as kt
except:
  !pip install keras-tuner
  import keras_tuner as kt
from google.colab import files
from google.colab import drive
import pandas as pd
import io
import matplotlib.pyplot as plt
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.80.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.5.20)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 1.1 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

Build a function to import data to the notebook.

In [ ]:
def import_data(file_path):
  try:
    drive.mount('/content/drive', force_remount=True)
    # Check if file exists
    if os.path.exists(file_path):
      df = pd.read_parquet(file_path)
      print(f"Loaded dataframe from Drive ({file_path})")
    else:
      raise FileNotFoundError(f"File not found at {file_path}")

  except Exception as e:
    print(f"Drive not available or file missing: {e}")
    print("Please upload dataframe manually.")
    uploaded = files.upload()

    # Automatically read the uploaded file
    file_name = list(uploaded.keys())[0]  # pick the first uploaded file
    try:
      df = pd.read_parquet(io.BytesIO(uploaded[file_name]))
    except:
      print("Wrong file extension. Parquet file required.")
    print(f"Loaded {file_name} from manual upload.")
    return df

Build a function to fit a given model on training data and output out-of-sample predictions, class probabilities, as well as the following metrics estimated on test data:
- Recall
- F1 score
- ROC AUC
- Confusion Matrix.

In [ ]:
def train_classifier(model, X_train, y_train, X_test, y_test, X_val=False, y_val=False, threshold=0.5, early_stopping=False):
  is_keras = hasattr(model, "fit") and hasattr(model, "predict") and not hasattr(model, "predict_proba")
  if is_keras:
    if early_stopping:
      model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, class_weight=class_weight, validation_data=(X_val, y_val), shuffle=False, callbacks=[combined_metric, es])
    else:
      model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, class_weight=class_weight, validation_data=(X_val, y_val), shuffle=False)
    y_score = model.predict(X_test).ravel()
    y_pred = (y_score >= threshold).astype(int)
  else:
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_score = model.predict_proba(X_test)[:, 1]

  # Output Following Metrics:
  recall = recall_score(y_test, y_pred)
  f1 = f1_score(y_test, y_pred)
  roc_auc = roc_auc_score(y_test, y_score)
  cm = confusion_matrix(y_test, y_pred)

  return recall, f1, roc_auc, cm, y_score, y_pred

Import the df_sse.parquet file, containing the Systemic Stress Events (the target variable) data, available in the <a href='https://github.com/SebastianoDenegri/vietnam-systemic-risk-index/tree/main/data/machine_learning'>data/machine_learning</a> subdirectory.

In [ ]:
file_path = "..."
df_sse = import_data(file_path)

Drive not available or file missing: Error: credential propagation was unsuccessful
Please upload dataframe manually.

Saving df_sse.parquet to df_sse.parquet
Loaded df_sse.parquet from manual upload.

Import the parquet file with the 5 disaggregated sub-indices already normalized via ECDF, risk_ecdf.parquet, available in the <a href='https://github.com/SebastianoDenegri/vietnam-systemic-risk-index/tree/main/data/machine_learning'>data/machine_learning</a> subdirectory.

In [ ]:
risk_ecdf = import_data(file_path)

Drive not available or file missing: Error: credential propagation was unsuccessful
Please upload dataframe manually.

Saving risk_ecdf.parquet to risk_ecdf.parquet
Loaded risk_ecdf.parquet from manual upload.

Build a dataframe with the 5 disaggregate indicators (predictors) and the Systemic Stress Events variable (target).  
The data sets are defined as follows:
- Training data: until 1st March 2023 (excluded)
- Validation data: from 1st March 2023 until 31st March 2024
- Test data: from 1st April 2024  

We apply a 20-day purge period between training and validation as well as validation and test sets.  
Sequence length: 60 days (a quarter of trading activities).

In [ ]:
# build a dataframe with the 5 disaggregate indicators (predictors) and the Systemic Stress Events variable (target)
df_bench = pd.concat([risk_ecdf, df_sse['systemic_stress_event']], axis=1, join='inner').dropna()
# align the dataframe at the same starting date of the VSRI
df_bench = df_bench.loc['2017-01-03':].dropna()

In [ ]:
df_bench.shape

(2285, 6)

In [ ]:
# split data in training and test set and apply purging
split_date = "2024-03-31"
purge = 20
train_bench = df_bench.loc[:split_date].iloc[:-purge]
test_bench  = df_bench[df_bench.index > split_date]

X_train_bench = train_bench[["VGCI",	"VMFI",	"VFTI",	"VTRI",	"VMII"]]
y_train_bench = train_bench["systemic_stress_event"]
X_test_bench  = test_bench[["VGCI",	"VMFI",	"VFTI",	"VTRI",	"VMII"]]
y_test_bench  = test_bench["systemic_stress_event"]

In [ ]:
timesteps = 60
split_idx = pd.Timestamp("2023-03-01")
X_train_lstm_bench = X_train_bench[X_train_bench.index < split_idx].iloc[:-purge]
y_train_lstm_bench = y_train_bench[y_train_bench.index < split_idx].iloc[:-purge]
X_val_lstm_bench = X_train_bench.loc[split_idx:]
y_val_lstm_bench = y_train_bench.loc[split_idx:]

X_train_values_bench = X_train_lstm_bench.values
y_train_values_bench = y_train_lstm_bench.values
X_test_values_bench = X_test_bench.values
y_test_values_bench = y_test_bench.values
X_val_values_bench = X_val_lstm_bench.values
y_val_values_bench = y_val_lstm_bench.values
X_train_seq_bench = []
y_train_seq_bench = []
X_test_seq_bench = []
y_test_seq_bench = []
X_val_seq_bench = []
y_val_seq_bench = []
for i in range(timesteps, len(X_train_values_bench)):
  X_train_seq_bench.append(X_train_values_bench[i - timesteps:i])
  y_train_seq_bench.append(y_train_values_bench[i])
for i in range(timesteps, len(X_test_values_bench)):
  X_test_seq_bench.append(X_test_values_bench[i - timesteps:i])
  y_test_seq_bench.append(y_test_values_bench[i])
for i in range(timesteps, len(X_val_values_bench)):
  X_val_seq_bench.append(X_val_values_bench[i - timesteps:i])
  y_val_seq_bench.append(y_val_values_bench[i])

X_train_seq_bench = np.array(X_train_seq_bench)
y_train_seq_bench = np.array(y_train_seq_bench)
X_test_seq_bench = np.array(X_test_seq_bench)
y_test_seq_bench = np.array(y_test_seq_bench)
X_val_seq_bench = np.array(X_val_seq_bench)
y_val_seq_bench = np.array(y_val_seq_bench)

In [ ]:
print(X_train_seq_bench.shape,
      y_train_seq_bench.shape,
      X_val_seq_bench.shape,
      y_val_seq_bench.shape,
      X_test_seq_bench.shape,
      y_test_seq_bench.shape)

(1457, 60, 5) (1457,) (192, 60, 5) (192,) (416, 60, 5) (416,)

In [ ]:
class CombinedMetric(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs=None):
    logs = logs or {}
    recall = logs.get("val_recall", 0)
    pr_auc = logs.get("val_pr_auc", 0)
    logs["val_combined"] = 0.3 * recall + 0.7 * pr_auc

In [ ]:
classes = np.unique(y_train_seq_bench)
weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train_seq_bench)
class_weight = dict(zip(classes, weights))
epochs=200
batch_size=32

In [ ]:
seeds = [38, 60, 96, 146, 162]
robustness_results_bench = []
input_shape = X_train_seq_bench.shape[1:]

In [ ]:
for seed in seeds:
  os.environ["PYTHONHASHSEED"] = str(seed)
  print(f"\nRunning seed {seed}")
  tf.keras.backend.clear_session()
  random.seed(seed)
  np.random.seed(seed)
  tf.keras.utils.set_random_seed(seed)

  # LSTM MODEL
  lstm_model_bench = keras.Sequential()
  lstm_model_bench.add(layers.LSTM(128, return_sequences=True, input_shape=input_shape))
  lstm_model_bench.add(layers.Dropout(0.5))
  lstm_model_bench.add(layers.LSTM(128, return_sequences=True))
  lstm_model_bench.add(layers.LSTM(16, return_sequences=True))
  lstm_model_bench.add(layers.LSTM(8, return_sequences=True))
  lstm_model_bench.add(layers.Dropout(0.3))
  lstm_model_bench.add(layers.LSTM(8, return_sequences=False))
  lstm_model_bench.add(layers.Dropout(0.3))
  # Dense layers
  lstm_model_bench.add(layers.Dense(16, activation="relu"))
  lstm_model_bench.add(layers.Dense(1, activation="sigmoid"))
  # Compile
  lstm_model_bench.compile(optimizer=keras.optimizers.Adam(learning_rate=0.0001),
                           loss="binary_crossentropy",
                           metrics=[keras.metrics.AUC(name="pr_auc", curve="PR"),
                                    keras.metrics.AUC(name="roc_auc", curve="ROC"),
                                    tf.keras.metrics.Recall(name="recall"),
                                    tf.keras.metrics.Precision(name="precision")])

  combined_metric = CombinedMetric()
  es = tf.keras.callbacks.EarlyStopping(monitor="val_combined",
                                        mode="max",
                                        patience=50,
                                        restore_best_weights=True,
                                        verbose=1)

  # TRAIN
  lstm_results_bench = train_classifier(lstm_model_bench, X_train_seq_bench, y_train_seq_bench, X_test_seq_bench, y_test_seq_bench, X_val=X_val_seq_bench, y_val=y_val_seq_bench, early_stopping=True)
  lstm_recall_bench, lstm_f1_bench, lstm_roc_auc_bench, lstm_cm_bench, lstm_probs_bench, lstm_preds_bench = lstm_results_bench
  # Store results
  robustness_results_bench.append({"seed": seed,
                                   "recall": lstm_recall_bench,
                                   "f1": lstm_f1_bench,
                                   "roc_auc": lstm_roc_auc_bench,
                                   "tn": lstm_cm_bench[0,0],
                                   "fp": lstm_cm_bench[0,1],
                                   "fn": lstm_cm_bench[1,0],
                                   "tp": lstm_cm_bench[1,1]})

Running seed 38

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 26s 230ms/step - loss: 0.6944 - pr_auc: 0.0657 - precision: 0.0781 - recall: 0.9741 - roc_auc: 0.4400 - val_loss: 0.7017 - val_pr_auc: 0.0521 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5000 - val_combined: 0.3365
Epoch 2/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 197ms/step - loss: 0.6919 - pr_auc: 0.1137 - precision: 0.0806 - recall: 1.0000 - roc_auc: 0.5816 - val_loss: 0.7037 - val_pr_auc: 0.0588 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.5885 - val_combined: 0.3412
Epoch 3/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 193ms/step - loss: 0.6903 - pr_auc: 0.1571 - precision: 0.0801 - recall: 0.9914 - roc_auc: 0.6002 - val_loss: 0.7061 - val_pr_auc: 0.0799 - val_precision: 0.0529 - val_recall: 1.0000 - val_roc_auc: 0.7033 - val_combined: 0.3560
Epoch 4/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6887 - pr_auc: 0.1350 - precision: 0.0811 - recall: 1.0000 - roc_auc: 0.6450 - val_loss: 0.7170 - val_pr_auc: 0.0701 - val_precision: 0.0578 - val_recall: 1.0000 - val_roc_auc: 0.6577 - val_combined: 0.3491
Epoch 5/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.6873 - pr_auc: 0.1478 - precision: 0.0808 - recall: 0.9828 - roc_auc: 0.6133 - val_loss: 0.7144 - val_pr_auc: 0.0895 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.7396 - val_combined: 0.3627
Epoch 6/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 183ms/step - loss: 0.6824 - pr_auc: 0.2399 - precision: 0.0806 - recall: 0.9914 - roc_auc: 0.7056 - val_loss: 0.7229 - val_pr_auc: 0.0919 - val_precision: 0.0529 - val_recall: 1.0000 - val_roc_auc: 0.7462 - val_combined: 0.3643
Epoch 7/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 205ms/step - loss: 0.6781 - pr_auc: 0.2115 - precision: 0.0831 - recall: 1.0000 - roc_auc: 0.7061 - val_loss: 0.7346 - val_pr_auc: 0.0994 - val_precision: 0.0529 - val_recall: 1.0000 - val_roc_auc: 0.7692 - val_combined: 0.3696
Epoch 8/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 205ms/step - loss: 0.6739 - pr_auc: 0.2104 - precision: 0.0824 - recall: 0.9914 - roc_auc: 0.7064 - val_loss: 0.7326 - val_pr_auc: 0.1458 - val_precision: 0.0541 - val_recall: 1.0000 - val_roc_auc: 0.8423 - val_combined: 0.4021
Epoch 9/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 190ms/step - loss: 0.6667 - pr_auc: 0.2148 - precision: 0.0855 - recall: 0.9828 - roc_auc: 0.7440 - val_loss: 0.7347 - val_pr_auc: 0.1898 - val_precision: 0.0562 - val_recall: 1.0000 - val_roc_auc: 0.8832 - val_combined: 0.4329
Epoch 10/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 200ms/step - loss: 0.6606 - pr_auc: 0.2132 - precision: 0.0881 - recall: 0.9655 - roc_auc: 0.7391 - val_loss: 0.7386 - val_pr_auc: 0.1756 - val_precision: 0.0662 - val_recall: 1.0000 - val_roc_auc: 0.8755 - val_combined: 0.4229
Epoch 11/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 207ms/step - loss: 0.6540 - pr_auc: 0.2383 - precision: 0.0918 - recall: 0.9052 - roc_auc: 0.7479 - val_loss: 0.7565 - val_pr_auc: 0.1545 - val_precision: 0.0943 - val_recall: 1.0000 - val_roc_auc: 0.8549 - val_combined: 0.4081
Epoch 12/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 206ms/step - loss: 0.6557 - pr_auc: 0.2279 - precision: 0.0889 - recall: 0.8534 - roc_auc: 0.7203 - val_loss: 0.7322 - val_pr_auc: 0.1860 - val_precision: 0.1299 - val_recall: 1.0000 - val_roc_auc: 0.8843 - val_combined: 0.4302
Epoch 13/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6494 - pr_auc: 0.2347 - precision: 0.0898 - recall: 0.8621 - roc_auc: 0.7336 - val_loss: 0.7507 - val_pr_auc: 0.1642 - val_precision: 0.1149 - val_recall: 1.0000 - val_roc_auc: 0.8659 - val_combined: 0.4150
Epoch 14/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6435 - pr_auc: 0.2590 - precision: 0.0991 - recall: 0.7931 - roc_auc: 0.7252 - val_loss: 0.7324 - val_pr_auc: 0.3990 - val_precision: 0.1493 - val_recall: 1.0000 - val_roc_auc: 0.9082 - val_combined: 0.5793
Epoch 15/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.6460 - pr_auc: 0.2420 - precision: 0.1051 - recall: 0.7586 - roc_auc: 0.7280 - val_loss: 0.7680 - val_pr_auc: 0.1839 - val_precision: 0.1136 - val_recall: 1.0000 - val_roc_auc: 0.8783 - val_combined: 0.4288
Epoch 16/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 199ms/step - loss: 0.6457 - pr_auc: 0.2195 - precision: 0.1126 - recall: 0.8103 - roc_auc: 0.7337 - val_loss: 0.7470 - val_pr_auc: 0.4625 - val_precision: 0.1408 - val_recall: 1.0000 - val_roc_auc: 0.9093 - val_combined: 0.6238
Epoch 17/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 189ms/step - loss: 0.6383 - pr_auc: 0.2445 - precision: 0.1194 - recall: 0.7759 - roc_auc: 0.7557 - val_loss: 0.7545 - val_pr_auc: 0.1797 - val_precision: 0.1389 - val_recall: 1.0000 - val_roc_auc: 0.8706 - val_combined: 0.4258
Epoch 18/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.6429 - pr_auc: 0.2144 - precision: 0.1234 - recall: 0.7500 - roc_auc: 0.7431 - val_loss: 0.7080 - val_pr_auc: 0.2750 - val_precision: 0.2045 - val_recall: 0.9000 - val_roc_auc: 0.8646 - val_combined: 0.4625
Epoch 19/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 211ms/step - loss: 0.6470 - pr_auc: 0.2035 - precision: 0.1331 - recall: 0.6379 - roc_auc: 0.6841 - val_loss: 0.7632 - val_pr_auc: 0.1525 - val_precision: 0.1370 - val_recall: 1.0000 - val_roc_auc: 0.8503 - val_combined: 0.4067
Epoch 20/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 182ms/step - loss: 0.6348 - pr_auc: 0.2294 - precision: 0.1486 - recall: 0.7328 - roc_auc: 0.7499 - val_loss: 0.7521 - val_pr_auc: 0.4326 - val_precision: 0.1613 - val_recall: 1.0000 - val_roc_auc: 0.8819 - val_combined: 0.6028
Epoch 21/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6311 - pr_auc: 0.2401 - precision: 0.1609 - recall: 0.6810 - roc_auc: 0.7363 - val_loss: 0.7537 - val_pr_auc: 0.1717 - val_precision: 0.1667 - val_recall: 1.0000 - val_roc_auc: 0.8670 - val_combined: 0.4202
Epoch 22/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.6271 - pr_auc: 0.2396 - precision: 0.1772 - recall: 0.7241 - roc_auc: 0.7612 - val_loss: 0.7091 - val_pr_auc: 0.2207 - val_precision: 0.1750 - val_recall: 0.7000 - val_roc_auc: 0.8896 - val_combined: 0.3645
Epoch 23/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 188ms/step - loss: 0.6386 - pr_auc: 0.2135 - precision: 0.1711 - recall: 0.6034 - roc_auc: 0.7371 - val_loss: 0.7956 - val_pr_auc: 0.1653 - val_precision: 0.1333 - val_recall: 1.0000 - val_roc_auc: 0.8651 - val_combined: 0.4157
Epoch 24/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 203ms/step - loss: 0.6211 - pr_auc: 0.2425 - precision: 0.1814 - recall: 0.6552 - roc_auc: 0.7377 - val_loss: 0.7708 - val_pr_auc: 0.1934 - val_precision: 0.1587 - val_recall: 1.0000 - val_roc_auc: 0.8604 - val_combined: 0.4354
Epoch 25/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.6212 - pr_auc: 0.2335 - precision: 0.2057 - recall: 0.6897 - roc_auc: 0.7660 - val_loss: 0.7607 - val_pr_auc: 0.1821 - val_precision: 0.1754 - val_recall: 1.0000 - val_roc_auc: 0.8670 - val_combined: 0.4275
Epoch 26/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 207ms/step - loss: 0.6277 - pr_auc: 0.2465 - precision: 0.2041 - recall: 0.6810 - roc_auc: 0.7502 - val_loss: 0.8171 - val_pr_auc: 0.1035 - val_precision: 0.1282 - val_recall: 1.0000 - val_roc_auc: 0.7871 - val_combined: 0.3725
Epoch 27/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 182ms/step - loss: 0.6246 - pr_auc: 0.2354 - precision: 0.1975 - recall: 0.6724 - roc_auc: 0.7496 - val_loss: 0.7804 - val_pr_auc: 0.1002 - val_precision: 0.1525 - val_recall: 0.9000 - val_roc_auc: 0.7766 - val_combined: 0.3401
Epoch 28/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 206ms/step - loss: 0.6141 - pr_auc: 0.2852 - precision: 0.2197 - recall: 0.6552 - roc_auc: 0.7584 - val_loss: 0.7704 - val_pr_auc: 0.1183 - val_precision: 0.1852 - val_recall: 1.0000 - val_roc_auc: 0.8195 - val_combined: 0.3828
Epoch 29/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.6206 - pr_auc: 0.2275 - precision: 0.1892 - recall: 0.6638 - roc_auc: 0.7054 - val_loss: 0.7781 - val_pr_auc: 0.1101 - val_precision: 0.1667 - val_recall: 0.9000 - val_roc_auc: 0.8011 - val_combined: 0.3470
Epoch 30/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 183ms/step - loss: 0.6059 - pr_auc: 0.3008 - precision: 0.2692 - recall: 0.6638 - roc_auc: 0.7419 - val_loss: 0.7696 - val_pr_auc: 0.1081 - val_precision: 0.1176 - val_recall: 0.6000 - val_roc_auc: 0.7951 - val_combined: 0.2557
Epoch 31/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.5954 - pr_auc: 0.3940 - precision: 0.2786 - recall: 0.6724 - roc_auc: 0.7863 - val_loss: 0.7788 - val_pr_auc: 0.1063 - val_precision: 0.1346 - val_recall: 0.7000 - val_roc_auc: 0.7909 - val_combined: 0.2844
Epoch 32/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.5972 - pr_auc: 0.3565 - precision: 0.2778 - recall: 0.6466 - roc_auc: 0.7736 - val_loss: 0.7450 - val_pr_auc: 0.1020 - val_precision: 0.1250 - val_recall: 0.6000 - val_roc_auc: 0.7761 - val_combined: 0.2514
Epoch 33/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.5923 - pr_auc: 0.4157 - precision: 0.3144 - recall: 0.6207 - roc_auc: 0.7949 - val_loss: 0.7331 - val_pr_auc: 0.1202 - val_precision: 0.2083 - val_recall: 1.0000 - val_roc_auc: 0.8181 - val_combined: 0.3841
Epoch 34/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 185ms/step - loss: 0.6037 - pr_auc: 0.3467 - precision: 0.2720 - recall: 0.5862 - roc_auc: 0.7536 - val_loss: 0.7564 - val_pr_auc: 0.0869 - val_precision: 0.0755 - val_recall: 0.4000 - val_roc_auc: 0.7305 - val_combined: 0.1808
Epoch 35/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.6017 - pr_auc: 0.3498 - precision: 0.2731 - recall: 0.6121 - roc_auc: 0.7557 - val_loss: 0.7745 - val_pr_auc: 0.0949 - val_precision: 0.1273 - val_recall: 0.7000 - val_roc_auc: 0.7560 - val_combined: 0.2764
Epoch 36/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.5851 - pr_auc: 0.3374 - precision: 0.2366 - recall: 0.6466 - roc_auc: 0.7671 - val_loss: 0.7842 - val_pr_auc: 0.1070 - val_precision: 0.1724 - val_recall: 1.0000 - val_roc_auc: 0.7876 - val_combined: 0.3749
Epoch 37/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 183ms/step - loss: 0.5775 - pr_auc: 0.4545 - precision: 0.2930 - recall: 0.6466 - roc_auc: 0.7475 - val_loss: 0.7987 - val_pr_auc: 0.1103 - val_precision: 0.1639 - val_recall: 1.0000 - val_roc_auc: 0.7937 - val_combined: 0.3772
Epoch 38/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.5825 - pr_auc: 0.4163 - precision: 0.2561 - recall: 0.6379 - roc_auc: 0.7483 - val_loss: 0.7701 - val_pr_auc: 0.1136 - val_precision: 0.1852 - val_recall: 1.0000 - val_roc_auc: 0.8014 - val_combined: 0.3795
Epoch 39/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.5960 - pr_auc: 0.3652 - precision: 0.2325 - recall: 0.6293 - roc_auc: 0.7547 - val_loss: 0.8283 - val_pr_auc: 0.1036 - val_precision: 0.1562 - val_recall: 1.0000 - val_roc_auc: 0.7805 - val_combined: 0.3725
Epoch 40/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5776 - pr_auc: 0.3904 - precision: 0.2662 - recall: 0.6379 - roc_auc: 0.7734 - val_loss: 0.7652 - val_pr_auc: 0.1062 - val_precision: 0.1429 - val_recall: 0.7000 - val_roc_auc: 0.7846 - val_combined: 0.2844
Epoch 41/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 193ms/step - loss: 0.5705 - pr_auc: 0.4541 - precision: 0.3578 - recall: 0.6293 - roc_auc: 0.7752 - val_loss: 0.7442 - val_pr_auc: 0.1025 - val_precision: 0.0667 - val_recall: 0.3000 - val_roc_auc: 0.7777 - val_combined: 0.1617
Epoch 42/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.5625 - pr_auc: 0.4568 - precision: 0.3846 - recall: 0.6466 - roc_auc: 0.7795 - val_loss: 0.7410 - val_pr_auc: 0.1007 - val_precision: 0.0500 - val_recall: 0.2000 - val_roc_auc: 0.7747 - val_combined: 0.1305
Epoch 43/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 210ms/step - loss: 0.5606 - pr_auc: 0.4938 - precision: 0.3871 - recall: 0.6207 - roc_auc: 0.7778 - val_loss: 0.7253 - val_pr_auc: 0.0994 - val_precision: 0.0345 - val_recall: 0.1000 - val_roc_auc: 0.7769 - val_combined: 0.0996
Epoch 44/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 184ms/step - loss: 0.5586 - pr_auc: 0.4721 - precision: 0.3967 - recall: 0.6293 - roc_auc: 0.7918 - val_loss: 0.7186 - val_pr_auc: 0.1197 - val_precision: 0.1250 - val_recall: 0.5000 - val_roc_auc: 0.8159 - val_combined: 0.2338
Epoch 45/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 211ms/step - loss: 0.5672 - pr_auc: 0.4452 - precision: 0.3054 - recall: 0.6293 - roc_auc: 0.7586 - val_loss: 0.8232 - val_pr_auc: 0.0851 - val_precision: 0.1493 - val_recall: 1.0000 - val_roc_auc: 0.7220 - val_combined: 0.3596
Epoch 46/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.5866 - pr_auc: 0.2971 - precision: 0.2450 - recall: 0.6293 - roc_auc: 0.7437 - val_loss: 0.7445 - val_pr_auc: 0.0854 - val_precision: 0.0303 - val_recall: 0.1000 - val_roc_auc: 0.7357 - val_combined: 0.0897
Epoch 47/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 185ms/step - loss: 0.5541 - pr_auc: 0.3835 - precision: 0.3883 - recall: 0.6293 - roc_auc: 0.7936 - val_loss: 0.7582 - val_pr_auc: 0.0925 - val_precision: 0.0476 - val_recall: 0.2000 - val_roc_auc: 0.7566 - val_combined: 0.1248
Epoch 48/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 204ms/step - loss: 0.5624 - pr_auc: 0.4134 - precision: 0.3793 - recall: 0.5690 - roc_auc: 0.7721 - val_loss: 0.7504 - val_pr_auc: 0.0932 - val_precision: 0.0541 - val_recall: 0.2000 - val_roc_auc: 0.7591 - val_combined: 0.1252
Epoch 49/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.5430 - pr_auc: 0.4953 - precision: 0.3862 - recall: 0.6293 - roc_auc: 0.8018 - val_loss: 0.7291 - val_pr_auc: 0.0731 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6585 - val_combined: 0.0512
Epoch 50/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.5393 - pr_auc: 0.4780 - precision: 0.4294 - recall: 0.6293 - roc_auc: 0.7685 - val_loss: 0.7273 - val_pr_auc: 0.0950 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7659 - val_combined: 0.0665
Epoch 51/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 190ms/step - loss: 0.5369 - pr_auc: 0.5074 - precision: 0.4260 - recall: 0.6207 - roc_auc: 0.7818 - val_loss: 0.7186 - val_pr_auc: 0.0901 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7519 - val_combined: 0.0631
Epoch 52/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - loss: 0.5467 - pr_auc: 0.4497 - precision: 0.3736 - recall: 0.5862 - roc_auc: 0.7956 - val_loss: 0.7415 - val_pr_auc: 0.1048 - val_precision: 0.0952 - val_recall: 0.4000 - val_roc_auc: 0.7879 - val_combined: 0.1934
Epoch 53/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 210ms/step - loss: 0.5565 - pr_auc: 0.3806 - precision: 0.3033 - recall: 0.6379 - roc_auc: 0.7762 - val_loss: 0.7179 - val_pr_auc: 0.1065 - val_precision: 0.0571 - val_recall: 0.2000 - val_roc_auc: 0.7926 - val_combined: 0.1345
Epoch 54/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 184ms/step - loss: 0.5250 - pr_auc: 0.5495 - precision: 0.4679 - recall: 0.6293 - roc_auc: 0.7928 - val_loss: 0.7069 - val_pr_auc: 0.1011 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7802 - val_combined: 0.0708
Epoch 55/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.5291 - pr_auc: 0.5250 - precision: 0.4512 - recall: 0.6379 - roc_auc: 0.7751 - val_loss: 0.6911 - val_pr_auc: 0.0986 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7755 - val_combined: 0.0690
Epoch 56/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.5287 - pr_auc: 0.5091 - precision: 0.4444 - recall: 0.6207 - roc_auc: 0.7839 - val_loss: 0.6849 - val_pr_auc: 0.0786 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6588 - val_combined: 0.0550
Epoch 57/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 187ms/step - loss: 0.5198 - pr_auc: 0.5291 - precision: 0.5103 - recall: 0.6379 - roc_auc: 0.8205 - val_loss: 0.6997 - val_pr_auc: 0.0804 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6750 - val_combined: 0.0563
Epoch 58/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 203ms/step - loss: 0.5202 - pr_auc: 0.4858 - precision: 0.4803 - recall: 0.6293 - roc_auc: 0.7876 - val_loss: 0.7001 - val_pr_auc: 0.0965 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7703 - val_combined: 0.0675
Epoch 59/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.5108 - pr_auc: 0.5452 - precision: 0.5175 - recall: 0.6379 - roc_auc: 0.7962 - val_loss: 0.7155 - val_pr_auc: 0.0654 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5896 - val_combined: 0.0457
Epoch 60/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.5143 - pr_auc: 0.5371 - precision: 0.4932 - recall: 0.6293 - roc_auc: 0.7617 - val_loss: 0.7125 - val_pr_auc: 0.0737 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6533 - val_combined: 0.0516
Epoch 61/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 184ms/step - loss: 0.5247 - pr_auc: 0.4952 - precision: 0.5234 - recall: 0.5776 - roc_auc: 0.7706 - val_loss: 0.7462 - val_pr_auc: 0.0982 - val_precision: 0.0312 - val_recall: 0.1000 - val_roc_auc: 0.7673 - val_combined: 0.0987
Epoch 62/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.5230 - pr_auc: 0.5383 - precision: 0.5455 - recall: 0.5690 - roc_auc: 0.7708 - val_loss: 0.6944 - val_pr_auc: 0.0761 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6434 - val_combined: 0.0533
Epoch 63/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 209ms/step - loss: 0.5152 - pr_auc: 0.5857 - precision: 0.6373 - recall: 0.5603 - roc_auc: 0.7824 - val_loss: 0.7431 - val_pr_auc: 0.0866 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7354 - val_combined: 0.0606
Epoch 64/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 196ms/step - loss: 0.5151 - pr_auc: 0.4980 - precision: 0.4148 - recall: 0.6293 - roc_auc: 0.8038 - val_loss: 0.7135 - val_pr_auc: 0.0849 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6835 - val_combined: 0.0594
Epoch 65/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.5054 - pr_auc: 0.5227 - precision: 0.4512 - recall: 0.6379 - roc_auc: 0.7839 - val_loss: 0.6914 - val_pr_auc: 0.0817 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6794 - val_combined: 0.0572
Epoch 66/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 210ms/step - loss: 0.5098 - pr_auc: 0.4999 - precision: 0.6050 - recall: 0.6207 - roc_auc: 0.7556 - val_loss: 0.6751 - val_pr_auc: 0.1067 - val_precision: 0.0400 - val_recall: 0.1000 - val_roc_auc: 0.7937 - val_combined: 0.1047
Epoch 66: early stopping
Restoring model weights from the end of the best epoch: 16.
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step

Running seed 60

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 19s 209ms/step - loss: 0.6943 - pr_auc: 0.0720 - precision: 0.0603 - recall: 0.1638 - roc_auc: 0.4686 - val_loss: 0.6861 - val_pr_auc: 0.0712 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6049 - val_combined: 0.0499
Epoch 2/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 186ms/step - loss: 0.6901 - pr_auc: 0.1199 - precision: 0.1325 - recall: 0.3448 - roc_auc: 0.6271 - val_loss: 0.6842 - val_pr_auc: 0.0837 - val_precision: 0.0769 - val_recall: 0.4000 - val_roc_auc: 0.6973 - val_combined: 0.1786
Epoch 3/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6903 - pr_auc: 0.1130 - precision: 0.1367 - recall: 0.3534 - roc_auc: 0.5960 - val_loss: 0.6749 - val_pr_auc: 0.1074 - val_precision: 0.0385 - val_recall: 0.1000 - val_roc_auc: 0.7885 - val_combined: 0.1052
Epoch 4/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 189ms/step - loss: 0.6868 - pr_auc: 0.1841 - precision: 0.1957 - recall: 0.3879 - roc_auc: 0.6534 - val_loss: 0.6586 - val_pr_auc: 0.1139 - val_precision: 0.0400 - val_recall: 0.1000 - val_roc_auc: 0.7926 - val_combined: 0.1098
Epoch 5/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 183ms/step - loss: 0.6825 - pr_auc: 0.1982 - precision: 0.2532 - recall: 0.3362 - roc_auc: 0.6907 - val_loss: 0.6465 - val_pr_auc: 0.1398 - val_precision: 0.1143 - val_recall: 0.4000 - val_roc_auc: 0.8319 - val_combined: 0.2179
Epoch 6/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.6816 - pr_auc: 0.2107 - precision: 0.2871 - recall: 0.5000 - roc_auc: 0.6764 - val_loss: 0.6392 - val_pr_auc: 0.1604 - val_precision: 0.1282 - val_recall: 0.5000 - val_roc_auc: 0.8478 - val_combined: 0.2623
Epoch 7/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 192ms/step - loss: 0.6742 - pr_auc: 0.2410 - precision: 0.2771 - recall: 0.3966 - roc_auc: 0.7172 - val_loss: 0.6411 - val_pr_auc: 0.2521 - val_precision: 0.1613 - val_recall: 1.0000 - val_roc_auc: 0.8799 - val_combined: 0.4765
Epoch 8/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 179ms/step - loss: 0.6733 - pr_auc: 0.2176 - precision: 0.2835 - recall: 0.4741 - roc_auc: 0.7037 - val_loss: 0.6314 - val_pr_auc: 0.1289 - val_precision: 0.1639 - val_recall: 1.0000 - val_roc_auc: 0.8234 - val_combined: 0.3902
Epoch 9/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6668 - pr_auc: 0.2304 - precision: 0.2757 - recall: 0.5776 - roc_auc: 0.7258 - val_loss: 0.6181 - val_pr_auc: 0.1560 - val_precision: 0.1786 - val_recall: 1.0000 - val_roc_auc: 0.8569 - val_combined: 0.4092
Epoch 10/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 191ms/step - loss: 0.6612 - pr_auc: 0.2555 - precision: 0.2944 - recall: 0.5862 - roc_auc: 0.7472 - val_loss: 0.6174 - val_pr_auc: 0.1818 - val_precision: 0.1538 - val_recall: 1.0000 - val_roc_auc: 0.8764 - val_combined: 0.4273
Epoch 11/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 179ms/step - loss: 0.6611 - pr_auc: 0.2636 - precision: 0.3046 - recall: 0.5172 - roc_auc: 0.7286 - val_loss: 0.6079 - val_pr_auc: 0.1470 - val_precision: 0.1639 - val_recall: 1.0000 - val_roc_auc: 0.8456 - val_combined: 0.4029
Epoch 12/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6592 - pr_auc: 0.2154 - precision: 0.2806 - recall: 0.6121 - roc_auc: 0.7182 - val_loss: 0.5940 - val_pr_auc: 0.1428 - val_precision: 0.1852 - val_recall: 1.0000 - val_roc_auc: 0.8418 - val_combined: 0.4000
Epoch 13/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 193ms/step - loss: 0.6553 - pr_auc: 0.2539 - precision: 0.3173 - recall: 0.5690 - roc_auc: 0.7247 - val_loss: 0.5763 - val_pr_auc: 0.1540 - val_precision: 0.1778 - val_recall: 0.8000 - val_roc_auc: 0.8588 - val_combined: 0.3478
Epoch 14/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 179ms/step - loss: 0.6575 - pr_auc: 0.2606 - precision: 0.3246 - recall: 0.5345 - roc_auc: 0.7059 - val_loss: 0.5800 - val_pr_auc: 0.1478 - val_precision: 0.1887 - val_recall: 1.0000 - val_roc_auc: 0.8481 - val_combined: 0.4034
Epoch 15/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6475 - pr_auc: 0.2562 - precision: 0.2899 - recall: 0.5948 - roc_auc: 0.7401 - val_loss: 0.5771 - val_pr_auc: 0.1449 - val_precision: 0.1818 - val_recall: 1.0000 - val_roc_auc: 0.8453 - val_combined: 0.4014
Epoch 16/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 192ms/step - loss: 0.6465 - pr_auc: 0.2682 - precision: 0.2886 - recall: 0.6121 - roc_auc: 0.7340 - val_loss: 0.5910 - val_pr_auc: 0.1456 - val_precision: 0.1493 - val_recall: 1.0000 - val_roc_auc: 0.8412 - val_combined: 0.4019
Epoch 17/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 178ms/step - loss: 0.6493 - pr_auc: 0.2126 - precision: 0.2363 - recall: 0.5948 - roc_auc: 0.7223 - val_loss: 0.5730 - val_pr_auc: 0.1277 - val_precision: 0.1724 - val_recall: 1.0000 - val_roc_auc: 0.8272 - val_combined: 0.3894
Epoch 18/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.6467 - pr_auc: 0.2427 - precision: 0.2932 - recall: 0.6293 - roc_auc: 0.7139 - val_loss: 0.5589 - val_pr_auc: 0.1331 - val_precision: 0.1277 - val_recall: 0.6000 - val_roc_auc: 0.8341 - val_combined: 0.2732
Epoch 19/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 196ms/step - loss: 0.6354 - pr_auc: 0.3298 - precision: 0.2951 - recall: 0.6207 - roc_auc: 0.7422 - val_loss: 0.5492 - val_pr_auc: 0.1518 - val_precision: 0.1778 - val_recall: 0.8000 - val_roc_auc: 0.8571 - val_combined: 0.3463
Epoch 20/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 172ms/step - loss: 0.6567 - pr_auc: 0.2418 - precision: 0.3100 - recall: 0.5345 - roc_auc: 0.6645 - val_loss: 0.5665 - val_pr_auc: 0.1270 - val_precision: 0.1852 - val_recall: 1.0000 - val_roc_auc: 0.8258 - val_combined: 0.3889
Epoch 21/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.6345 - pr_auc: 0.2857 - precision: 0.3042 - recall: 0.6293 - roc_auc: 0.7351 - val_loss: 0.5559 - val_pr_auc: 0.1467 - val_precision: 0.1633 - val_recall: 0.8000 - val_roc_auc: 0.8481 - val_combined: 0.3427
Epoch 22/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 196ms/step - loss: 0.6303 - pr_auc: 0.2796 - precision: 0.3117 - recall: 0.6207 - roc_auc: 0.7383 - val_loss: 0.5586 - val_pr_auc: 0.1352 - val_precision: 0.1538 - val_recall: 0.8000 - val_roc_auc: 0.8321 - val_combined: 0.3347
Epoch 23/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - loss: 0.6266 - pr_auc: 0.2603 - precision: 0.3051 - recall: 0.6207 - roc_auc: 0.7607 - val_loss: 0.5671 - val_pr_auc: 0.1486 - val_precision: 0.1667 - val_recall: 1.0000 - val_roc_auc: 0.8470 - val_combined: 0.4040
Epoch 24/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6351 - pr_auc: 0.2378 - precision: 0.2944 - recall: 0.6293 - roc_auc: 0.7060 - val_loss: 0.5455 - val_pr_auc: 0.1706 - val_precision: 0.1458 - val_recall: 0.7000 - val_roc_auc: 0.8549 - val_combined: 0.3294
Epoch 25/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6224 - pr_auc: 0.2617 - precision: 0.3038 - recall: 0.6207 - roc_auc: 0.7518 - val_loss: 0.5581 - val_pr_auc: 0.1505 - val_precision: 0.1754 - val_recall: 1.0000 - val_roc_auc: 0.8481 - val_combined: 0.4053
Epoch 26/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 172ms/step - loss: 0.6138 - pr_auc: 0.2533 - precision: 0.3090 - recall: 0.6207 - roc_auc: 0.7822 - val_loss: 0.5483 - val_pr_auc: 0.1342 - val_precision: 0.1509 - val_recall: 0.8000 - val_roc_auc: 0.8319 - val_combined: 0.3339
Epoch 27/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.6109 - pr_auc: 0.2844 - precision: 0.3274 - recall: 0.6379 - roc_auc: 0.7764 - val_loss: 0.5289 - val_pr_auc: 0.1558 - val_precision: 0.1364 - val_recall: 0.6000 - val_roc_auc: 0.8541 - val_combined: 0.2890
Epoch 28/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 200ms/step - loss: 0.6154 - pr_auc: 0.2380 - precision: 0.2902 - recall: 0.6379 - roc_auc: 0.7557 - val_loss: 0.5816 - val_pr_auc: 0.1286 - val_precision: 0.1408 - val_recall: 1.0000 - val_roc_auc: 0.8198 - val_combined: 0.3900
Epoch 29/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 173ms/step - loss: 0.6152 - pr_auc: 0.2616 - precision: 0.2761 - recall: 0.6379 - roc_auc: 0.7531 - val_loss: 0.5608 - val_pr_auc: 0.1183 - val_precision: 0.1613 - val_recall: 1.0000 - val_roc_auc: 0.8104 - val_combined: 0.3828
Epoch 30/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 194ms/step - loss: 0.6089 - pr_auc: 0.2784 - precision: 0.2769 - recall: 0.6207 - roc_auc: 0.7584 - val_loss: 0.5463 - val_pr_auc: 0.1316 - val_precision: 0.1786 - val_recall: 1.0000 - val_roc_auc: 0.8299 - val_combined: 0.3921
Epoch 31/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6008 - pr_auc: 0.3012 - precision: 0.3136 - recall: 0.6379 - roc_auc: 0.7742 - val_loss: 0.5236 - val_pr_auc: 0.1548 - val_precision: 0.1333 - val_recall: 0.6000 - val_roc_auc: 0.8525 - val_combined: 0.2883
Epoch 32/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 188ms/step - loss: 0.5919 - pr_auc: 0.2870 - precision: 0.3318 - recall: 0.6293 - roc_auc: 0.7878 - val_loss: 0.5219 - val_pr_auc: 0.1506 - val_precision: 0.1395 - val_recall: 0.6000 - val_roc_auc: 0.8484 - val_combined: 0.2854
Epoch 33/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 181ms/step - loss: 0.5908 - pr_auc: 0.2936 - precision: 0.3488 - recall: 0.6466 - roc_auc: 0.7838 - val_loss: 0.5336 - val_pr_auc: 0.1237 - val_precision: 0.1250 - val_recall: 0.6000 - val_roc_auc: 0.8228 - val_combined: 0.2666
Epoch 34/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.6164 - pr_auc: 0.2455 - precision: 0.2544 - recall: 0.6207 - roc_auc: 0.7159 - val_loss: 0.4625 - val_pr_auc: 0.1511 - val_precision: 0.2222 - val_recall: 0.4000 - val_roc_auc: 0.7970 - val_combined: 0.2258
Epoch 35/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 195ms/step - loss: 0.6364 - pr_auc: 0.1856 - precision: 0.1813 - recall: 0.5862 - roc_auc: 0.6877 - val_loss: 0.5365 - val_pr_auc: 0.1128 - val_precision: 0.0976 - val_recall: 0.4000 - val_roc_auc: 0.8066 - val_combined: 0.1990
Epoch 36/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 179ms/step - loss: 0.6153 - pr_auc: 0.1979 - precision: 0.2078 - recall: 0.6466 - roc_auc: 0.7226 - val_loss: 0.5272 - val_pr_auc: 0.1193 - val_precision: 0.1250 - val_recall: 0.5000 - val_roc_auc: 0.8179 - val_combined: 0.2335
Epoch 37/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.5968 - pr_auc: 0.2477 - precision: 0.2741 - recall: 0.6379 - roc_auc: 0.7660 - val_loss: 0.5595 - val_pr_auc: 0.1062 - val_precision: 0.1552 - val_recall: 0.9000 - val_roc_auc: 0.7967 - val_combined: 0.3444
Epoch 38/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6066 - pr_auc: 0.2488 - precision: 0.2491 - recall: 0.6293 - roc_auc: 0.7411 - val_loss: 0.5617 - val_pr_auc: 0.1170 - val_precision: 0.1346 - val_recall: 0.7000 - val_roc_auc: 0.8168 - val_combined: 0.2919
Epoch 39/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 173ms/step - loss: 0.5884 - pr_auc: 0.3411 - precision: 0.3153 - recall: 0.6034 - roc_auc: 0.7737 - val_loss: 0.5221 - val_pr_auc: 0.1178 - val_precision: 0.1429 - val_recall: 0.7000 - val_roc_auc: 0.8190 - val_combined: 0.2925
Epoch 40/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.5936 - pr_auc: 0.2800 - precision: 0.3272 - recall: 0.6121 - roc_auc: 0.7547 - val_loss: 0.5217 - val_pr_auc: 0.1410 - val_precision: 0.1800 - val_recall: 0.9000 - val_roc_auc: 0.8423 - val_combined: 0.3687
Epoch 41/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 200ms/step - loss: 0.5929 - pr_auc: 0.2694 - precision: 0.3275 - recall: 0.6466 - roc_auc: 0.7426 - val_loss: 0.5263 - val_pr_auc: 0.1410 - val_precision: 0.1633 - val_recall: 0.8000 - val_roc_auc: 0.8423 - val_combined: 0.3387
Epoch 42/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 174ms/step - loss: 0.5807 - pr_auc: 0.2807 - precision: 0.3318 - recall: 0.6379 - roc_auc: 0.7747 - val_loss: 0.5240 - val_pr_auc: 0.1447 - val_precision: 0.1522 - val_recall: 0.7000 - val_roc_auc: 0.8467 - val_combined: 0.3113
Epoch 43/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 196ms/step - loss: 0.5876 - pr_auc: 0.2850 - precision: 0.3304 - recall: 0.6466 - roc_auc: 0.7422 - val_loss: 0.5298 - val_pr_auc: 0.1451 - val_precision: 0.1333 - val_recall: 0.6000 - val_roc_auc: 0.8456 - val_combined: 0.2815
Epoch 44/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5719 - pr_auc: 0.3306 - precision: 0.3363 - recall: 0.6466 - roc_auc: 0.7793 - val_loss: 0.5341 - val_pr_auc: 0.1285 - val_precision: 0.1333 - val_recall: 0.6000 - val_roc_auc: 0.8357 - val_combined: 0.2699
Epoch 45/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 173ms/step - loss: 0.5744 - pr_auc: 0.2995 - precision: 0.3378 - recall: 0.6466 - roc_auc: 0.7699 - val_loss: 0.5297 - val_pr_auc: 0.1281 - val_precision: 0.1463 - val_recall: 0.6000 - val_roc_auc: 0.8357 - val_combined: 0.2697
Epoch 46/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 197ms/step - loss: 0.5664 - pr_auc: 0.2855 - precision: 0.3460 - recall: 0.6293 - roc_auc: 0.7916 - val_loss: 0.5153 - val_pr_auc: 0.1266 - val_precision: 0.1316 - val_recall: 0.5000 - val_roc_auc: 0.8324 - val_combined: 0.2387
Epoch 47/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5749 - pr_auc: 0.2984 - precision: 0.3538 - recall: 0.6466 - roc_auc: 0.7588 - val_loss: 0.5751 - val_pr_auc: 0.0835 - val_precision: 0.1277 - val_recall: 0.6000 - val_roc_auc: 0.6970 - val_combined: 0.2385
Epoch 48/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 188ms/step - loss: 0.5614 - pr_auc: 0.3180 - precision: 0.3692 - recall: 0.6207 - roc_auc: 0.8093 - val_loss: 0.5595 - val_pr_auc: 0.0928 - val_precision: 0.1364 - val_recall: 0.6000 - val_roc_auc: 0.7132 - val_combined: 0.2449
Epoch 49/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 182ms/step - loss: 0.5601 - pr_auc: 0.2763 - precision: 0.3125 - recall: 0.6466 - roc_auc: 0.7979 - val_loss: 0.4912 - val_pr_auc: 0.0983 - val_precision: 0.1429 - val_recall: 0.4000 - val_roc_auc: 0.7214 - val_combined: 0.1888
Epoch 50/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.5734 - pr_auc: 0.2860 - precision: 0.3302 - recall: 0.6034 - roc_auc: 0.7730 - val_loss: 0.5933 - val_pr_auc: 0.0944 - val_precision: 0.1091 - val_recall: 0.6000 - val_roc_auc: 0.7626 - val_combined: 0.2461
Epoch 51/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 188ms/step - loss: 0.5556 - pr_auc: 0.3050 - precision: 0.3147 - recall: 0.6293 - roc_auc: 0.8130 - val_loss: 0.5181 - val_pr_auc: 0.0873 - val_precision: 0.1081 - val_recall: 0.4000 - val_roc_auc: 0.7266 - val_combined: 0.1811
Epoch 52/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 182ms/step - loss: 0.5339 - pr_auc: 0.3955 - precision: 0.3719 - recall: 0.6379 - roc_auc: 0.8371 - val_loss: 0.5145 - val_pr_auc: 0.0718 - val_precision: 0.1071 - val_recall: 0.3000 - val_roc_auc: 0.6519 - val_combined: 0.1403
Epoch 53/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5287 - pr_auc: 0.3759 - precision: 0.3776 - recall: 0.6379 - roc_auc: 0.8451 - val_loss: 0.4464 - val_pr_auc: 0.1029 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7755 - val_combined: 0.0720
Epoch 54/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 195ms/step - loss: 0.5233 - pr_auc: 0.4134 - precision: 0.3561 - recall: 0.6293 - roc_auc: 0.8479 - val_loss: 0.4642 - val_pr_auc: 0.1080 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7929 - val_combined: 0.0756
Epoch 55/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 179ms/step - loss: 0.5593 - pr_auc: 0.3050 - precision: 0.3382 - recall: 0.6034 - roc_auc: 0.7863 - val_loss: 0.8201 - val_pr_auc: 0.1173 - val_precision: 0.0943 - val_recall: 1.0000 - val_roc_auc: 0.8071 - val_combined: 0.3821
Epoch 56/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.5797 - pr_auc: 0.1755 - precision: 0.1923 - recall: 0.6466 - roc_auc: 0.7780 - val_loss: 0.6656 - val_pr_auc: 0.0951 - val_precision: 0.1429 - val_recall: 0.9000 - val_roc_auc: 0.7659 - val_combined: 0.3366
Epoch 57/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 192ms/step - loss: 0.5592 - pr_auc: 0.2460 - precision: 0.2442 - recall: 0.6379 - roc_auc: 0.8022 - val_loss: 0.5746 - val_pr_auc: 0.1048 - val_precision: 0.1481 - val_recall: 0.8000 - val_roc_auc: 0.7893 - val_combined: 0.3134
Epoch 57: early stopping
Restoring model weights from the end of the best epoch: 7.
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step

Running seed 96

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 18s 222ms/step - loss: 0.6983 - pr_auc: 0.0521 - precision: 0.0375 - recall: 0.0259 - roc_auc: 0.3001 - val_loss: 0.6737 - val_pr_auc: 0.0559 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.5824 - val_combined: 0.0391
Epoch 2/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 196ms/step - loss: 0.6941 - pr_auc: 0.0752 - precision: 0.0000e+00 - recall: 0.0000e+00 - roc_auc: 0.4869 - val_loss: 0.6717 - val_pr_auc: 0.0613 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6236 - val_combined: 0.0429
Epoch 3/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 179ms/step - loss: 0.6920 - pr_auc: 0.1170 - precision: 0.0769 - recall: 0.0172 - roc_auc: 0.5568 - val_loss: 0.6700 - val_pr_auc: 0.0648 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6374 - val_combined: 0.0453
Epoch 4/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 188ms/step - loss: 0.6897 - pr_auc: 0.1640 - precision: 0.3200 - recall: 0.0690 - roc_auc: 0.6300 - val_loss: 0.6652 - val_pr_auc: 0.0740 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.6926 - val_combined: 0.0518
Epoch 5/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6874 - pr_auc: 0.1904 - precision: 0.3864 - recall: 0.1466 - roc_auc: 0.6621 - val_loss: 0.6601 - val_pr_auc: 0.0833 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7239 - val_combined: 0.0583
Epoch 6/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 189ms/step - loss: 0.6846 - pr_auc: 0.2047 - precision: 0.3250 - recall: 0.1121 - roc_auc: 0.7021 - val_loss: 0.6578 - val_pr_auc: 0.0854 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7368 - val_combined: 0.0598
Epoch 7/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 178ms/step - loss: 0.6842 - pr_auc: 0.2266 - precision: 0.3939 - recall: 0.1121 - roc_auc: 0.6958 - val_loss: 0.6452 - val_pr_auc: 0.0979 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7769 - val_combined: 0.0686
Epoch 8/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 197ms/step - loss: 0.6792 - pr_auc: 0.3617 - precision: 0.5000 - recall: 0.2759 - roc_auc: 0.7163 - val_loss: 0.6406 - val_pr_auc: 0.1050 - val_precision: 0.1212 - val_recall: 0.4000 - val_roc_auc: 0.7907 - val_combined: 0.1935
Epoch 9/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 186ms/step - loss: 0.6745 - pr_auc: 0.3077 - precision: 0.4124 - recall: 0.3448 - roc_auc: 0.7495 - val_loss: 0.6279 - val_pr_auc: 0.1116 - val_precision: 0.1212 - val_recall: 0.4000 - val_roc_auc: 0.8047 - val_combined: 0.1981
Epoch 10/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 183ms/step - loss: 0.6757 - pr_auc: 0.2700 - precision: 0.4158 - recall: 0.3621 - roc_auc: 0.7034 - val_loss: 0.6357 - val_pr_auc: 0.1042 - val_precision: 0.1071 - val_recall: 0.6000 - val_roc_auc: 0.7890 - val_combined: 0.2530
Epoch 11/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.6721 - pr_auc: 0.2428 - precision: 0.3033 - recall: 0.3190 - roc_auc: 0.7341 - val_loss: 0.6339 - val_pr_auc: 0.1218 - val_precision: 0.1667 - val_recall: 1.0000 - val_roc_auc: 0.8253 - val_combined: 0.3853
Epoch 12/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 192ms/step - loss: 0.6702 - pr_auc: 0.2642 - precision: 0.3000 - recall: 0.4655 - roc_auc: 0.7235 - val_loss: 0.6194 - val_pr_auc: 0.1168 - val_precision: 0.1277 - val_recall: 0.6000 - val_roc_auc: 0.8176 - val_combined: 0.2618
Epoch 13/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 180ms/step - loss: 0.6640 - pr_auc: 0.2729 - precision: 0.3195 - recall: 0.4655 - roc_auc: 0.7443 - val_loss: 0.6156 - val_pr_auc: 0.1390 - val_precision: 0.1961 - val_recall: 1.0000 - val_roc_auc: 0.8418 - val_combined: 0.3973
Epoch 14/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6620 - pr_auc: 0.2294 - precision: 0.2629 - recall: 0.4828 - roc_auc: 0.7413 - val_loss: 0.6173 - val_pr_auc: 0.1542 - val_precision: 0.1639 - val_recall: 1.0000 - val_roc_auc: 0.8560 - val_combined: 0.4079
Epoch 15/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 197ms/step - loss: 0.6573 - pr_auc: 0.2486 - precision: 0.2500 - recall: 0.5086 - roc_auc: 0.7486 - val_loss: 0.6403 - val_pr_auc: 0.1462 - val_precision: 0.1205 - val_recall: 1.0000 - val_roc_auc: 0.8544 - val_combined: 0.4024
Epoch 16/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 173ms/step - loss: 0.6685 - pr_auc: 0.1671 - precision: 0.2024 - recall: 0.4397 - roc_auc: 0.6702 - val_loss: 0.6080 - val_pr_auc: 0.1348 - val_precision: 0.1818 - val_recall: 1.0000 - val_roc_auc: 0.8357 - val_combined: 0.3943
Epoch 17/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6563 - pr_auc: 0.2338 - precision: 0.2886 - recall: 0.5000 - roc_auc: 0.7335 - val_loss: 0.6089 - val_pr_auc: 0.1271 - val_precision: 0.1852 - val_recall: 1.0000 - val_roc_auc: 0.8261 - val_combined: 0.3890
Epoch 18/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 197ms/step - loss: 0.6460 - pr_auc: 0.2746 - precision: 0.3136 - recall: 0.5948 - roc_auc: 0.7701 - val_loss: 0.6005 - val_pr_auc: 0.1854 - val_precision: 0.1887 - val_recall: 1.0000 - val_roc_auc: 0.8692 - val_combined: 0.4298
Epoch 19/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 173ms/step - loss: 0.6468 - pr_auc: 0.2369 - precision: 0.2600 - recall: 0.5603 - roc_auc: 0.7432 - val_loss: 0.6239 - val_pr_auc: 0.1910 - val_precision: 0.1429 - val_recall: 1.0000 - val_roc_auc: 0.8687 - val_combined: 0.4337
Epoch 20/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6441 - pr_auc: 0.2379 - precision: 0.2795 - recall: 0.5517 - roc_auc: 0.7561 - val_loss: 0.6071 - val_pr_auc: 0.1255 - val_precision: 0.1695 - val_recall: 1.0000 - val_roc_auc: 0.8220 - val_combined: 0.3878
Epoch 21/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6423 - pr_auc: 0.2109 - precision: 0.2464 - recall: 0.5948 - roc_auc: 0.7378 - val_loss: 0.5848 - val_pr_auc: 0.1782 - val_precision: 0.1739 - val_recall: 0.8000 - val_roc_auc: 0.8665 - val_combined: 0.3647
Epoch 22/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 172ms/step - loss: 0.6431 - pr_auc: 0.2484 - precision: 0.3122 - recall: 0.5086 - roc_auc: 0.7298 - val_loss: 0.5910 - val_pr_auc: 0.1737 - val_precision: 0.1600 - val_recall: 0.8000 - val_roc_auc: 0.8541 - val_combined: 0.3616
Epoch 23/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6324 - pr_auc: 0.2580 - precision: 0.2929 - recall: 0.6034 - roc_auc: 0.7500 - val_loss: 0.5880 - val_pr_auc: 0.1526 - val_precision: 0.1633 - val_recall: 0.8000 - val_roc_auc: 0.8514 - val_combined: 0.3468
Epoch 24/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 199ms/step - loss: 0.6362 - pr_auc: 0.2422 - precision: 0.2571 - recall: 0.5431 - roc_auc: 0.7319 - val_loss: 0.6383 - val_pr_auc: 0.1181 - val_precision: 0.1316 - val_recall: 1.0000 - val_roc_auc: 0.8077 - val_combined: 0.3827
Epoch 25/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 172ms/step - loss: 0.6379 - pr_auc: 0.2151 - precision: 0.2339 - recall: 0.5948 - roc_auc: 0.7234 - val_loss: 0.6085 - val_pr_auc: 0.1200 - val_precision: 0.1500 - val_recall: 0.9000 - val_roc_auc: 0.8071 - val_combined: 0.3540
Epoch 26/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.6471 - pr_auc: 0.2061 - precision: 0.2199 - recall: 0.5517 - roc_auc: 0.6902 - val_loss: 0.6005 - val_pr_auc: 0.1359 - val_precision: 0.1273 - val_recall: 0.7000 - val_roc_auc: 0.8234 - val_combined: 0.3052
Epoch 27/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.6347 - pr_auc: 0.2150 - precision: 0.2345 - recall: 0.5862 - roc_auc: 0.7314 - val_loss: 0.5877 - val_pr_auc: 0.1373 - val_precision: 0.1250 - val_recall: 0.6000 - val_roc_auc: 0.8313 - val_combined: 0.2761
Epoch 28/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 174ms/step - loss: 0.6248 - pr_auc: 0.2728 - precision: 0.3139 - recall: 0.6034 - roc_auc: 0.7543 - val_loss: 0.5923 - val_pr_auc: 0.1133 - val_precision: 0.1176 - val_recall: 0.6000 - val_roc_auc: 0.8099 - val_combined: 0.2593
Epoch 29/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6249 - pr_auc: 0.2678 - precision: 0.3093 - recall: 0.6293 - roc_auc: 0.7349 - val_loss: 0.5866 - val_pr_auc: 0.1536 - val_precision: 0.1250 - val_recall: 0.6000 - val_roc_auc: 0.8440 - val_combined: 0.2875
Epoch 30/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.6105 - pr_auc: 0.2780 - precision: 0.3445 - recall: 0.6207 - roc_auc: 0.7836 - val_loss: 0.5880 - val_pr_auc: 0.1385 - val_precision: 0.1250 - val_recall: 0.6000 - val_roc_auc: 0.8341 - val_combined: 0.2769
Epoch 31/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 173ms/step - loss: 0.6165 - pr_auc: 0.2656 - precision: 0.3333 - recall: 0.6034 - roc_auc: 0.7494 - val_loss: 0.5874 - val_pr_auc: 0.1159 - val_precision: 0.1600 - val_recall: 0.8000 - val_roc_auc: 0.8157 - val_combined: 0.3211
Epoch 32/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6136 - pr_auc: 0.2552 - precision: 0.3271 - recall: 0.6034 - roc_auc: 0.7573 - val_loss: 0.5934 - val_pr_auc: 0.1120 - val_precision: 0.1176 - val_recall: 0.6000 - val_roc_auc: 0.8085 - val_combined: 0.2584
Epoch 33/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 199ms/step - loss: 0.6099 - pr_auc: 0.2787 - precision: 0.3209 - recall: 0.5948 - roc_auc: 0.7595 - val_loss: 0.5816 - val_pr_auc: 0.1204 - val_precision: 0.1333 - val_recall: 0.6000 - val_roc_auc: 0.8228 - val_combined: 0.2643
Epoch 34/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 172ms/step - loss: 0.5925 - pr_auc: 0.3169 - precision: 0.3561 - recall: 0.6293 - roc_auc: 0.8094 - val_loss: 0.5824 - val_pr_auc: 0.1548 - val_precision: 0.1304 - val_recall: 0.6000 - val_roc_auc: 0.8462 - val_combined: 0.2883
Epoch 35/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.6009 - pr_auc: 0.2753 - precision: 0.3488 - recall: 0.6466 - roc_auc: 0.7476 - val_loss: 0.5876 - val_pr_auc: 0.1334 - val_precision: 0.1765 - val_recall: 0.9000 - val_roc_auc: 0.8346 - val_combined: 0.3634
Epoch 36/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6023 - pr_auc: 0.2691 - precision: 0.3427 - recall: 0.6293 - roc_auc: 0.7683 - val_loss: 0.5903 - val_pr_auc: 0.1341 - val_precision: 0.1698 - val_recall: 0.9000 - val_roc_auc: 0.8327 - val_combined: 0.3639
Epoch 37/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 188ms/step - loss: 0.5939 - pr_auc: 0.2959 - precision: 0.3349 - recall: 0.6034 - roc_auc: 0.7830 - val_loss: 0.5671 - val_pr_auc: 0.1111 - val_precision: 0.1053 - val_recall: 0.4000 - val_roc_auc: 0.8008 - val_combined: 0.1977
Epoch 38/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 182ms/step - loss: 0.5974 - pr_auc: 0.2975 - precision: 0.3272 - recall: 0.6121 - roc_auc: 0.7618 - val_loss: 0.5612 - val_pr_auc: 0.1368 - val_precision: 0.1579 - val_recall: 0.6000 - val_roc_auc: 0.8473 - val_combined: 0.2757
Epoch 39/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6301 - pr_auc: 0.1962 - precision: 0.2551 - recall: 0.5431 - roc_auc: 0.6900 - val_loss: 0.6623 - val_pr_auc: 0.1562 - val_precision: 0.1299 - val_recall: 1.0000 - val_roc_auc: 0.8516 - val_combined: 0.4094
Epoch 40/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 187ms/step - loss: 0.6111 - pr_auc: 0.2133 - precision: 0.2323 - recall: 0.6207 - roc_auc: 0.7335 - val_loss: 0.6323 - val_pr_auc: 0.1369 - val_precision: 0.1471 - val_recall: 1.0000 - val_roc_auc: 0.8352 - val_combined: 0.3958
Epoch 41/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 183ms/step - loss: 0.5972 - pr_auc: 0.2716 - precision: 0.2899 - recall: 0.5948 - roc_auc: 0.7485 - val_loss: 0.5990 - val_pr_auc: 0.1427 - val_precision: 0.1754 - val_recall: 1.0000 - val_roc_auc: 0.8434 - val_combined: 0.3999
Epoch 42/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5941 - pr_auc: 0.2753 - precision: 0.3008 - recall: 0.6379 - roc_auc: 0.7493 - val_loss: 0.5962 - val_pr_auc: 0.1429 - val_precision: 0.1818 - val_recall: 1.0000 - val_roc_auc: 0.8467 - val_combined: 0.4000
Epoch 43/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 193ms/step - loss: 0.6041 - pr_auc: 0.2290 - precision: 0.2806 - recall: 0.6121 - roc_auc: 0.7431 - val_loss: 0.6015 - val_pr_auc: 0.1155 - val_precision: 0.1786 - val_recall: 1.0000 - val_roc_auc: 0.8143 - val_combined: 0.3809
Epoch 44/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 179ms/step - loss: 0.5855 - pr_auc: 0.3088 - precision: 0.3160 - recall: 0.6293 - roc_auc: 0.7702 - val_loss: 0.5891 - val_pr_auc: 0.1368 - val_precision: 0.1800 - val_recall: 0.9000 - val_roc_auc: 0.8379 - val_combined: 0.3658
Epoch 45/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.5865 - pr_auc: 0.2912 - precision: 0.3510 - recall: 0.6293 - roc_auc: 0.7565 - val_loss: 0.5899 - val_pr_auc: 0.1411 - val_precision: 0.1633 - val_recall: 0.8000 - val_roc_auc: 0.8407 - val_combined: 0.3388
Epoch 46/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 200ms/step - loss: 0.5749 - pr_auc: 0.3375 - precision: 0.3425 - recall: 0.6466 - roc_auc: 0.7734 - val_loss: 0.5884 - val_pr_auc: 0.1402 - val_precision: 0.1837 - val_recall: 0.9000 - val_roc_auc: 0.8423 - val_combined: 0.3682
Epoch 47/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 173ms/step - loss: 0.5734 - pr_auc: 0.3105 - precision: 0.3524 - recall: 0.6379 - roc_auc: 0.7764 - val_loss: 0.5819 - val_pr_auc: 0.1508 - val_precision: 0.1333 - val_recall: 0.6000 - val_roc_auc: 0.8508 - val_combined: 0.2855
Epoch 48/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 11s 186ms/step - loss: 0.5796 - pr_auc: 0.2913 - precision: 0.3663 - recall: 0.6379 - roc_auc: 0.7585 - val_loss: 0.5891 - val_pr_auc: 0.1444 - val_precision: 0.1489 - val_recall: 0.7000 - val_roc_auc: 0.8445 - val_combined: 0.3111
Epoch 49/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5691 - pr_auc: 0.3255 - precision: 0.3695 - recall: 0.6466 - roc_auc: 0.7826 - val_loss: 0.5842 - val_pr_auc: 0.1241 - val_precision: 0.1333 - val_recall: 0.6000 - val_roc_auc: 0.8291 - val_combined: 0.2668
Epoch 50/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 203ms/step - loss: 0.5736 - pr_auc: 0.3276 - precision: 0.3365 - recall: 0.6121 - roc_auc: 0.7638 - val_loss: 0.5754 - val_pr_auc: 0.1615 - val_precision: 0.2000 - val_recall: 0.9000 - val_roc_auc: 0.8643 - val_combined: 0.3831
Epoch 51/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 173ms/step - loss: 0.6171 - pr_auc: 0.2157 - precision: 0.2353 - recall: 0.5862 - roc_auc: 0.6767 - val_loss: 0.6314 - val_pr_auc: 0.1164 - val_precision: 0.1404 - val_recall: 0.8000 - val_roc_auc: 0.8047 - val_combined: 0.3215
Epoch 52/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.5940 - pr_auc: 0.2248 - precision: 0.2708 - recall: 0.6466 - roc_auc: 0.7203 - val_loss: 0.6063 - val_pr_auc: 0.1084 - val_precision: 0.1250 - val_recall: 0.6000 - val_roc_auc: 0.8011 - val_combined: 0.2559
Epoch 53/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5682 - pr_auc: 0.3041 - precision: 0.3217 - recall: 0.6379 - roc_auc: 0.7820 - val_loss: 0.5921 - val_pr_auc: 0.1243 - val_precision: 0.1333 - val_recall: 0.6000 - val_roc_auc: 0.8294 - val_combined: 0.2670
Epoch 54/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 174ms/step - loss: 0.5661 - pr_auc: 0.3234 - precision: 0.3695 - recall: 0.6466 - roc_auc: 0.7744 - val_loss: 0.5867 - val_pr_auc: 0.1168 - val_precision: 0.1395 - val_recall: 0.6000 - val_roc_auc: 0.8154 - val_combined: 0.2618
Epoch 55/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5624 - pr_auc: 0.3148 - precision: 0.3676 - recall: 0.6466 - roc_auc: 0.7658 - val_loss: 0.5827 - val_pr_auc: 0.1189 - val_precision: 0.1429 - val_recall: 0.6000 - val_roc_auc: 0.8170 - val_combined: 0.2633
Epoch 56/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 203ms/step - loss: 0.5609 - pr_auc: 0.3166 - precision: 0.4121 - recall: 0.6466 - roc_auc: 0.7787 - val_loss: 0.5846 - val_pr_auc: 0.1190 - val_precision: 0.1395 - val_recall: 0.6000 - val_roc_auc: 0.8187 - val_combined: 0.2633
Epoch 57/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 174ms/step - loss: 0.5452 - pr_auc: 0.3959 - precision: 0.3946 - recall: 0.6293 - roc_auc: 0.8039 - val_loss: 0.5281 - val_pr_auc: 0.1342 - val_precision: 0.1481 - val_recall: 0.4000 - val_roc_auc: 0.8415 - val_combined: 0.2139
Epoch 58/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5643 - pr_auc: 0.3378 - precision: 0.3936 - recall: 0.6379 - roc_auc: 0.7504 - val_loss: 0.5454 - val_pr_auc: 0.1387 - val_precision: 0.1622 - val_recall: 0.6000 - val_roc_auc: 0.8475 - val_combined: 0.2771
Epoch 59/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.5542 - pr_auc: 0.3907 - precision: 0.4464 - recall: 0.6466 - roc_auc: 0.7643 - val_loss: 0.5642 - val_pr_auc: 0.1676 - val_precision: 0.1538 - val_recall: 0.6000 - val_roc_auc: 0.8714 - val_combined: 0.2974
Epoch 60/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - loss: 0.6174 - pr_auc: 0.2447 - precision: 0.2737 - recall: 0.4483 - roc_auc: 0.7088 - val_loss: 0.6083 - val_pr_auc: 0.1388 - val_precision: 0.2000 - val_recall: 1.0000 - val_roc_auc: 0.8423 - val_combined: 0.3971
Epoch 61/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5619 - pr_auc: 0.3002 - precision: 0.3261 - recall: 0.6466 - roc_auc: 0.7798 - val_loss: 0.5767 - val_pr_auc: 0.1250 - val_precision: 0.1500 - val_recall: 0.6000 - val_roc_auc: 0.8297 - val_combined: 0.2675
Epoch 62/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.5480 - pr_auc: 0.3751 - precision: 0.3978 - recall: 0.6379 - roc_auc: 0.7753 - val_loss: 0.5973 - val_pr_auc: 0.1205 - val_precision: 0.1364 - val_recall: 0.6000 - val_roc_auc: 0.8217 - val_combined: 0.2643
Epoch 63/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 174ms/step - loss: 0.5638 - pr_auc: 0.3463 - precision: 0.4395 - recall: 0.5948 - roc_auc: 0.7712 - val_loss: 0.6272 - val_pr_auc: 0.1318 - val_precision: 0.1818 - val_recall: 1.0000 - val_roc_auc: 0.8335 - val_combined: 0.3923
Epoch 64/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5551 - pr_auc: 0.3028 - precision: 0.3233 - recall: 0.6466 - roc_auc: 0.7727 - val_loss: 0.6066 - val_pr_auc: 0.1288 - val_precision: 0.2000 - val_recall: 1.0000 - val_roc_auc: 0.8368 - val_combined: 0.3902
Epoch 65/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5668 - pr_auc: 0.3547 - precision: 0.4151 - recall: 0.5690 - roc_auc: 0.7510 - val_loss: 0.5955 - val_pr_auc: 0.1542 - val_precision: 0.1957 - val_recall: 0.9000 - val_roc_auc: 0.8577 - val_combined: 0.3779
Epoch 66/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 173ms/step - loss: 0.5535 - pr_auc: 0.4265 - precision: 0.4331 - recall: 0.5862 - roc_auc: 0.7648 - val_loss: 0.5622 - val_pr_auc: 0.1444 - val_precision: 0.1500 - val_recall: 0.6000 - val_roc_auc: 0.8552 - val_combined: 0.2811
Epoch 67/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.5686 - pr_auc: 0.3626 - precision: 0.4552 - recall: 0.5690 - roc_auc: 0.7391 - val_loss: 0.5901 - val_pr_auc: 0.1417 - val_precision: 0.1429 - val_recall: 0.6000 - val_roc_auc: 0.8516 - val_combined: 0.2792
Epoch 68/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 200ms/step - loss: 0.5564 - pr_auc: 0.3927 - precision: 0.4323 - recall: 0.5776 - roc_auc: 0.7660 - val_loss: 0.5765 - val_pr_auc: 0.1776 - val_precision: 0.2195 - val_recall: 0.9000 - val_roc_auc: 0.8780 - val_combined: 0.3943
Epoch 69/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 173ms/step - loss: 0.5811 - pr_auc: 0.3106 - precision: 0.3459 - recall: 0.5517 - roc_auc: 0.7285 - val_loss: 0.5948 - val_pr_auc: 0.1247 - val_precision: 0.1333 - val_recall: 0.6000 - val_roc_auc: 0.8245 - val_combined: 0.2673
Epoch 69: early stopping
Restoring model weights from the end of the best epoch: 19.
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 56ms/step

Running seed 146

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 19s 223ms/step - loss: 0.6942 - pr_auc: 0.0668 - precision: 0.0609 - recall: 0.2241 - roc_auc: 0.4332 - val_loss: 0.6933 - val_pr_auc: 0.0399 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.4093 - val_combined: 0.0279
Epoch 2/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 197ms/step - loss: 0.6916 - pr_auc: 0.1070 - precision: 0.1230 - recall: 0.3362 - roc_auc: 0.5744 - val_loss: 0.6985 - val_pr_auc: 0.0603 - val_precision: 0.1111 - val_recall: 1.0000 - val_roc_auc: 0.6154 - val_combined: 0.3422
Epoch 3/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - loss: 0.6886 - pr_auc: 0.1204 - precision: 0.0979 - recall: 0.5345 - roc_auc: 0.5929 - val_loss: 0.7068 - val_pr_auc: 0.0815 - val_precision: 0.1000 - val_recall: 1.0000 - val_roc_auc: 0.7198 - val_combined: 0.3570
Epoch 4/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 197ms/step - loss: 0.6733 - pr_auc: 0.2388 - precision: 0.1354 - recall: 0.6293 - roc_auc: 0.6979 - val_loss: 0.7519 - val_pr_auc: 0.0832 - val_precision: 0.0870 - val_recall: 1.0000 - val_roc_auc: 0.7286 - val_combined: 0.3583
Epoch 5/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6577 - pr_auc: 0.2351 - precision: 0.1409 - recall: 0.6293 - roc_auc: 0.7085 - val_loss: 0.7701 - val_pr_auc: 0.1006 - val_precision: 0.1010 - val_recall: 1.0000 - val_roc_auc: 0.7816 - val_combined: 0.3704
Epoch 6/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 173ms/step - loss: 0.6443 - pr_auc: 0.2371 - precision: 0.1584 - recall: 0.6293 - roc_auc: 0.7013 - val_loss: 0.7313 - val_pr_auc: 0.1979 - val_precision: 0.1562 - val_recall: 1.0000 - val_roc_auc: 0.8703 - val_combined: 0.4386
Epoch 7/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6364 - pr_auc: 0.2353 - precision: 0.1850 - recall: 0.5948 - roc_auc: 0.7082 - val_loss: 0.8015 - val_pr_auc: 0.1517 - val_precision: 0.1099 - val_recall: 1.0000 - val_roc_auc: 0.8407 - val_combined: 0.4062
Epoch 8/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 197ms/step - loss: 0.6243 - pr_auc: 0.2576 - precision: 0.1901 - recall: 0.6638 - roc_auc: 0.7488 - val_loss: 0.8008 - val_pr_auc: 0.1415 - val_precision: 0.1205 - val_recall: 1.0000 - val_roc_auc: 0.8319 - val_combined: 0.3990
Epoch 9/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 173ms/step - loss: 0.6248 - pr_auc: 0.2110 - precision: 0.2175 - recall: 0.6638 - roc_auc: 0.7349 - val_loss: 0.7590 - val_pr_auc: 0.1467 - val_precision: 0.1515 - val_recall: 1.0000 - val_roc_auc: 0.8525 - val_combined: 0.4027
Epoch 10/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6286 - pr_auc: 0.1900 - precision: 0.1877 - recall: 0.6552 - roc_auc: 0.7164 - val_loss: 0.8471 - val_pr_auc: 0.1191 - val_precision: 0.1087 - val_recall: 1.0000 - val_roc_auc: 0.8121 - val_combined: 0.3834
Epoch 11/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.6196 - pr_auc: 0.2475 - precision: 0.2028 - recall: 0.6293 - roc_auc: 0.7303 - val_loss: 0.7365 - val_pr_auc: 0.1321 - val_precision: 0.1852 - val_recall: 1.0000 - val_roc_auc: 0.8365 - val_combined: 0.3925
Epoch 12/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 172ms/step - loss: 0.6199 - pr_auc: 0.2218 - precision: 0.2271 - recall: 0.6207 - roc_auc: 0.7067 - val_loss: 0.8178 - val_pr_auc: 0.1274 - val_precision: 0.1205 - val_recall: 1.0000 - val_roc_auc: 0.8184 - val_combined: 0.3892
Epoch 13/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.6135 - pr_auc: 0.2260 - precision: 0.2110 - recall: 0.6293 - roc_auc: 0.7148 - val_loss: 0.7359 - val_pr_auc: 0.1272 - val_precision: 0.1731 - val_recall: 0.9000 - val_roc_auc: 0.8313 - val_combined: 0.3590
Epoch 14/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6051 - pr_auc: 0.2610 - precision: 0.2467 - recall: 0.6379 - roc_auc: 0.7642 - val_loss: 0.8023 - val_pr_auc: 0.1151 - val_precision: 0.1351 - val_recall: 1.0000 - val_roc_auc: 0.8088 - val_combined: 0.3805
Epoch 15/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 172ms/step - loss: 0.6037 - pr_auc: 0.2534 - precision: 0.2426 - recall: 0.6379 - roc_auc: 0.7234 - val_loss: 0.7412 - val_pr_auc: 0.1223 - val_precision: 0.1731 - val_recall: 0.9000 - val_roc_auc: 0.8253 - val_combined: 0.3556
Epoch 16/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5932 - pr_auc: 0.3083 - precision: 0.2618 - recall: 0.6207 - roc_auc: 0.7353 - val_loss: 0.7531 - val_pr_auc: 0.1196 - val_precision: 0.1818 - val_recall: 1.0000 - val_roc_auc: 0.8214 - val_combined: 0.3837
Epoch 17/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.5895 - pr_auc: 0.2762 - precision: 0.2606 - recall: 0.6379 - roc_auc: 0.7442 - val_loss: 0.7869 - val_pr_auc: 0.1126 - val_precision: 0.1613 - val_recall: 1.0000 - val_roc_auc: 0.8096 - val_combined: 0.3788
Epoch 18/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 172ms/step - loss: 0.6020 - pr_auc: 0.2308 - precision: 0.2599 - recall: 0.6207 - roc_auc: 0.7171 - val_loss: 0.7656 - val_pr_auc: 0.1160 - val_precision: 0.1754 - val_recall: 1.0000 - val_roc_auc: 0.8148 - val_combined: 0.3812
Epoch 19/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 197ms/step - loss: 0.5853 - pr_auc: 0.2725 - precision: 0.2714 - recall: 0.6293 - roc_auc: 0.7754 - val_loss: 0.7239 - val_pr_auc: 0.1220 - val_precision: 0.1333 - val_recall: 0.6000 - val_roc_auc: 0.8247 - val_combined: 0.2654
Epoch 20/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.5986 - pr_auc: 0.2751 - precision: 0.2509 - recall: 0.6034 - roc_auc: 0.7257 - val_loss: 0.8478 - val_pr_auc: 0.0913 - val_precision: 0.1250 - val_recall: 1.0000 - val_roc_auc: 0.7492 - val_combined: 0.3639
Epoch 21/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 173ms/step - loss: 0.5950 - pr_auc: 0.2764 - precision: 0.2229 - recall: 0.6379 - roc_auc: 0.7434 - val_loss: 0.7633 - val_pr_auc: 0.1017 - val_precision: 0.1273 - val_recall: 0.7000 - val_roc_auc: 0.7802 - val_combined: 0.2812
Epoch 22/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5900 - pr_auc: 0.2681 - precision: 0.2574 - recall: 0.6034 - roc_auc: 0.7356 - val_loss: 0.7343 - val_pr_auc: 0.1157 - val_precision: 0.1277 - val_recall: 0.6000 - val_roc_auc: 0.8107 - val_combined: 0.2610
Epoch 23/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.5904 - pr_auc: 0.3060 - precision: 0.2653 - recall: 0.5603 - roc_auc: 0.7509 - val_loss: 0.7635 - val_pr_auc: 0.0996 - val_precision: 0.1111 - val_recall: 0.6000 - val_roc_auc: 0.7745 - val_combined: 0.2497
Epoch 24/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 173ms/step - loss: 0.5755 - pr_auc: 0.3551 - precision: 0.2794 - recall: 0.5948 - roc_auc: 0.7595 - val_loss: 0.7245 - val_pr_auc: 0.1140 - val_precision: 0.1333 - val_recall: 0.6000 - val_roc_auc: 0.8066 - val_combined: 0.2598
Epoch 25/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.5698 - pr_auc: 0.3853 - precision: 0.3318 - recall: 0.6293 - roc_auc: 0.7520 - val_loss: 0.7115 - val_pr_auc: 0.1046 - val_precision: 0.1277 - val_recall: 0.6000 - val_roc_auc: 0.7846 - val_combined: 0.2532
Epoch 26/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 197ms/step - loss: 0.5489 - pr_auc: 0.4887 - precision: 0.3706 - recall: 0.6293 - roc_auc: 0.7864 - val_loss: 0.6809 - val_pr_auc: 0.1003 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7698 - val_combined: 0.0702
Epoch 27/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - loss: 0.5429 - pr_auc: 0.4532 - precision: 0.3706 - recall: 0.6293 - roc_auc: 0.7842 - val_loss: 0.6583 - val_pr_auc: 0.1071 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7863 - val_combined: 0.0750
Epoch 28/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.5386 - pr_auc: 0.4942 - precision: 0.3956 - recall: 0.6207 - roc_auc: 0.7774 - val_loss: 0.6142 - val_pr_auc: 0.1180 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.8104 - val_combined: 0.0826
Epoch 29/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.6083 - pr_auc: 0.3416 - precision: 0.3481 - recall: 0.4052 - roc_auc: 0.7011 - val_loss: 0.7136 - val_pr_auc: 0.0919 - val_precision: 0.0851 - val_recall: 0.4000 - val_roc_auc: 0.7492 - val_combined: 0.1843
Epoch 30/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 174ms/step - loss: 0.5525 - pr_auc: 0.3803 - precision: 0.3350 - recall: 0.5690 - roc_auc: 0.7724 - val_loss: 0.7182 - val_pr_auc: 0.1007 - val_precision: 0.1250 - val_recall: 0.6000 - val_roc_auc: 0.7720 - val_combined: 0.2505
Epoch 31/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5519 - pr_auc: 0.4364 - precision: 0.4400 - recall: 0.5690 - roc_auc: 0.7534 - val_loss: 0.6951 - val_pr_auc: 0.1008 - val_precision: 0.0256 - val_recall: 0.1000 - val_roc_auc: 0.7706 - val_combined: 0.1006
Epoch 32/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.5399 - pr_auc: 0.5106 - precision: 0.4408 - recall: 0.5776 - roc_auc: 0.7843 - val_loss: 0.7569 - val_pr_auc: 0.0986 - val_precision: 0.1154 - val_recall: 0.6000 - val_roc_auc: 0.7657 - val_combined: 0.2490
Epoch 33/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 172ms/step - loss: 0.5585 - pr_auc: 0.3890 - precision: 0.3090 - recall: 0.6207 - roc_auc: 0.7224 - val_loss: 0.6782 - val_pr_auc: 0.1257 - val_precision: 0.1538 - val_recall: 0.6000 - val_roc_auc: 0.8269 - val_combined: 0.2680
Epoch 34/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5768 - pr_auc: 0.3269 - precision: 0.3164 - recall: 0.4828 - roc_auc: 0.7296 - val_loss: 0.6427 - val_pr_auc: 0.1077 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7898 - val_combined: 0.0754
Epoch 35/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 204ms/step - loss: 0.5322 - pr_auc: 0.4327 - precision: 0.4094 - recall: 0.6034 - roc_auc: 0.8247 - val_loss: 0.7335 - val_pr_auc: 0.1241 - val_precision: 0.2083 - val_recall: 1.0000 - val_roc_auc: 0.8214 - val_combined: 0.3869
Epoch 36/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 174ms/step - loss: 0.5711 - pr_auc: 0.3437 - precision: 0.3173 - recall: 0.5690 - roc_auc: 0.7046 - val_loss: 0.8005 - val_pr_auc: 0.1129 - val_precision: 0.1786 - val_recall: 1.0000 - val_roc_auc: 0.8049 - val_combined: 0.3790
Epoch 37/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5388 - pr_auc: 0.4148 - precision: 0.3349 - recall: 0.6293 - roc_auc: 0.7339 - val_loss: 0.6927 - val_pr_auc: 0.1181 - val_precision: 0.1429 - val_recall: 0.6000 - val_roc_auc: 0.8107 - val_combined: 0.2627
Epoch 38/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5274 - pr_auc: 0.4176 - precision: 0.4320 - recall: 0.6293 - roc_auc: 0.7754 - val_loss: 0.7226 - val_pr_auc: 0.0885 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7327 - val_combined: 0.0620
Epoch 39/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 174ms/step - loss: 0.5449 - pr_auc: 0.3136 - precision: 0.3544 - recall: 0.6293 - roc_auc: 0.7681 - val_loss: 0.6920 - val_pr_auc: 0.0951 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7580 - val_combined: 0.0666
Epoch 40/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.5162 - pr_auc: 0.4445 - precision: 0.4506 - recall: 0.6293 - roc_auc: 0.8038 - val_loss: 0.6733 - val_pr_auc: 0.0992 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7695 - val_combined: 0.0694
Epoch 41/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.5080 - pr_auc: 0.4671 - precision: 0.4899 - recall: 0.6293 - roc_auc: 0.8047 - val_loss: 0.6608 - val_pr_auc: 0.0951 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7593 - val_combined: 0.0666
Epoch 42/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 174ms/step - loss: 0.5050 - pr_auc: 0.5038 - precision: 0.4679 - recall: 0.6293 - roc_auc: 0.7865 - val_loss: 0.6353 - val_pr_auc: 0.0949 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7453 - val_combined: 0.0664
Epoch 43/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.4995 - pr_auc: 0.4764 - precision: 0.5139 - recall: 0.6379 - roc_auc: 0.8161 - val_loss: 0.6526 - val_pr_auc: 0.1137 - val_precision: 0.0690 - val_recall: 0.2000 - val_roc_auc: 0.8077 - val_combined: 0.1396
Epoch 44/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.5112 - pr_auc: 0.5067 - precision: 0.4506 - recall: 0.6293 - roc_auc: 0.7814 - val_loss: 0.7599 - val_pr_auc: 0.0815 - val_precision: 0.0426 - val_recall: 0.2000 - val_roc_auc: 0.7151 - val_combined: 0.1170
Epoch 45/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 174ms/step - loss: 0.5273 - pr_auc: 0.3900 - precision: 0.3614 - recall: 0.6293 - roc_auc: 0.7710 - val_loss: 0.6840 - val_pr_auc: 0.0905 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7453 - val_combined: 0.0634
Epoch 46/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 198ms/step - loss: 0.5227 - pr_auc: 0.4798 - precision: 0.4783 - recall: 0.5690 - roc_auc: 0.7684 - val_loss: 0.7521 - val_pr_auc: 0.0892 - val_precision: 0.0233 - val_recall: 0.1000 - val_roc_auc: 0.7371 - val_combined: 0.0924
Epoch 47/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 200ms/step - loss: 0.5229 - pr_auc: 0.3686 - precision: 0.4098 - recall: 0.6466 - roc_auc: 0.7682 - val_loss: 0.6838 - val_pr_auc: 0.0976 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7662 - val_combined: 0.0683
Epoch 48/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 174ms/step - loss: 0.5023 - pr_auc: 0.4877 - precision: 0.4867 - recall: 0.6293 - roc_auc: 0.7692 - val_loss: 0.6582 - val_pr_auc: 0.0987 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7720 - val_combined: 0.0691
Epoch 49/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.4818 - pr_auc: 0.5154 - precision: 0.5172 - recall: 0.6466 - roc_auc: 0.8247 - val_loss: 0.6480 - val_pr_auc: 0.0976 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7679 - val_combined: 0.0683
Epoch 50/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5631 - pr_auc: 0.2526 - precision: 0.3288 - recall: 0.6293 - roc_auc: 0.7631 - val_loss: 0.7134 - val_pr_auc: 0.1238 - val_precision: 0.1667 - val_recall: 0.7000 - val_roc_auc: 0.8198 - val_combined: 0.2967
Epoch 51/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 178ms/step - loss: 0.6489 - pr_auc: 0.1577 - precision: 0.2095 - recall: 0.5345 - roc_auc: 0.6905 - val_loss: 0.6084 - val_pr_auc: 0.1212 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.8214 - val_combined: 0.0848
Epoch 52/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5499 - pr_auc: 0.3565 - precision: 0.3317 - recall: 0.5862 - roc_auc: 0.7667 - val_loss: 0.7209 - val_pr_auc: 0.1029 - val_precision: 0.0976 - val_recall: 0.4000 - val_roc_auc: 0.7802 - val_combined: 0.1920
Epoch 53/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.5303 - pr_auc: 0.3291 - precision: 0.3934 - recall: 0.6207 - roc_auc: 0.7619 - val_loss: 0.6681 - val_pr_auc: 0.1025 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7758 - val_combined: 0.0718
Epoch 54/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 176ms/step - loss: 0.4930 - pr_auc: 0.5018 - precision: 0.4966 - recall: 0.6293 - roc_auc: 0.8167 - val_loss: 0.6599 - val_pr_auc: 0.0991 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7662 - val_combined: 0.0693
Epoch 55/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.4973 - pr_auc: 0.4434 - precision: 0.5141 - recall: 0.6293 - roc_auc: 0.7837 - val_loss: 0.6499 - val_pr_auc: 0.0996 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7701 - val_combined: 0.0697
Epoch 56/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.4854 - pr_auc: 0.5690 - precision: 0.5414 - recall: 0.6207 - roc_auc: 0.7989 - val_loss: 0.6421 - val_pr_auc: 0.0952 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7593 - val_combined: 0.0666
Epoch 56: early stopping
Restoring model weights from the end of the best epoch: 6.
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step

Running seed 162

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Epoch 1/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 18s 197ms/step - loss: 0.6949 - pr_auc: 0.0633 - precision: 0.0781 - recall: 0.9397 - roc_auc: 0.4089 - val_loss: 0.7026 - val_pr_auc: 0.0308 - val_precision: 0.0521 - val_recall: 1.0000 - val_roc_auc: 0.2121 - val_combined: 0.3216
Epoch 2/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 210ms/step - loss: 0.6934 - pr_auc: 0.0753 - precision: 0.0807 - recall: 0.8707 - roc_auc: 0.5098 - val_loss: 0.6974 - val_pr_auc: 0.0909 - val_precision: 0.0538 - val_recall: 1.0000 - val_roc_auc: 0.7253 - val_combined: 0.3636
Epoch 3/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 21s 465ms/step - loss: 0.6921 - pr_auc: 0.0897 - precision: 0.0903 - recall: 0.8621 - roc_auc: 0.5475 - val_loss: 0.6949 - val_pr_auc: 0.0395 - val_precision: 0.0761 - val_recall: 0.7000 - val_roc_auc: 0.3956 - val_combined: 0.2376
Epoch 4/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - loss: 0.6917 - pr_auc: 0.1054 - precision: 0.0856 - recall: 0.7241 - roc_auc: 0.5895 - val_loss: 0.6951 - val_pr_auc: 0.0550 - val_precision: 0.0862 - val_recall: 1.0000 - val_roc_auc: 0.5324 - val_combined: 0.3385
Epoch 5/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6900 - pr_auc: 0.1346 - precision: 0.0961 - recall: 0.7069 - roc_auc: 0.6251 - val_loss: 0.6967 - val_pr_auc: 0.0550 - val_precision: 0.0893 - val_recall: 1.0000 - val_roc_auc: 0.5665 - val_combined: 0.3385
Epoch 6/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.6852 - pr_auc: 0.2442 - precision: 0.1019 - recall: 0.7414 - roc_auc: 0.6595 - val_loss: 0.7050 - val_pr_auc: 0.0601 - val_precision: 0.0877 - val_recall: 1.0000 - val_roc_auc: 0.6066 - val_combined: 0.3421
Epoch 7/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 176ms/step - loss: 0.6827 - pr_auc: 0.2076 - precision: 0.1026 - recall: 0.6897 - roc_auc: 0.6441 - val_loss: 0.7125 - val_pr_auc: 0.0711 - val_precision: 0.0901 - val_recall: 1.0000 - val_roc_auc: 0.6720 - val_combined: 0.3497
Epoch 8/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.6717 - pr_auc: 0.2398 - precision: 0.1097 - recall: 0.6810 - roc_auc: 0.6806 - val_loss: 0.7364 - val_pr_auc: 0.0864 - val_precision: 0.0935 - val_recall: 1.0000 - val_roc_auc: 0.7418 - val_combined: 0.3605
Epoch 9/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.6663 - pr_auc: 0.1989 - precision: 0.1193 - recall: 0.6810 - roc_auc: 0.6828 - val_loss: 0.7472 - val_pr_auc: 0.1350 - val_precision: 0.1053 - val_recall: 1.0000 - val_roc_auc: 0.8272 - val_combined: 0.3945
Epoch 10/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 177ms/step - loss: 0.6558 - pr_auc: 0.2057 - precision: 0.1537 - recall: 0.6638 - roc_auc: 0.7138 - val_loss: 0.7418 - val_pr_auc: 0.1811 - val_precision: 0.1205 - val_recall: 1.0000 - val_roc_auc: 0.8777 - val_combined: 0.4268
Epoch 11/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.6471 - pr_auc: 0.2061 - precision: 0.1477 - recall: 0.6810 - roc_auc: 0.7072 - val_loss: 0.7941 - val_pr_auc: 0.1527 - val_precision: 0.1020 - val_recall: 1.0000 - val_roc_auc: 0.8538 - val_combined: 0.4069
Epoch 12/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.6434 - pr_auc: 0.1986 - precision: 0.1653 - recall: 0.6897 - roc_auc: 0.7206 - val_loss: 0.7387 - val_pr_auc: 0.1985 - val_precision: 0.1449 - val_recall: 1.0000 - val_roc_auc: 0.8712 - val_combined: 0.4390
Epoch 13/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 183ms/step - loss: 0.6272 - pr_auc: 0.2523 - precision: 0.1833 - recall: 0.6638 - roc_auc: 0.7350 - val_loss: 0.7372 - val_pr_auc: 0.1933 - val_precision: 0.1613 - val_recall: 1.0000 - val_roc_auc: 0.8799 - val_combined: 0.4353
Epoch 14/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.6306 - pr_auc: 0.2513 - precision: 0.1966 - recall: 0.6034 - roc_auc: 0.7130 - val_loss: 0.7542 - val_pr_auc: 0.1551 - val_precision: 0.1515 - val_recall: 1.0000 - val_roc_auc: 0.8503 - val_combined: 0.4086
Epoch 15/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 217ms/step - loss: 0.6182 - pr_auc: 0.2599 - precision: 0.2010 - recall: 0.6983 - roc_auc: 0.7288 - val_loss: 0.7372 - val_pr_auc: 0.1678 - val_precision: 0.1754 - val_recall: 1.0000 - val_roc_auc: 0.8651 - val_combined: 0.4174
Epoch 16/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 185ms/step - loss: 0.6239 - pr_auc: 0.2471 - precision: 0.1830 - recall: 0.6121 - roc_auc: 0.7190 - val_loss: 0.7895 - val_pr_auc: 0.1457 - val_precision: 0.1370 - val_recall: 1.0000 - val_roc_auc: 0.8423 - val_combined: 0.4020
Epoch 17/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 190ms/step - loss: 0.6168 - pr_auc: 0.2279 - precision: 0.1825 - recall: 0.6466 - roc_auc: 0.7291 - val_loss: 0.6867 - val_pr_auc: 0.1660 - val_precision: 0.1500 - val_recall: 0.6000 - val_roc_auc: 0.8684 - val_combined: 0.2962
Epoch 18/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.6148 - pr_auc: 0.2440 - precision: 0.2085 - recall: 0.5948 - roc_auc: 0.7246 - val_loss: 0.7387 - val_pr_auc: 0.1332 - val_precision: 0.1923 - val_recall: 1.0000 - val_roc_auc: 0.8385 - val_combined: 0.3932
Epoch 19/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 191ms/step - loss: 0.6067 - pr_auc: 0.2525 - precision: 0.1934 - recall: 0.6552 - roc_auc: 0.7387 - val_loss: 0.8240 - val_pr_auc: 0.1232 - val_precision: 0.1282 - val_recall: 1.0000 - val_roc_auc: 0.8159 - val_combined: 0.3862
Epoch 20/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 185ms/step - loss: 0.6011 - pr_auc: 0.2368 - precision: 0.2088 - recall: 0.6552 - roc_auc: 0.7400 - val_loss: 0.7642 - val_pr_auc: 0.1032 - val_precision: 0.1579 - val_recall: 0.9000 - val_roc_auc: 0.7849 - val_combined: 0.3423
Epoch 21/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.5931 - pr_auc: 0.2939 - precision: 0.2281 - recall: 0.6293 - roc_auc: 0.7483 - val_loss: 0.7378 - val_pr_auc: 0.1118 - val_precision: 0.1250 - val_recall: 0.6000 - val_roc_auc: 0.8030 - val_combined: 0.2582
Epoch 22/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 10s 202ms/step - loss: 0.5802 - pr_auc: 0.3463 - precision: 0.2671 - recall: 0.6379 - roc_auc: 0.7445 - val_loss: 0.7430 - val_pr_auc: 0.1168 - val_precision: 0.1458 - val_recall: 0.7000 - val_roc_auc: 0.8126 - val_combined: 0.2918
Epoch 23/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 176ms/step - loss: 0.5969 - pr_auc: 0.2870 - precision: 0.2623 - recall: 0.5517 - roc_auc: 0.7148 - val_loss: 0.7361 - val_pr_auc: 0.1037 - val_precision: 0.1224 - val_recall: 0.6000 - val_roc_auc: 0.7805 - val_combined: 0.2526
Epoch 24/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.5664 - pr_auc: 0.5043 - precision: 0.3395 - recall: 0.6293 - roc_auc: 0.7591 - val_loss: 0.7298 - val_pr_auc: 0.1057 - val_precision: 0.1887 - val_recall: 1.0000 - val_roc_auc: 0.7890 - val_combined: 0.3740
Epoch 25/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.5555 - pr_auc: 0.4677 - precision: 0.3551 - recall: 0.6552 - roc_auc: 0.8040 - val_loss: 0.7283 - val_pr_auc: 0.0955 - val_precision: 0.0851 - val_recall: 0.4000 - val_roc_auc: 0.7596 - val_combined: 0.1868
Epoch 26/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 176ms/step - loss: 0.5657 - pr_auc: 0.3929 - precision: 0.2897 - recall: 0.6293 - roc_auc: 0.7406 - val_loss: 0.7015 - val_pr_auc: 0.0970 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7624 - val_combined: 0.0679
Epoch 27/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.5470 - pr_auc: 0.4549 - precision: 0.3575 - recall: 0.6379 - roc_auc: 0.7776 - val_loss: 0.6714 - val_pr_auc: 0.1113 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.8016 - val_combined: 0.0779
Epoch 28/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.5415 - pr_auc: 0.5002 - precision: 0.3663 - recall: 0.6379 - roc_auc: 0.7682 - val_loss: 0.6623 - val_pr_auc: 0.1014 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7794 - val_combined: 0.0710
Epoch 29/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 178ms/step - loss: 0.5350 - pr_auc: 0.5022 - precision: 0.4327 - recall: 0.6379 - roc_auc: 0.7781 - val_loss: 0.6655 - val_pr_auc: 0.0994 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7720 - val_combined: 0.0696
Epoch 30/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 204ms/step - loss: 0.5320 - pr_auc: 0.4661 - precision: 0.3596 - recall: 0.6293 - roc_auc: 0.7884 - val_loss: 0.8992 - val_pr_auc: 0.0701 - val_precision: 0.1200 - val_recall: 0.9000 - val_roc_auc: 0.6558 - val_combined: 0.3190
Epoch 31/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.5547 - pr_auc: 0.3925 - precision: 0.2922 - recall: 0.6121 - roc_auc: 0.7349 - val_loss: 0.7757 - val_pr_auc: 0.0976 - val_precision: 0.1346 - val_recall: 0.7000 - val_roc_auc: 0.7668 - val_combined: 0.2783
Epoch 32/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 178ms/step - loss: 0.5730 - pr_auc: 0.3460 - precision: 0.3856 - recall: 0.5086 - roc_auc: 0.7455 - val_loss: 0.8355 - val_pr_auc: 0.0934 - val_precision: 0.1471 - val_recall: 1.0000 - val_roc_auc: 0.7541 - val_combined: 0.3654
Epoch 33/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.5417 - pr_auc: 0.4529 - precision: 0.3382 - recall: 0.5948 - roc_auc: 0.7590 - val_loss: 0.6610 - val_pr_auc: 0.1092 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7973 - val_combined: 0.0764
Epoch 34/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 200ms/step - loss: 0.5458 - pr_auc: 0.4309 - precision: 0.4062 - recall: 0.5603 - roc_auc: 0.7488 - val_loss: 0.6968 - val_pr_auc: 0.1013 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7764 - val_combined: 0.0709
Epoch 35/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - loss: 0.5171 - pr_auc: 0.4986 - precision: 0.4277 - recall: 0.6379 - roc_auc: 0.7721 - val_loss: 0.6685 - val_pr_auc: 0.0983 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7750 - val_combined: 0.0688
Epoch 36/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 204ms/step - loss: 0.5012 - pr_auc: 0.5513 - precision: 0.4405 - recall: 0.6379 - roc_auc: 0.7994 - val_loss: 0.6299 - val_pr_auc: 0.1168 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.8137 - val_combined: 0.0818
Epoch 37/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 203ms/step - loss: 0.5323 - pr_auc: 0.4801 - precision: 0.4238 - recall: 0.5517 - roc_auc: 0.7842 - val_loss: 0.7433 - val_pr_auc: 0.1061 - val_precision: 0.0930 - val_recall: 0.4000 - val_roc_auc: 0.7904 - val_combined: 0.1943
Epoch 38/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 175ms/step - loss: 0.5074 - pr_auc: 0.5242 - precision: 0.4412 - recall: 0.6466 - roc_auc: 0.7849 - val_loss: 0.6198 - val_pr_auc: 0.1314 - val_precision: 0.0526 - val_recall: 0.1000 - val_roc_auc: 0.8379 - val_combined: 0.1220
Epoch 39/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 199ms/step - loss: 0.5375 - pr_auc: 0.4564 - precision: 0.4662 - recall: 0.5345 - roc_auc: 0.7264 - val_loss: 0.7091 - val_pr_auc: 0.0906 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7448 - val_combined: 0.0634
Epoch 40/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.5240 - pr_auc: 0.4274 - precision: 0.3822 - recall: 0.6293 - roc_auc: 0.7560 - val_loss: 0.6642 - val_pr_auc: 0.1065 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7942 - val_combined: 0.0746
Epoch 41/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 180ms/step - loss: 0.5411 - pr_auc: 0.3817 - precision: 0.3879 - recall: 0.5517 - roc_auc: 0.7514 - val_loss: 0.7355 - val_pr_auc: 0.0878 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7294 - val_combined: 0.0614
Epoch 42/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 194ms/step - loss: 0.5409 - pr_auc: 0.3343 - precision: 0.3583 - recall: 0.5776 - roc_auc: 0.7803 - val_loss: 0.6050 - val_pr_auc: 0.0850 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7343 - val_combined: 0.0595
Epoch 43/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.5761 - pr_auc: 0.2777 - precision: 0.3851 - recall: 0.4914 - roc_auc: 0.7384 - val_loss: 0.8549 - val_pr_auc: 0.0993 - val_precision: 0.1786 - val_recall: 1.0000 - val_roc_auc: 0.7670 - val_combined: 0.3695
Epoch 44/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 184ms/step - loss: 0.5266 - pr_auc: 0.4508 - precision: 0.4490 - recall: 0.5690 - roc_auc: 0.7615 - val_loss: 0.6909 - val_pr_auc: 0.1074 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7942 - val_combined: 0.0752
Epoch 45/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 192ms/step - loss: 0.5204 - pr_auc: 0.4991 - precision: 0.5410 - recall: 0.5690 - roc_auc: 0.7634 - val_loss: 0.7279 - val_pr_auc: 0.0947 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7591 - val_combined: 0.0663
Epoch 46/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 203ms/step - loss: 0.5263 - pr_auc: 0.4359 - precision: 0.4490 - recall: 0.5690 - roc_auc: 0.7540 - val_loss: 0.7018 - val_pr_auc: 0.1012 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7761 - val_combined: 0.0709
Epoch 47/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 190ms/step - loss: 0.5096 - pr_auc: 0.4819 - precision: 0.5280 - recall: 0.5690 - roc_auc: 0.7519 - val_loss: 0.6798 - val_pr_auc: 0.1030 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7808 - val_combined: 0.0721
Epoch 48/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 185ms/step - loss: 0.5028 - pr_auc: 0.5237 - precision: 0.5323 - recall: 0.5690 - roc_auc: 0.7629 - val_loss: 0.6767 - val_pr_auc: 0.1016 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7827 - val_combined: 0.0711
Epoch 49/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.5060 - pr_auc: 0.5326 - precision: 0.5804 - recall: 0.5603 - roc_auc: 0.7654 - val_loss: 0.6821 - val_pr_auc: 0.1070 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7934 - val_combined: 0.0749
Epoch 50/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 197ms/step - loss: 0.5061 - pr_auc: 0.4964 - precision: 0.5238 - recall: 0.5690 - roc_auc: 0.7785 - val_loss: 0.6289 - val_pr_auc: 0.0924 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7066 - val_combined: 0.0647
Epoch 51/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 181ms/step - loss: 0.4961 - pr_auc: 0.5503 - precision: 0.6286 - recall: 0.5690 - roc_auc: 0.7553 - val_loss: 0.6980 - val_pr_auc: 0.1068 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7896 - val_combined: 0.0748
Epoch 52/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.5071 - pr_auc: 0.4966 - precision: 0.5546 - recall: 0.5690 - roc_auc: 0.7607 - val_loss: 0.6279 - val_pr_auc: 0.1161 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7920 - val_combined: 0.0813
Epoch 53/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 207ms/step - loss: 0.4956 - pr_auc: 0.5383 - precision: 0.6204 - recall: 0.5776 - roc_auc: 0.7888 - val_loss: 0.5582 - val_pr_auc: 0.1425 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.8530 - val_combined: 0.0997
Epoch 54/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 176ms/step - loss: 0.5054 - pr_auc: 0.5264 - precision: 0.5194 - recall: 0.5776 - roc_auc: 0.7640 - val_loss: 0.5933 - val_pr_auc: 0.1171 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.8162 - val_combined: 0.0820
Epoch 55/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 201ms/step - loss: 0.4841 - pr_auc: 0.5867 - precision: 0.5185 - recall: 0.6034 - roc_auc: 0.7807 - val_loss: 0.6764 - val_pr_auc: 0.0865 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7071 - val_combined: 0.0605
Epoch 56/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 203ms/step - loss: 0.5569 - pr_auc: 0.3308 - precision: 0.3333 - recall: 0.5862 - roc_auc: 0.7726 - val_loss: 0.7586 - val_pr_auc: 0.1161 - val_precision: 0.0667 - val_recall: 0.2000 - val_roc_auc: 0.8099 - val_combined: 0.1412
Epoch 57/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 176ms/step - loss: 0.6148 - pr_auc: 0.2103 - precision: 0.2541 - recall: 0.5345 - roc_auc: 0.7121 - val_loss: 0.5743 - val_pr_auc: 0.1218 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.8209 - val_combined: 0.0853
Epoch 58/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.5497 - pr_auc: 0.3619 - precision: 0.3441 - recall: 0.5517 - roc_auc: 0.7759 - val_loss: 0.6618 - val_pr_auc: 0.1012 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7791 - val_combined: 0.0709
Epoch 59/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.4917 - pr_auc: 0.5041 - precision: 0.5214 - recall: 0.6293 - roc_auc: 0.7717 - val_loss: 0.6555 - val_pr_auc: 0.1064 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7909 - val_combined: 0.0744
Epoch 60/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 8s 177ms/step - loss: 0.4916 - pr_auc: 0.4914 - precision: 0.5496 - recall: 0.6207 - roc_auc: 0.7818 - val_loss: 0.6428 - val_pr_auc: 0.1087 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7981 - val_combined: 0.0761
Epoch 61/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.5416 - pr_auc: 0.3232 - precision: 0.3770 - recall: 0.5948 - roc_auc: 0.7626 - val_loss: 0.6519 - val_pr_auc: 0.0933 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7544 - val_combined: 0.0653
Epoch 62/200
46/46 ━━━━━━━━━━━━━━━━━━━━ 9s 202ms/step - loss: 0.5023 - pr_auc: 0.4718 - precision: 0.4451 - recall: 0.6293 - roc_auc: 0.7598 - val_loss: 0.6400 - val_pr_auc: 0.0983 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_roc_auc: 0.7747 - val_combined: 0.0688
Epoch 62: early stopping
Restoring model weights from the end of the best epoch: 12.
13/13 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step

In [ ]:
df_robustness_bench = pd.DataFrame(robustness_results_bench)
df_robustness_bench

   seed  recall   f1   roc_auc   tn  fp  fn  tp
0    38     0.0  0.0  0.640838  339  53  24   0
1    60     0.0  0.0  0.358844  363  29  24   0
2    96     0.0  0.0  0.293155  305  87  24   0
3   146     0.0  0.0  0.402742  381  11  24   0
4   162     0.0  0.0  0.272853  369  23  24   0

```python
df_robustness_bench.to_csv("df_robustness_bench.csv", index=True)
files.download("df_robustness_bench.csv")
df_robustness_bench.to_parquet("df_robustness_bench.parquet", index=True)
files.download("df_robustness_bench.parquet")
```

In [ ]:
#df_robustness_bench = import_data(file_path)

In [ ]:
df_robustness_bench = pd.concat([df_robustness_bench, pd.DataFrame({'seed': 23,
                                                                    'recall': 0,
                                                                    'f1': 0,
                                                                    'roc_auc': 0.48,
                                                                    'tn': 369,
                                                                    'fp': 23,
                                                                    'fn': 24,
                                                                    'tp': 0},
                                                                    index=[0])], ignore_index=True) #add results from baseline model
df_robustness_bench

   seed  recall   f1   roc_auc   tn  fp  fn  tp
0    38     0.0  0.0  0.640838  339  53  24   0
1    60     0.0  0.0  0.358844  363  29  24   0
2    96     0.0  0.0  0.293155  305  87  24   0
3   146     0.0  0.0  0.402742  381  11  24   0
4   162     0.0  0.0  0.272853  369  23  24   0
5    23     0.0  0.0  0.480000  369  23  24   0

In [ ]:
df_robustness_bench = df_robustness_bench.set_index('seed')[['recall',	'f1',	'roc_auc']].sort_index()
df_robustness_bench = df_robustness_bench.rename(columns={'recall':'Recall',	'f1':'F1-Score',	'roc_auc':'ROC-AUC'})

In [ ]:
df_robustness_bench.round(2)

      Recall  F1-Score  ROC-AUC
seed
23       0.0       0.0     0.48
38       0.0       0.0     0.64
60       0.0       0.0     0.36
96       0.0       0.0     0.29
146      0.0       0.0     0.40
162      0.0       0.0     0.27

In [ ]:
df_robustness_bench.mean().round(2).rename('mean')

Recall      0.00
F1-Score    0.00
ROC-AUC     0.41
Name: mean, dtype: float64

In [ ]:
df_robustness_bench.std().round(2).rename('std')

Recall      0.00
F1-Score    0.00
ROC-AUC     0.14
Name: std, dtype: float64

We refer to the project report for a discussion on the results of the LSTM sensitivity analysis to random initialization.